extends RefCounted


const LOCALES: Array[String] = ["zh_CN", "zh_TW", "en", "ja", "es", "de", "ru"]
const KEYS: Array[String] = [
	"hud", "title", "nest", "mission_title", "mission_desc", "rules", "home_note",
	"start", "settle_first", "progress", "return_win", "retreat", "confirm_retreat",
	"confirm", "cancel", "return_fail", "victory", "failure", "retreated", "upgrade",
	"need_materials", "next_preview", "story", "close", "save_failed", "mission_active",
	"prototype", "retry", "mission_paused", "main_nest"
]

const TEXTS := {
	"zh_CN": {
		"hud": "主巢 · 任务 [J]",
		"title": "主巢与出征",
		"nest": "主巢等级 {level} · 筑巢物质 {materials}",
		"mission_title": "独立任务：第一条补给线",
		"mission_desc": "在独立培养区建立菌丝补给。实际吸收 {organic} 有机营养与 {mineral} 矿物，并维持 {length} μm 成熟菌丝。",
		"rules": "临时菌落使用固定补给与基础科技；任务库存不带回。首次胜利带回 3 筑巢物质。",
		"home_note": "主巢保留；返回时结算离开期间的经营，最多 48 小时。",
		"start": "开始任务",
		"settle_first": "先让主孢子萌发",
		"progress": "有机 {organic}/{organic_goal} · 矿物 {mineral}/{mineral_goal} · 菌丝 {length}/{length_goal} μm",
		"return_win": "完成并返回主巢",
		"retreat": "撤退返回主巢",
		"confirm_retreat": "撤退不获得材料；主巢保留。",
		"confirm": "确认撤退",
		"cancel": "取消",
		"return_fail": "返回主巢",
		"victory": "任务完成：筑巢物质 +{reward}",
		"failure": "出征菌落失活；主巢保留",
		"retreated": "已撤退；未获得任务材料",
		"upgrade": "升级主巢 · 3 筑巢物质",
		"need_materials": "完成任务以取得筑巢物质",
		"next_preview": "主巢已成长：下一段剧情与挑战正在制作，本版不能继续进入。",
		"story": "补给样本已融入母体。新的育孢组织开始形成；远处的培养区等待探索。",
		"close": "关闭",
		"save_failed": "保存失败，操作未完成，请重试。",
		"mission_active": "出征中 · 主巢已保存",
		"prototype": "剧情闭环测试版 · 非完整第一章",
		"retry": "再次挑战（无首次材料）",
		"mission_paused": "任务离线暂停，回到游戏后继续。",
		"main_nest": "主巢"
	},
	"zh_TW": {
		"hud": "主巢 · 任務 [J]",
		"title": "主巢與出征",
		"nest": "主巢等級 {level} · 築巢物質 {materials}",
		"mission_title": "獨立任務：第一條補給線",
		"mission_desc": "在獨立培養區建立菌絲補給。實際吸收 {organic} 有機營養與 {mineral} 礦物，並維持 {length} μm 成熟菌絲。",
		"rules": "臨時菌落使用固定補給與基礎科技；任務庫存不帶回。首次勝利帶回 3 築巢物質。",
		"home_note": "主巢保留；返回時結算離開期間的經營，最多 48 小時。",
		"start": "開始任務",
		"settle_first": "先讓主孢子萌發",
		"progress": "有機 {organic}/{organic_goal} · 礦物 {mineral}/{mineral_goal} · 菌絲 {length}/{length_goal} μm",
		"return_win": "完成並返回主巢",
		"retreat": "撤退返回主巢",
		"confirm_retreat": "撤退不獲得材料；主巢保留。",
		"confirm": "確認撤退",
		"cancel": "取消",
		"return_fail": "返回主巢",
		"victory": "任務完成：築巢物質 +{reward}",
		"failure": "出征菌落失活；主巢保留",
		"retreated": "已撤退；未獲得任務材料",
		"upgrade": "升級主巢 · 3 築巢物質",
		"need_materials": "完成任務以取得築巢物質",
		"next_preview": "主巢已成長：下一段劇情與挑戰正在製作，本版無法繼續進入。",
		"story": "補給樣本已融入母體。新的育孢組織開始形成；遠處的培養區等待探索。",
		"close": "關閉",
		"save_failed": "儲存失敗，操作未完成，請重試。",
		"mission_active": "出征中 · 主巢已儲存",
		"prototype": "劇情閉環測試版 · 非完整第一章",
		"retry": "再次挑戰（無首次材料）",
		"mission_paused": "任務離線暫停，回到遊戲後繼續。",
		"main_nest": "主巢"
	},
	"en": {
		"hud": "Nest · Missions [J]",
		"title": "Home nest & expeditions",
		"nest": "Nest level {level} · Nest materials {materials}",
		"mission_title": "Independent mission: First supply line",
		"mission_desc": "Build a hyphal supply line in a separate culture area. Absorb {organic} organic nutrients and {mineral} minerals, and maintain {length} μm of mature hyphae.",
		"rules": "The temporary colony uses fixed supplies and basic technology. Mission stock stays behind. Your first victory brings home 3 nest materials.",
		"home_note": "Your home nest is kept. On return, its progress during your absence is calculated, up to 48 hours.",
		"start": "Start mission",
		"settle_first": "Germinate the founder spore first",
		"progress": "Organic {organic}/{organic_goal} · Minerals {mineral}/{mineral_goal} · Hyphae {length}/{length_goal} μm",
		"return_win": "Complete & return home",
		"retreat": "Retreat to home nest",
		"confirm_retreat": "Retreat gives no materials. Your home nest is kept.",
		"confirm": "Confirm retreat",
		"cancel": "Cancel",
		"return_fail": "Return to home nest",
		"victory": "Mission complete: nest materials +{reward}",
		"failure": "The expedition colony died; your home nest is kept",
		"retreated": "Retreated; no mission materials gained",
		"upgrade": "Upgrade nest · 3 nest materials",
		"need_materials": "Complete the mission to earn nest materials",
		"next_preview": "Your nest has grown. The next story and challenge are in development and unavailable in this version.",
		"story": "The supply samples have joined the parent colony. New spore-growing tissue begins to form. Distant culture areas await exploration.",
		"close": "Close",
		"save_failed": "Save failed. The action was not completed; please retry.",
		"mission_active": "On expedition · Home nest saved",
		"prototype": "Story-loop prototype · Not the full first chapter",
		"retry": "Retry (no first-win materials)",
		"mission_paused": "Missions pause while offline. Return to the game to continue.",
		"main_nest": "Home nest"
	},
	"ja": {
		"hud": "母巣 · ミッション [J]",
		"title": "母巣と遠征",
		"nest": "母巣レベル {level} · 巣の素材 {materials}",
		"mission_title": "独立ミッション：最初の補給路",
		"mission_desc": "独立した培養区に菌糸の補給路を作ろう。有機栄養 {organic} とミネラル {mineral} を実際に吸収し、成熟した菌糸を {length} μm 維持する。",
		"rules": "一時的なコロニーは固定の物資と基礎技術で開始。任務中の在庫は持ち帰れない。初勝利で巣の素材を 3 獲得。",
		"home_note": "母巣は保持される。帰還時に不在中の経営を最大 48 時間分まで精算。",
		"start": "ミッション開始",
		"settle_first": "まず主胞子を発芽させよう",
		"progress": "有機 {organic}/{organic_goal} · ミネラル {mineral}/{mineral_goal} · 菌糸 {length}/{length_goal} μm",
		"return_win": "完了して母巣へ戻る",
		"retreat": "撤退して母巣へ戻る",
		"confirm_retreat": "撤退では素材を獲得できない。母巣は保持される。",
		"confirm": "撤退を確定",
		"cancel": "キャンセル",
		"return_fail": "母巣へ戻る",
		"victory": "ミッション完了：巣の素材 +{reward}",
		"failure": "遠征コロニーは死滅した。母巣は保持されている",
		"retreated": "撤退した。ミッションの素材は未獲得",
		"upgrade": "母巣を強化 · 巣の素材 3",
		"need_materials": "ミッションを達成して巣の素材を獲得しよう",
		"next_preview": "母巣が成長した。次の物語と挑戦は制作中のため、このバージョンでは進めない。",
		"story": "補給サンプルが母体に取り込まれた。新たな胞子を育む組織が生まれ始める。遠くの培養区が探索を待っている。",
		"close": "閉じる",
		"save_failed": "保存に失敗しました。操作は未完了です。再試行してください。",
		"mission_active": "遠征中 · 母巣は保存済み",
		"prototype": "物語ループの試作版 · 第1章の完成版ではありません",
		"retry": "再挑戦（初勝利の素材なし）",
		"mission_paused": "ミッションはオフライン中は一時停止。ゲームに戻ると再開する。",
		"main_nest": "母巣"
	},
	"es": {
		"hud": "Nido · Misiones [J]",
		"title": "Nido principal y expediciones",
		"nest": "Nivel del nido {level} · Material de nido {materials}",
		"mission_title": "Misión independiente: Primera ruta de suministro",
		"mission_desc": "Crea una ruta de hifas en un área de cultivo separada. Absorbe {organic} de nutrientes orgánicos y {mineral} de minerales, y mantén {length} μm de hifas maduras.",
		"rules": "La colonia temporal empieza con suministros fijos y tecnología básica. Sus reservas no vuelven al nido. La primera victoria aporta 3 de material de nido.",
		"home_note": "El nido principal se conserva. Al volver se calcula su progreso durante tu ausencia, hasta 48 horas.",
		"start": "Iniciar misión",
		"settle_first": "Primero haz germinar la espora fundadora",
		"progress": "Orgánico {organic}/{organic_goal} · Minerales {mineral}/{mineral_goal} · Hifas {length}/{length_goal} μm",
		"return_win": "Completar y volver al nido",
		"retreat": "Retirarse al nido principal",
		"confirm_retreat": "Retirarse no da materiales. El nido principal se conserva.",
		"confirm": "Confirmar retirada",
		"cancel": "Cancelar",
		"return_fail": "Volver al nido principal",
		"victory": "Misión completada: material de nido +{reward}",
		"failure": "La colonia expedicionaria ha muerto; el nido principal se conserva",
		"retreated": "Retirada completada; sin materiales de misión",
		"upgrade": "Mejorar nido · 3 de material de nido",
		"need_materials": "Completa la misión para obtener material de nido",
		"next_preview": "El nido ha crecido. La siguiente historia y desafío están en desarrollo y no se pueden jugar en esta versión.",
		"story": "Las muestras de suministro se han integrado en la colonia madre. Empieza a formarse nuevo tejido productor de esporas. Otras áreas de cultivo esperan ser exploradas.",
		"close": "Cerrar",
		"save_failed": "No se pudo guardar. La acción no se completó; inténtalo de nuevo.",
		"mission_active": "En expedición · Nido principal guardado",
		"prototype": "Prototipo del ciclo narrativo · No es el primer capítulo completo",
		"retry": "Reintentar (sin material de primera victoria)",
		"mission_paused": "La misión se pausa mientras estás fuera del juego. Vuelve para continuar.",
		"main_nest": "Nido principal"
	},
	"de": {
		"hud": "Nest · Missionen [J]",
		"title": "Hauptnest und Expeditionen",
		"nest": "Neststufe {level} · Nistmaterial {materials}",
		"mission_title": "Separate Mission: Erste Versorgungslinie",
		"mission_desc": "Baue eine Hyphen-Versorgungslinie in einem getrennten Kulturgebiet. Nimm {organic} organische Nährstoffe und {mineral} Mineralien auf und erhalte {length} μm ausgereifte Hyphen.",
		"rules": "Die vorübergehende Kolonie startet mit festen Vorräten und Basistechnik. Missionsvorräte bleiben zurück. Der erste Sieg bringt 3 Nistmaterial zurück.",
		"home_note": "Das Hauptnest bleibt erhalten. Bei der Rückkehr wird sein Fortschritt während deiner Abwesenheit berechnet, bis zu 48 Stunden.",
		"start": "Mission starten",
		"settle_first": "Lass zuerst die Gründerspore keimen",
		"progress": "Organisch {organic}/{organic_goal} · Mineralien {mineral}/{mineral_goal} · Hyphen {length}/{length_goal} μm",
		"return_win": "Abschließen und heimkehren",
		"retreat": "Zum Hauptnest zurückziehen",
		"confirm_retreat": "Ein Rückzug bringt kein Material. Das Hauptnest bleibt erhalten.",
		"confirm": "Rückzug bestätigen",
		"cancel": "Abbrechen",
		"return_fail": "Zum Hauptnest zurück",
		"victory": "Mission abgeschlossen: Nistmaterial +{reward}",
		"failure": "Die Expeditionskolonie ist abgestorben; das Hauptnest bleibt erhalten",
		"retreated": "Zurückgezogen; kein Missionsmaterial erhalten",
		"upgrade": "Nest ausbauen · 3 Nistmaterial",
		"need_materials": "Schließe die Mission ab, um Nistmaterial zu erhalten",
		"next_preview": "Dein Nest ist gewachsen. Die nächste Geschichte und Herausforderung sind in Arbeit und in dieser Version noch nicht spielbar.",
		"story": "Die Versorgungsproben wurden in die Mutterkolonie aufgenommen. Neues sporentragendes Gewebe beginnt sich zu bilden. Ferne Kulturgebiete warten auf ihre Erkundung.",
		"close": "Schließen",
		"save_failed": "Speichern fehlgeschlagen. Die Aktion wurde nicht abgeschlossen. Bitte erneut versuchen.",
		"mission_active": "Auf Expedition · Hauptnest gespeichert",
		"prototype": "Prototyp des Handlungsablaufs · Kein vollständiges erstes Kapitel",
		"retry": "Erneut spielen (ohne Erstsiegmaterial)",
		"mission_paused": "Die Mission pausiert offline. Kehre ins Spiel zurück, um fortzufahren.",
		"main_nest": "Hauptnest"
	},
	"ru": {
		"hud": "Гнездо · Задания [J]",
		"title": "Главное гнездо и экспедиции",
		"nest": "Уровень гнезда {level} · Материал для гнезда {materials}",
		"mission_title": "Отдельное задание: Первая линия снабжения",
		"mission_desc": "Создайте линию снабжения из гиф в отдельной зоне культуры. Поглотите {organic} органики и {mineral} минералов и поддерживайте {length} μm зрелых гиф.",
		"rules": "Временная колония начинает с фиксированными запасами и базовыми технологиями. Запасы задания не переносятся домой. Первая победа приносит 3 ед. материала для гнезда.",
		"home_note": "Главное гнездо сохраняется. При возвращении рассчитывается его развитие за время отсутствия, не более 48 часов.",
		"start": "Начать задание",
		"settle_first": "Сначала прорастите спору-основательницу",
		"progress": "Органика {organic}/{organic_goal} · Минералы {mineral}/{mineral_goal} · Гифы {length}/{length_goal} μm",
		"return_win": "Завершить и вернуться",
		"retreat": "Отступить в главное гнездо",
		"confirm_retreat": "Отступление не даёт материалов. Главное гнездо сохраняется.",
		"confirm": "Подтвердить отступление",
		"cancel": "Отмена",
		"return_fail": "Вернуться в главное гнездо",
		"victory": "Задание выполнено: материал для гнезда +{reward}",
		"failure": "Экспедиционная колония погибла; главное гнездо сохранено",
		"retreated": "Отступление завершено; материалы задания не получены",
		"upgrade": "Улучшить гнездо · 3 ед. материала",
		"need_materials": "Выполните задание, чтобы получить материал для гнезда",
		"next_preview": "Гнездо выросло. Следующая история и испытание ещё в разработке и недоступны в этой версии.",
		"story": "Образцы питательных веществ стали частью материнской колонии. Начинает формироваться новая спороносная ткань. Далёкие зоны культуры ждут исследования.",
		"close": "Закрыть",
		"save_failed": "Не удалось сохранить. Действие не выполнено; попробуйте ещё раз.",
		"mission_active": "В экспедиции · Главное гнездо сохранено",
		"prototype": "Прототип сюжетного цикла · Не полная первая глава",
		"retry": "Повторить (без награды за первую победу)",
		"mission_paused": "Пока игра закрыта, задание приостановлено. Вернитесь в игру, чтобы продолжить.",
		"main_nest": "Главное гнездо"
	}
}


static func normalize_locale(locale: String) -> String:
	var value := locale.strip_edges().replace("-", "_").to_lower()
	if value.begins_with("zh_hant") or value.begins_with("zh_tw") or value.begins_with("zh_hk") or value.begins_with("zh_mo"):
		return "zh_TW"
	if value.begins_with("zh"):
		return "zh_CN"
	for candidate in ["en", "ja", "es", "de", "ru"]:
		if value == candidate or value.begins_with(candidate + "_"):
			return candidate
	return "en"


# This new campaign API takes the locale first, then a key and named values.
# Numeric formatting belongs to the caller so the displayed precision is kept.
static func text(locale: String, key: String, values: Dictionary = {}) -> String:
	var table: Dictionary = TEXTS.get(normalize_locale(locale), TEXTS["en"])
	var template := String(table.get(key, TEXTS["en"].get(key, key)))
	return template.format(values)
