extends RefCounted


const BaseWords = preload("res://scripts/campaign_localization.gd")
const LOCALES: Array[String] = ["zh_CN", "zh_TW", "en", "ja", "es", "de", "ru"]
const KEYS: Array[String] = [
	"first_contact_desc",
	"substrate_race_desc",
	"lost_network_desc",
	"two_fronts_desc",
	"toxic_frontier_desc",
	"boundary_counterattack_desc",
	"stable_colony_desc",
	"mission_goal_row",
	"mission_hint",
	"mission_locked_generic",
	"locked",
	"upgrade_cost",
	"nest_max",
	"chapter_progress",
	"chapter_end",
	"nest_benefits",
	"branch_transport",
	"branch_resilience",
	"branch_defense",
	"branch_buy",
	"branch_info",
	"branch_reserve",
	"trial_rules",
	"story_1",
	"story_2",
	"story_3",
	"story_4",
	"campaign_goal_contested_patches",
	"campaign_goal_absorbed_organic",
	"campaign_goal_absorbed_mineral",
	"campaign_goal_networks_rescued",
	"campaign_goal_relay_biomass",
	"campaign_goal_cargo_organic",
	"campaign_goal_cargo_mineral",
	"campaign_goal_units_returned",
	"campaign_goal_target_defeated",
	"campaign_action_begin_rescue",
	"trial_waves",
	"trial_enemies",
	"trial_organic",
	"trial_mineral",
	"trial_network",
	"trial_start_wave",
	"trial_wave_active",
	"trial_finished",
	"trial_warning_east",
	"trial_warning_west",
	"trial_warning_two_fronts",
	"mission_failed",
	"mission_failed_hint",
	"campaign_marker_contested_patch",
	"campaign_marker_orphan_network",
	"campaign_marker_damaged_relay",
	"campaign_note_contested",
	"campaign_note_rescue_prepare",
	"campaign_note_rescue_remaining",
	"campaign_note_rescue_recovered",
	"campaign_note_toxin_returns",
	"campaign_note_scout_east",
]

# Narrative text never supplies objective numbers; live mission definitions do.
const TEXTS := {
	"zh_CN": {
		"first_contact_desc": "培养区边缘出现了陌生孢子。使用自己的主巢布局整备防线，再主动开始下一波，击退入侵并保住菌落。",
		"substrate_race_desc": "原地分裂的细菌正在争夺富集培养基。向争夺区建立采集网络，实际吸收所需营养；选择抢占、绕行或利用已激活的食性。",
		"lost_network_desc": "一段旧网络正在失去活性。开始救援后接管孤立菌丝，恢复受损中继核心的生物量，重新建立能够存活的连接。",
		"two_fronts_desc": "主巢两侧的补给同时受到威胁。整备运输、维护与防御，主动开启各波次，在击退入侵的同时维持补给网络。",
		"toxic_frontier_desc": "代谢产物在资源区附近形成了危险区域。规划孢子的采集和返程路线，运回所需物资，并让外出的孢子安全返回。",
		"boundary_counterattack_desc": "竞争菌落堵住了扩张边界。侦察并组织补给，处理防守威胁，最终击败指定敌方核心；基础兵种也能完成任务。",
		"stable_colony_desc": "主巢即将接受完整的培养试验。逐波抵御入侵，同时维持营养吸收和成熟菌丝网络；完成全部指标，让样本成为稳定菌落。",
		"mission_goal_row": "{name}：{current}/{target}",
		"mission_hint": "按 [J] 查看目标与阶段",
		"mission_locked_generic": "需要主巢 {level} 级，并完成{mission}",
		"locked": "未解锁",
		"upgrade_cost": "主巢升至 {level} 级 · {cost} 材料",
		"nest_max": "主巢已满级",
		"chapter_progress": "第一章 {done}/9",
		"chapter_end": "第一章完成。样本已形成稳定菌落，可以继续经营主巢或重玩任务。后续尺度尚未制作。",
		"nest_benefits": "主巢成长：2 级运输载量 +10%，3 级核心回复 +10%，4 级对真菌核心和守卫伤害 +10%。仅在主巢与主巢挑战生效。",
		"branch_transport": "运输组织",
		"branch_resilience": "韧性组织",
		"branch_defense": "防御组织",
		"branch_buy": "{branch} {level}/2 · {cost} 材料",
		"branch_info": "每级分别提升运输载量、核心回复或对真菌核心与守卫的伤害 15%。三项建设仅在主巢和主巢挑战生效。",
		"branch_reserve": "为后续主线升级保留 {reserve} 材料",
		"trial_rules": "挑战使用主巢快照，每波由你主动开始。结束后恢复战前状态，仅首次胜利材料带回；挑战期间不另计主巢离线收益。",
		"story_1": "培养记录：孢子开始萌发，细菌丝接触到附近营养。稳定供给比快速蔓延更重要。",
		"story_2": "培养记录：外出孢子将远处资源运回，补给网络不再局限于主巢周围。新的接触也带来了防御需求。",
		"story_3": "培养记录：资源竞争与局部损伤暴露了网络的薄弱处。分散采集和中继修复使菌落能够继续生长。",
		"story_4": "培养记录：吸收、运输与防御已能共同维持菌落。培养皿中的样本稳定下来，更大尺度的旅程仍在等待。",
		"campaign_goal_contested_patches": "已利用争夺资源区",
		"campaign_goal_absorbed_organic": "实际吸收有机",
		"campaign_goal_absorbed_mineral": "实际吸收矿物",
		"campaign_goal_networks_rescued": "救回网络",
		"campaign_goal_relay_biomass": "中继生物量（%）",
		"campaign_goal_cargo_organic": "孢子运回有机",
		"campaign_goal_cargo_mineral": "孢子运回矿物",
		"campaign_goal_units_returned": "安全返回孢子",
		"campaign_goal_target_defeated": "指定目标已击败",
		"campaign_action_begin_rescue": "开始网络救援",
		"trial_waves": "已完成波次",
		"trial_enemies": "已击退来袭孢子",
		"trial_organic": "实际吸收有机",
		"trial_mineral": "实际吸收矿物",
		"trial_network": "成熟菌丝 (μm)",
		"trial_start_wave": "开始下一波",
		"trial_wave_active": "本波进行中",
		"trial_finished": "挑战目标已完成",
		"trial_warning_east": "来袭方向：东侧",
		"trial_warning_west": "来袭方向：西侧",
		"trial_warning_two_fronts": "来袭方向：东西两侧",
		"mission_failed": "任务失败：关键目标已失效，可返回主巢。",
		"mission_failed_hint": "任务失败 · [J] 返回",
		"campaign_marker_contested_patch": "争夺资源区",
		"campaign_marker_orphan_network": "待救孤网",
		"campaign_marker_damaged_relay": "受损中继",
		"campaign_note_contested": "把成熟且存活的菌丝伸入两个标记区；吸收目标仍按实际吸收入账计算。",
		"campaign_note_rescue_prepare": "先整备并延伸至标记附近，再点击开始救援。开封后有 {minutes} 分钟接管孤网；不会复活死去的核心。",
		"campaign_note_rescue_remaining": "接管窗口还剩 {seconds} 秒。",
		"campaign_note_rescue_recovered": "孤网已接管，继续修复受损中继并完成补给。",
		"campaign_note_toxin_returns": "两名不同孢子必须携货回到兵营，空载侦察不计。南侧路线可以绕过毒区。",
		"campaign_note_scout_east": "向东侦察竞争菌落，延伸补给后再进攻。"
	},
	"zh_TW": {
		"first_contact_desc": "培養區邊緣出現了陌生孢子。使用自己的主巢布局整備防線，再主動開始下一波，擊退入侵並保住菌落。",
		"substrate_race_desc": "原地分裂的細菌正在爭奪富集培養基。向爭奪區建立採集網路，實際吸收所需營養；選擇搶占、繞行或利用已啟用的食性。",
		"lost_network_desc": "一段舊網路正在失去活性。開始救援後接管孤立菌絲，恢復受損中繼核心的生物量，重新建立能夠存活的連接。",
		"two_fronts_desc": "主巢兩側的補給同時受到威脅。整備運輸、維護與防禦，主動開啟各波次，在擊退入侵的同時維持補給網路。",
		"toxic_frontier_desc": "代謝產物在資源區附近形成了危險區域。規劃孢子的採集和返程路線，運回所需物資，並讓外出的孢子安全返回。",
		"boundary_counterattack_desc": "競爭菌落堵住了擴張邊界。偵察並組織補給，處理防守威脅，最終擊敗指定敵方核心；基礎兵種也能完成任務。",
		"stable_colony_desc": "主巢即將接受完整的培養試驗。逐波抵禦入侵，同時維持營養吸收和成熟菌絲網路；完成全部指標，讓樣本成為穩定菌落。",
		"mission_goal_row": "{name}：{current}/{target}",
		"mission_hint": "按 [J] 查看目標與階段",
		"mission_locked_generic": "需要主巢 {level} 級，並完成{mission}",
		"locked": "未解鎖",
		"upgrade_cost": "主巢升至 {level} 級 · {cost} 材料",
		"nest_max": "主巢已滿級",
		"chapter_progress": "第一章 {done}/9",
		"chapter_end": "第一章完成。樣本已形成穩定菌落，可以繼續經營主巢或重玩任務。後續尺度尚未製作。",
		"nest_benefits": "主巢成長：2 級運輸載量 +10%，3 級核心回復 +10%，4 級對真菌核心和守衛傷害 +10%。僅在主巢與主巢挑戰生效。",
		"branch_transport": "運輸組織",
		"branch_resilience": "韌性組織",
		"branch_defense": "防禦組織",
		"branch_buy": "{branch} {level}/2 · {cost} 材料",
		"branch_info": "每級分別提升運輸載量、核心回復或對真菌核心與守衛的傷害 15%。三項建設僅在主巢和主巢挑戰生效。",
		"branch_reserve": "為後續主線升級保留 {reserve} 材料",
		"trial_rules": "挑戰使用主巢快照，每波由你主動開始。結束後恢復戰前狀態，僅首次勝利材料帶回；挑戰期間不另計主巢離線收益。",
		"story_1": "培養記錄：孢子開始萌發，細菌絲接觸到附近營養。穩定供給比快速蔓延更重要。",
		"story_2": "培養記錄：外出孢子將遠處資源運回，補給網路不再侷限於主巢周圍。新的接觸也帶來了防禦需求。",
		"story_3": "培養記錄：資源競爭與局部損傷暴露了網路的薄弱處。分散採集和中繼修復使菌落能夠繼續生長。",
		"story_4": "培養記錄：吸收、運輸與防禦已能共同維持菌落。培養皿中的樣本穩定下來，更大尺度的旅程仍在等待。",
		"campaign_goal_contested_patches": "已利用爭奪資源區",
		"campaign_goal_absorbed_organic": "實際吸收有機",
		"campaign_goal_absorbed_mineral": "實際吸收礦物",
		"campaign_goal_networks_rescued": "救回網路",
		"campaign_goal_relay_biomass": "中繼生物量（%）",
		"campaign_goal_cargo_organic": "孢子運回有機",
		"campaign_goal_cargo_mineral": "孢子運回礦物",
		"campaign_goal_units_returned": "安全返回孢子",
		"campaign_goal_target_defeated": "指定目標已擊敗",
		"campaign_action_begin_rescue": "開始網路救援",
		"trial_waves": "已完成波次",
		"trial_enemies": "已擊退來襲孢子",
		"trial_organic": "實際吸收有機",
		"trial_mineral": "實際吸收礦物",
		"trial_network": "成熟菌絲 (μm)",
		"trial_start_wave": "開始下一波",
		"trial_wave_active": "本波進行中",
		"trial_finished": "挑戰目標已完成",
		"trial_warning_east": "來襲方向：東側",
		"trial_warning_west": "來襲方向：西側",
		"trial_warning_two_fronts": "來襲方向：東西兩側",
		"mission_failed": "任務失敗：關鍵目標已失效，可返回主巢。",
		"mission_failed_hint": "任務失敗 · [J] 返回",
		"campaign_marker_contested_patch": "爭奪資源區",
		"campaign_marker_orphan_network": "待救孤網",
		"campaign_marker_damaged_relay": "受損中繼",
		"campaign_note_contested": "把成熟且存活的菌絲伸入兩個標記區；吸收目標仍按實際吸收入帳計算。",
		"campaign_note_rescue_prepare": "先整備並延伸至標記附近，再點擊開始救援。開封後有 {minutes} 分鐘接管孤網；不會復活死去的核心。",
		"campaign_note_rescue_remaining": "接管窗口還剩 {seconds} 秒。",
		"campaign_note_rescue_recovered": "孤網已接管，繼續修復受損中繼並完成補給。",
		"campaign_note_toxin_returns": "兩名不同孢子必須攜貨回到兵營，空載偵察不計。南側路線可以繞過毒區。",
		"campaign_note_scout_east": "向東偵察競爭菌落，延伸補給後再進攻。"
	},
	"en": {
		"first_contact_desc": "Unfamiliar spores have appeared at the edge of the culture. Prepare defenses using your own nest layout, then start each wave when ready. Repel the intruders and keep the colony alive.",
		"substrate_race_desc": "Stationary bacteria are dividing across rich substrate. Establish gathering routes into contested patches and absorb the required nutrients. Claim ground, go around, or use a diet you have activated.",
		"lost_network_desc": "An old network is losing viability. Begin the rescue, reconnect isolated hyphae, and restore the damaged relay core's biomass to rebuild a living connection.",
		"two_fronts_desc": "Supplies on both sides of the nest are under threat. Prepare transport, repair and defense, then start each wave. Repel the attacks while maintaining your supply network.",
		"toxic_frontier_desc": "Metabolic byproducts have made areas near the resources hazardous. Plan gathering and return routes, bring back the required cargo, and get your foraging spores home safely.",
		"boundary_counterattack_desc": "A rival colony blocks the expansion boundary. Scout and organize supplies, deal with its defenses, then defeat the marked enemy core. Basic units can complete this mission too.",
		"stable_colony_desc": "The nest faces a full culture trial. Repel each wave while maintaining nutrient uptake and a mature hyphal network. Meet every objective to establish a stable colony.",
		"mission_goal_row": "{name}: {current}/{target}",
		"mission_hint": "Press [J] for objectives and stages",
		"mission_locked_generic": "Requires nest level {level} and completion of {mission}",
		"locked": "Locked",
		"upgrade_cost": "Upgrade nest to level {level} · {cost} materials",
		"nest_max": "Nest at maximum level",
		"chapter_progress": "Chapter 1: {done}/9",
		"chapter_end": "Chapter 1 complete. The sample has formed a stable colony. Keep managing the nest or replay missions. Later scales are not implemented yet.",
		"nest_benefits": "Nest growth: level 2 adds 10% cargo capacity, level 3 adds 10% core recovery, and level 4 adds 10% damage against fungal cores and guards. Applies only at home and in nest challenges.",
		"branch_transport": "Transport tissue",
		"branch_resilience": "Resilient tissue",
		"branch_defense": "Defensive tissue",
		"branch_buy": "{branch} {level}/2 · {cost} materials",
		"branch_info": "Each level adds 15% to cargo capacity, core recovery, or damage against fungal cores and guards, respectively. These branches apply only at home and in nest challenges.",
		"branch_reserve": "Reserve {reserve} materials for remaining main-path upgrades",
		"trial_rules": "Challenges use a snapshot of your nest; you start every wave manually. Finishing restores the pre-battle state. Only first-win materials carry back; challenge time earns no separate home offline progress.",
		"story_1": "Culture log: the spore is germinating, and fine hyphae have reached nearby nutrients. A steady supply matters more than rapid spread.",
		"story_2": "Culture log: roaming spores bring distant resources home, extending supply beyond the nest's surroundings. New contacts also call for defenses.",
		"story_3": "Culture log: competition and local damage have exposed weak links. Distributed gathering and repaired relays allow the colony to keep growing.",
		"story_4": "Culture log: uptake, transport and defense now sustain the colony together. The sample in the dish is stable; the journey to larger scales still lies ahead.",
		"campaign_goal_contested_patches": "Contested patches used",
		"campaign_goal_absorbed_organic": "Organic nutrients absorbed",
		"campaign_goal_absorbed_mineral": "Minerals absorbed",
		"campaign_goal_networks_rescued": "Networks rescued",
		"campaign_goal_relay_biomass": "Relay biomass (%)",
		"campaign_goal_cargo_organic": "Organic cargo delivered",
		"campaign_goal_cargo_mineral": "Mineral cargo delivered",
		"campaign_goal_units_returned": "Spores returned safely",
		"campaign_goal_target_defeated": "Marked target defeated",
		"campaign_action_begin_rescue": "Begin network rescue",
		"trial_waves": "Waves completed",
		"trial_enemies": "Raiders defeated",
		"trial_organic": "Organic nutrients absorbed",
		"trial_mineral": "Minerals absorbed",
		"trial_network": "Mature hyphae (μm)",
		"trial_start_wave": "Start next wave",
		"trial_wave_active": "Wave in progress",
		"trial_finished": "Challenge objectives complete",
		"trial_warning_east": "Attack direction: east",
		"trial_warning_west": "Attack direction: west",
		"trial_warning_two_fronts": "Attack direction: east and west",
		"mission_failed": "Mission failed: a critical objective was lost. You can return to the nest.",
		"mission_failed_hint": "Failed · [J] Return",
		"campaign_marker_contested_patch": "Contested resource patch",
		"campaign_marker_orphan_network": "Isolated network to rescue",
		"campaign_marker_damaged_relay": "Damaged relay",
		"campaign_note_contested": "Extend mature living hyphae into both marked areas. Nutrient goals still count actual absorbed amounts.",
		"campaign_note_rescue_prepare": "Prepare and extend near the markers before starting the rescue. Once opened, you have {minutes} minutes to reconnect the isolated networks; dead cores do not revive.",
		"campaign_note_rescue_remaining": "Reconnection window: {seconds} seconds left.",
		"campaign_note_rescue_recovered": "The isolated networks are reconnected. Repair the damaged relay and finish the supply objective.",
		"campaign_note_toxin_returns": "Two different spores must carry cargo back to barracks. Empty scouting trips do not count. The southern route avoids the toxin zone.",
		"campaign_note_scout_east": "Scout east for the rival colony, extend supply, then attack."
	},
	"ja": {
		"first_contact_desc": "培養区の端に未知の胞子が現れた。自分の母巣の配置を使って防衛を整え、準備ができたら各ウェーブを開始しよう。侵入者を退け、コロニーを守る。",
		"substrate_race_desc": "その場で分裂する細菌が、栄養豊富な培地を奪い合っている。競合する資源区へ採集網を伸ばし、必要な栄養を実際に吸収しよう。先取り、迂回、有効にした食性の利用から方針を選べる。",
		"lost_network_desc": "古い菌糸網が活性を失いつつある。救援を開始したら孤立した菌糸をつなぎ、傷ついた中継コアの生物量を回復して、生きた接続を取り戻そう。",
		"two_fronts_desc": "母巣の両側で補給が脅かされている。輸送、修復、防衛を整えてから各ウェーブを開始し、補給網を維持しながら侵入者を退けよう。",
		"toxic_frontier_desc": "代謝産物によって資源区の近くに危険地帯ができた。採集と帰還の経路を考え、必要な物資を運び戻し、外出した胞子を無事に帰還させよう。",
		"boundary_counterattack_desc": "競合コロニーが拡張の境界を塞いでいる。偵察と補給を整え、防衛を突破して指定の敵コアを倒そう。基本兵種でも達成できる。",
		"stable_colony_desc": "母巣に総合的な培養試験が待っている。栄養吸収と成熟した菌糸網を維持しながら各ウェーブを退け、すべての目標を満たして安定したコロニーを作ろう。",
		"mission_goal_row": "{name}：{current}/{target}",
		"mission_hint": "[J] で目標と段階を確認",
		"mission_locked_generic": "母巣レベル {level} と「{mission}」の達成が必要",
		"locked": "未解放",
		"upgrade_cost": "母巣をレベル {level} へ · 素材 {cost}",
		"nest_max": "母巣は最大レベル",
		"chapter_progress": "第1章 {done}/9",
		"chapter_end": "第1章達成。サンプルは安定したコロニーになった。母巣の経営やミッションの再挑戦を続けられる。次のスケールはまだ未実装。",
		"nest_benefits": "母巣の成長：レベル 2 で運搬量 +10%、レベル 3 でコアの回復 +10%、レベル 4 で真菌コアと守衛へのダメージ +10%。母巣と母巣の挑戦でのみ有効。",
		"branch_transport": "輸送組織",
		"branch_resilience": "強靭な組織",
		"branch_defense": "防御組織",
		"branch_buy": "{branch} {level}/2 · 素材 {cost}",
		"branch_info": "各レベルで、それぞれ運搬量、コアの回復、真菌コアと守衛へのダメージが 15% 増える。母巣と母巣の挑戦でのみ有効。",
		"branch_reserve": "今後の必須強化に素材 {reserve} を確保",
		"trial_rules": "挑戦は母巣のスナップショットを使い、各ウェーブを手動で開始する。終了後は戦闘前の状態に戻り、初勝利の素材だけを持ち帰る。挑戦中の時間は母巣のオフライン収益に加算されない。",
		"story_1": "培養記録：胞子が発芽し、細い菌糸が近くの栄養に届いた。急速に広がることより、安定した補給が重要だ。",
		"story_2": "培養記録：外出した胞子が遠くの資源を持ち帰り、補給は母巣の周囲を越えて広がった。新たな接触に備え、防衛も必要になっている。",
		"story_3": "培養記録：資源競争と局所的な損傷から、菌糸網の弱点が見えてきた。採集先の分散と中継の修復によって、成長を続けられる。",
		"story_4": "培養記録：吸収、輸送、防衛が連携してコロニーを支えるようになった。培養皿のサンプルは安定し、より大きなスケールへの旅はこれからだ。",
		"campaign_goal_contested_patches": "利用した競合資源区",
		"campaign_goal_absorbed_organic": "吸収した有機栄養",
		"campaign_goal_absorbed_mineral": "吸収したミネラル",
		"campaign_goal_networks_rescued": "救援した菌糸網",
		"campaign_goal_relay_biomass": "中継の生物量（%）",
		"campaign_goal_cargo_organic": "運搬した有機栄養",
		"campaign_goal_cargo_mineral": "運搬したミネラル",
		"campaign_goal_units_returned": "無事に帰還した胞子",
		"campaign_goal_target_defeated": "指定目標の撃破",
		"campaign_action_begin_rescue": "菌糸網の救援を開始",
		"trial_waves": "完了したウェーブ",
		"trial_enemies": "撃退した襲来胞子",
		"trial_organic": "吸収した有機栄養",
		"trial_mineral": "吸収したミネラル",
		"trial_network": "成熟した菌糸 (μm)",
		"trial_start_wave": "次のウェーブを開始",
		"trial_wave_active": "ウェーブ進行中",
		"trial_finished": "挑戦の目標を達成",
		"trial_warning_east": "襲来方向：東",
		"trial_warning_west": "襲来方向：西",
		"trial_warning_two_fronts": "襲来方向：東西両側",
		"mission_failed": "ミッション失敗：重要な目標を維持できなかった。母巣へ戻れる。",
		"mission_failed_hint": "任務失敗 · [J] 戻る",
		"campaign_marker_contested_patch": "競合する資源区",
		"campaign_marker_orphan_network": "救援を待つ孤立菌糸網",
		"campaign_marker_damaged_relay": "損傷した中継",
		"campaign_note_contested": "成熟した生きた菌糸を両方のマーカー内へ伸ばそう。栄養目標は実際に吸収した量で判定される。",
		"campaign_note_rescue_prepare": "準備を整え、マーカー付近まで菌糸を伸ばしてから救援を開始しよう。開封後 {minutes} 分以内に孤立菌糸網を接続する。死んだコアは復活しない。",
		"campaign_note_rescue_remaining": "接続できる時間は残り {seconds} 秒。",
		"campaign_note_rescue_recovered": "孤立菌糸網を接続した。損傷した中継を修復し、補給目標を達成しよう。",
		"campaign_note_toxin_returns": "2体の別々の胞子が物資を持って兵舎へ帰る必要がある。空荷の偵察は数えない。南側の経路で毒素地帯を回避できる。",
		"campaign_note_scout_east": "東へ偵察して競合コロニーを見つけ、補給を伸ばしてから攻撃しよう。"
	},
	"es": {
		"first_contact_desc": "Han aparecido esporas desconocidas en el borde del cultivo. Prepara las defensas con la distribución de tu propio nido y comienza cada oleada cuando estés listo. Rechaza a los intrusos y conserva la colonia.",
		"substrate_race_desc": "Las bacterias inmóviles se dividen por el sustrato rico en nutrientes. Extiende la red de recolección hacia las zonas disputadas y absorbe los nutrientes necesarios. Ocupa terreno, busca un rodeo o aprovecha una dieta activada.",
		"lost_network_desc": "Una red antigua está perdiendo vitalidad. Inicia el rescate, reconecta las hifas aisladas y recupera la biomasa del núcleo de enlace dañado para restablecer una conexión viva.",
		"two_fronts_desc": "El suministro está amenazado a ambos lados del nido. Prepara el transporte, la reparación y la defensa antes de iniciar cada oleada. Rechaza los ataques sin perder la red de suministro.",
		"toxic_frontier_desc": "Los subproductos metabólicos han creado zonas peligrosas cerca de los recursos. Planifica las rutas de recogida y regreso, entrega la carga necesaria y haz que las esporas vuelvan a salvo.",
		"boundary_counterattack_desc": "Una colonia rival bloquea el límite de expansión. Explora y organiza el suministro, supera sus defensas y derrota al núcleo enemigo señalado. También puedes lograrlo con unidades básicas.",
		"stable_colony_desc": "El nido afronta una prueba completa de cultivo. Rechaza cada oleada mientras mantienes la absorción de nutrientes y una red de hifas maduras. Cumple todos los objetivos para formar una colonia estable.",
		"mission_goal_row": "{name}: {current}/{target}",
		"mission_hint": "Pulsa [J] para ver objetivos y etapas",
		"mission_locked_generic": "Requiere nido de nivel {level} y completar {mission}",
		"locked": "Bloqueada",
		"upgrade_cost": "Nido a nivel {level} · {cost} materiales",
		"nest_max": "Nido al nivel máximo",
		"chapter_progress": "Capítulo 1: {done}/9",
		"chapter_end": "Capítulo 1 completado. La muestra ha formado una colonia estable. Puedes seguir gestionando el nido o repetir misiones. Las escalas posteriores aún no están implementadas.",
		"nest_benefits": "Crecimiento del nido: nivel 2, capacidad de carga +10%; nivel 3, recuperación de núcleos +10%; nivel 4, daño contra núcleos fúngicos y guardianes +10%. Solo en el nido y sus desafíos.",
		"branch_transport": "Tejido de transporte",
		"branch_resilience": "Tejido resistente",
		"branch_defense": "Tejido defensivo",
		"branch_buy": "{branch} {level}/2 · {cost} materiales",
		"branch_info": "Cada nivel aumenta un 15% la capacidad de carga, la recuperación de núcleos o el daño contra núcleos fúngicos y guardianes, respectivamente. Solo se aplica en el nido y sus desafíos.",
		"branch_reserve": "Reserva {reserve} materiales para las mejoras obligatorias restantes",
		"trial_rules": "Los desafíos usan una copia del nido; tú inicias cada oleada. Al terminar, se restaura el estado previo al combate. Solo vuelven los materiales de la primera victoria; el tiempo del desafío no genera progreso adicional del nido sin conexión.",
		"story_1": "Registro de cultivo: la espora germina y las hifas finas alcanzan nutrientes cercanos. Un suministro estable importa más que extenderse deprisa.",
		"story_2": "Registro de cultivo: las esporas traen recursos lejanos y el suministro supera los alrededores del nido. Los nuevos contactos también exigen defensas.",
		"story_3": "Registro de cultivo: la competencia y el daño local han revelado puntos débiles. Diversificar la recogida y reparar enlaces permite que la colonia siga creciendo.",
		"story_4": "Registro de cultivo: la absorción, el transporte y la defensa ya sostienen juntos la colonia. La muestra de la placa es estable; el viaje hacia escalas mayores aún está por llegar.",
		"campaign_goal_contested_patches": "Zonas disputadas aprovechadas",
		"campaign_goal_absorbed_organic": "Nutrientes orgánicos absorbidos",
		"campaign_goal_absorbed_mineral": "Minerales absorbidos",
		"campaign_goal_networks_rescued": "Redes rescatadas",
		"campaign_goal_relay_biomass": "Biomasa del enlace (%)",
		"campaign_goal_cargo_organic": "Carga orgánica entregada",
		"campaign_goal_cargo_mineral": "Carga mineral entregada",
		"campaign_goal_units_returned": "Esporas que regresaron a salvo",
		"campaign_goal_target_defeated": "Objetivo señalado derrotado",
		"campaign_action_begin_rescue": "Iniciar rescate de la red",
		"trial_waves": "Oleadas completadas",
		"trial_enemies": "Invasores derrotados",
		"trial_organic": "Nutrientes orgánicos absorbidos",
		"trial_mineral": "Minerales absorbidos",
		"trial_network": "Hifas maduras (μm)",
		"trial_start_wave": "Iniciar siguiente oleada",
		"trial_wave_active": "Oleada en curso",
		"trial_finished": "Objetivos del desafío completados",
		"trial_warning_east": "Dirección del ataque: este",
		"trial_warning_west": "Dirección del ataque: oeste",
		"trial_warning_two_fronts": "Dirección del ataque: este y oeste",
		"mission_failed": "Misión fallida: se ha perdido un objetivo esencial. Puedes volver al nido.",
		"mission_failed_hint": "Fallo · [J] Volver",
		"campaign_marker_contested_patch": "Zona de recursos disputada",
		"campaign_marker_orphan_network": "Red aislada por rescatar",
		"campaign_marker_damaged_relay": "Enlace dañado",
		"campaign_note_contested": "Extiende hifas maduras y vivas hasta ambas zonas marcadas. Los objetivos de nutrientes siguen contando la cantidad realmente absorbida.",
		"campaign_note_rescue_prepare": "Prepárate y extiende las hifas cerca de los marcadores antes de iniciar el rescate. Tras abrir las muestras, tienes {minutes} minutos para reconectar las redes; los núcleos muertos no reviven.",
		"campaign_note_rescue_remaining": "Tiempo para reconectar: {seconds} segundos.",
		"campaign_note_rescue_recovered": "Las redes aisladas están reconectadas. Repara el enlace dañado y completa el objetivo de suministro.",
		"campaign_note_toxin_returns": "Dos esporas distintas deben volver al cuartel con carga. Las visitas de exploración sin carga no cuentan. La ruta sur evita la zona tóxica.",
		"campaign_note_scout_east": "Explora hacia el este para localizar la colonia rival, extiende el suministro y después ataca."
	},
	"de": {
		"first_contact_desc": "Am Rand der Kultur sind fremde Sporen aufgetaucht. Bereite die Verteidigung mit deinem eigenen Nestaufbau vor und starte jede Welle, wenn du bereit bist. Wehre die Eindringlinge ab und erhalte die Kolonie.",
		"substrate_race_desc": "Ortsfeste Bakterien vermehren sich auf nährstoffreichem Substrat. Erschließe umkämpfte Vorkommen und nimm die benötigten Nährstoffe auf. Besetze Flächen, wähle Umwege oder nutze eine aktivierte Ernährung.",
		"lost_network_desc": "Ein altes Netzwerk verliert an Lebenskraft. Beginne die Rettung, verbinde isolierte Hyphen und stelle die Biomasse des beschädigten Verbindungskerns wieder her, um eine lebende Verbindung zu schaffen.",
		"two_fronts_desc": "Die Versorgung auf beiden Seiten des Nests ist bedroht. Bereite Transport, Reparatur und Verteidigung vor und starte jede Welle selbst. Wehre die Angriffe ab und erhalte das Versorgungsnetz.",
		"toxic_frontier_desc": "Stoffwechselprodukte haben gefährliche Bereiche nahe den Ressourcen gebildet. Plane Sammel- und Rückwege, liefere die nötige Fracht ab und bringe die ausgeschickten Sporen sicher zurück.",
		"boundary_counterattack_desc": "Eine rivalisierende Kolonie blockiert die Ausbreitungsgrenze. Erkunde das Gebiet, sichere die Versorgung, überwinde ihre Verteidigung und besiege den markierten feindlichen Kern. Das gelingt auch mit Basiseinheiten.",
		"stable_colony_desc": "Das Nest steht vor einer umfassenden Kulturprüfung. Wehre jede Welle ab und erhalte dabei die Nährstoffaufnahme und ein ausgereiftes Hyphennetz. Erfülle alle Ziele, um eine stabile Kolonie zu bilden.",
		"mission_goal_row": "{name}: {current}/{target}",
		"mission_hint": "[J] zeigt Ziele und Phasen",
		"mission_locked_generic": "Benötigt Neststufe {level} und Abschluss von {mission}",
		"locked": "Gesperrt",
		"upgrade_cost": "Nest auf Stufe {level} · {cost} Material",
		"nest_max": "Nest auf Höchststufe",
		"chapter_progress": "Kapitel 1: {done}/9",
		"chapter_end": "Kapitel 1 abgeschlossen. Die Probe bildet nun eine stabile Kolonie. Du kannst das Nest weiter ausbauen oder Missionen wiederholen. Spätere Maßstabsebenen sind noch nicht umgesetzt.",
		"nest_benefits": "Nestwachstum: Stufe 2 gibt +10% Frachtkapazität, Stufe 3 +10% Kernregeneration, Stufe 4 +10% Schaden gegen Pilzkerne und Wächter. Gilt nur im Hauptnest und in Nestprüfungen.",
		"branch_transport": "Transportgewebe",
		"branch_resilience": "Robustes Gewebe",
		"branch_defense": "Abwehrgewebe",
		"branch_buy": "{branch} {level}/2 · {cost} Material",
		"branch_info": "Jede Stufe erhöht jeweils Frachtkapazität, Kernregeneration oder Schaden gegen Pilzkerne und Wächter um 15%. Diese Zweige wirken nur im Hauptnest und in Nestprüfungen.",
		"branch_reserve": "{reserve} Material für verbleibende Pflichtausbauten reservieren",
		"trial_rules": "Prüfungen nutzen eine Momentaufnahme deines Nests; jede Welle startet manuell. Danach wird der Zustand vor dem Kampf wiederhergestellt. Nur Erstsiegmaterial wird übernommen; die Prüfungszeit zählt nicht zusätzlich als Offline-Fortschritt des Hauptnests.",
		"story_1": "Kulturprotokoll: Die Spore keimt, und feine Hyphen erreichen nahe Nährstoffe. Eine stetige Versorgung ist wichtiger als schnelle Ausbreitung.",
		"story_2": "Kulturprotokoll: Ausgeschickte Sporen bringen ferne Ressourcen zurück; die Versorgung reicht über die Nestumgebung hinaus. Neue Kontakte erfordern auch Verteidigung.",
		"story_3": "Kulturprotokoll: Konkurrenz und örtliche Schäden haben Schwachstellen offengelegt. Verteiltes Sammeln und reparierte Verbindungen ermöglichen weiteres Wachstum.",
		"story_4": "Kulturprotokoll: Aufnahme, Transport und Abwehr erhalten die Kolonie nun gemeinsam. Die Probe in der Schale ist stabil; der Weg zu größeren Maßstäben steht noch bevor.",
		"campaign_goal_contested_patches": "Genutzte umkämpfte Vorkommen",
		"campaign_goal_absorbed_organic": "Aufgenommene Organik",
		"campaign_goal_absorbed_mineral": "Aufgenommene Mineralien",
		"campaign_goal_networks_rescued": "Gerettete Netzwerke",
		"campaign_goal_relay_biomass": "Verbindungskern-Biomasse (%)",
		"campaign_goal_cargo_organic": "Gelieferte Organikfracht",
		"campaign_goal_cargo_mineral": "Gelieferte Mineralfracht",
		"campaign_goal_units_returned": "Sicher zurückgekehrte Sporen",
		"campaign_goal_target_defeated": "Markiertes Ziel besiegt",
		"campaign_action_begin_rescue": "Netzwerkrettung starten",
		"trial_waves": "Abgeschlossene Wellen",
		"trial_enemies": "Besiegte Angreifer",
		"trial_organic": "Aufgenommene Organik",
		"trial_mineral": "Aufgenommene Mineralien",
		"trial_network": "Ausgereifte Hyphen (μm)",
		"trial_start_wave": "Nächste Welle starten",
		"trial_wave_active": "Welle läuft",
		"trial_finished": "Prüfungsziele erfüllt",
		"trial_warning_east": "Angriffsrichtung: Osten",
		"trial_warning_west": "Angriffsrichtung: Westen",
		"trial_warning_two_fronts": "Angriffsrichtung: Ost und West",
		"mission_failed": "Mission gescheitert: Ein wichtiges Ziel ging verloren. Du kannst zum Nest zurückkehren.",
		"mission_failed_hint": "Gescheitert · [J] Zurück",
		"campaign_marker_contested_patch": "Umkämpftes Vorkommen",
		"campaign_marker_orphan_network": "Isoliertes Netzwerk retten",
		"campaign_marker_damaged_relay": "Beschädigte Verbindung",
		"campaign_note_contested": "Strecke ausgereifte, lebende Hyphen in beide markierten Bereiche. Für Nährstoffziele zählt weiterhin nur die tatsächlich aufgenommene Menge.",
		"campaign_note_rescue_prepare": "Bereite dich vor und wachse bis nahe an die Markierungen, bevor du die Rettung startest. Nach dem Öffnen bleiben {minutes} Minuten zum Verbinden der isolierten Netze; tote Kerne werden nicht wiederbelebt.",
		"campaign_note_rescue_remaining": "Zeit zum Verbinden: noch {seconds} Sekunden.",
		"campaign_note_rescue_recovered": "Die isolierten Netze sind verbunden. Repariere den beschädigten Verbindungskern und erfülle das Versorgungsziel.",
		"campaign_note_toxin_returns": "Zwei verschiedene Sporen müssen Fracht zur Kaserne zurückbringen. Erkundungen ohne Fracht zählen nicht. Die südliche Route umgeht die Giftzone.",
		"campaign_note_scout_east": "Erkunde im Osten die rivalisierende Kolonie, erweitere die Versorgung und greife dann an."
	},
	"ru": {
		"first_contact_desc": "На краю культуры появились незнакомые споры. Подготовьте оборону своего гнезда и запускайте каждую волну, когда будете готовы. Отразите вторжение и сохраните колонию.",
		"substrate_race_desc": "Неподвижные бактерии делятся на богатом питательными веществами субстрате. Проложите сеть сбора к спорным участкам и поглотите нужные вещества. Занимайте участки, обходите соперников или используйте активированный тип питания.",
		"lost_network_desc": "Старая сеть теряет жизнеспособность. Начните спасение, подключите изолированные гифы и восстановите биомассу повреждённого связующего ядра, чтобы вернуть живое соединение.",
		"two_fronts_desc": "Снабжение под угрозой с двух сторон гнезда. Подготовьте перевозку, ремонт и оборону, а затем запускайте волны вручную. Отражайте нападения, сохраняя сеть снабжения.",
		"toxic_frontier_desc": "Продукты обмена создали опасные зоны рядом с ресурсами. Спланируйте пути сбора и возвращения, доставьте нужный груз и обеспечьте безопасное возвращение вышедших спор.",
		"boundary_counterattack_desc": "Соперничающая колония перекрыла границу расширения. Проведите разведку, наладьте снабжение, преодолейте оборону и уничтожьте отмеченное вражеское ядро. Задание можно пройти и базовыми бойцами.",
		"stable_colony_desc": "Гнезду предстоит полное испытание культуры. Отражайте волны, поддерживая поглощение питательных веществ и сеть зрелых гиф. Выполните все цели, чтобы сформировать устойчивую колонию.",
		"mission_goal_row": "{name}: {current}/{target}",
		"mission_hint": "[J] — цели и этапы",
		"mission_locked_generic": "Нужны гнездо уровня {level} и завершение задания «{mission}»",
		"locked": "Закрыто",
		"upgrade_cost": "Гнездо до уровня {level} · Материал: {cost}",
		"nest_max": "Гнездо максимального уровня",
		"chapter_progress": "Глава 1: {done}/9",
		"chapter_end": "Первая глава завершена. Образец сформировал устойчивую колонию. Можно продолжать развивать гнездо или повторять задания. Следующие масштабы ещё не реализованы.",
		"nest_benefits": "Рост гнезда: уровень 2 даёт +10% вместимости груза, уровень 3 — +10% восстановления ядер, уровень 4 — +10% урона грибным ядрам и стражам. Только в главном гнезде и его испытаниях.",
		"branch_transport": "Транспортная ткань",
		"branch_resilience": "Устойчивая ткань",
		"branch_defense": "Защитная ткань",
		"branch_buy": "{branch} {level}/2 · Материал: {cost}",
		"branch_info": "Каждый уровень повышает соответственно вместимость груза, восстановление ядер или урон грибным ядрам и стражам на 15%. Эти ветви действуют только в главном гнезде и его испытаниях.",
		"branch_reserve": "Запас материала для обязательных улучшений: {reserve}",
		"trial_rules": "Испытание использует снимок гнезда; каждую волну вы запускаете вручную. После завершения восстанавливается состояние до боя. Переносятся только материалы первой победы; время испытания не даёт отдельного офлайн-прогресса главного гнезда.",
		"story_1": "Журнал культуры: спора прорастает, тонкие гифы достигли ближайших питательных веществ. Стабильное снабжение важнее быстрого распространения.",
		"story_2": "Журнал культуры: подвижные споры доставляют дальние ресурсы, расширяя снабжение за пределы окрестностей гнезда. Новые контакты требуют и обороны.",
		"story_3": "Журнал культуры: конкуренция и локальные повреждения выявили слабые места сети. Разные точки сбора и восстановленные связи позволяют колонии расти дальше.",
		"story_4": "Журнал культуры: поглощение, транспорт и оборона теперь совместно поддерживают колонию. Образец в чашке стабилен; путь к большим масштабам ещё впереди.",
		"campaign_goal_contested_patches": "Освоенные спорные участки",
		"campaign_goal_absorbed_organic": "Поглощённая органика",
		"campaign_goal_absorbed_mineral": "Поглощённые минералы",
		"campaign_goal_networks_rescued": "Спасённые сети",
		"campaign_goal_relay_biomass": "Биомасса связующего ядра (%)",
		"campaign_goal_cargo_organic": "Доставленная органика",
		"campaign_goal_cargo_mineral": "Доставленные минералы",
		"campaign_goal_units_returned": "Безопасно вернувшиеся споры",
		"campaign_goal_target_defeated": "Отмеченная цель уничтожена",
		"campaign_action_begin_rescue": "Начать спасение сети",
		"trial_waves": "Завершённые волны",
		"trial_enemies": "Побеждённые налётчики",
		"trial_organic": "Поглощённая органика",
		"trial_mineral": "Поглощённые минералы",
		"trial_network": "Зрелые гифы (μm)",
		"trial_start_wave": "Начать следующую волну",
		"trial_wave_active": "Волна идёт",
		"trial_finished": "Цели испытания выполнены",
		"trial_warning_east": "Направление атаки: восток",
		"trial_warning_west": "Направление атаки: запад",
		"trial_warning_two_fronts": "Направление атаки: восток и запад",
		"mission_failed": "Задание провалено: ключевая цель потеряна. Можно вернуться в гнездо.",
		"mission_failed_hint": "Провал · [J] Назад",
		"campaign_marker_contested_patch": "Спорный участок ресурсов",
		"campaign_marker_orphan_network": "Изолированная сеть для спасения",
		"campaign_marker_damaged_relay": "Повреждённое связующее ядро",
		"campaign_note_contested": "Протяните зрелые живые гифы в обе отмеченные зоны. Цели по питанию по-прежнему учитывают только реально поглощённое количество.",
		"campaign_note_rescue_prepare": "Подготовьтесь и протяните гифы к меткам, затем начните спасение. После вскрытия образцов у вас будет {minutes} мин. на подключение сетей; погибшие ядра не оживают.",
		"campaign_note_rescue_remaining": "Время на подключение: осталось {seconds} сек.",
		"campaign_note_rescue_recovered": "Изолированные сети подключены. Восстановите повреждённое связующее ядро и выполните цель по снабжению.",
		"campaign_note_toxin_returns": "Две разные споры должны вернуться в казарму с грузом. Разведка без груза не учитывается. Южный путь позволяет обойти токсичную зону.",
		"campaign_note_scout_east": "Разведайте соперничающую колонию на востоке, протяните снабжение и затем атакуйте."
	}
}


static func normalize_locale(locale: String) -> String:
	return BaseWords.normalize_locale(locale)


static func text(locale: String, key: String, values: Dictionary = {}) -> String:
	var table: Dictionary = TEXTS.get(normalize_locale(locale), TEXTS["en"])
	var template := String(table.get(key, TEXTS["en"].get(key, key)))
	return template.format(values)
