extends RefCounted


const BaseWords = preload("res://scripts/campaign_localization.gd")
const LOCALES: Array[String] = ["zh_CN", "zh_TW", "en", "ja", "es", "de", "ru"]
const KEYS: Array[String] = [
	"remote_pantry_title",
	"remote_pantry_desc",
	"transport_progress",
	"transport_progress_compact",
	"hint_barracks",
	"hint_chelator",
	"hint_transport_organic",
	"hint_transport_mineral",
	"choose_mission",
	"mission_locked",
	"mission_ready",
	"mission_done",
	"remote_pantry_story",
	"inheritance_note",
	"first_supply_title",
	"first_contact_title",
	"substrate_race_title",
	"lost_network_title",
	"two_fronts_title",
	"toxic_frontier_title",
	"boundary_counterattack_title",
	"stable_colony_title",
	"planned",
	"chapter_roster",
]

# Campaign expansion copy is separate so the original mission keeps its API.
const TEXTS := {
	"zh_CN": {
		"remote_pantry_title": "独立任务：远端粮仓",
		"remote_pantry_desc": "派孢子实际运回 {organic} 有机营养与 {mineral} 矿物。菌丝吸收量和现有库存不计入目标。",
		"transport_progress": "运回有机 {organic}/{organic_goal} · 矿物 {mineral}/{mineral_goal}",
		"transport_progress_compact": "运回：有 {organic}/{organic_goal} 矿 {mineral}/{mineral_goal}",
		"hint_barracks": "先攒 2 DNA，建立兵营",
		"hint_chelator": "商店：4 DNA 解锁螯合孢子",
		"hint_transport_organic": "生产游猎孢子，设置采区并运回有机",
		"hint_transport_mineral": "生产螯合孢子，设置采区并运回矿物",
		"choose_mission": "选择任务",
		"mission_locked": "先完成第一条补给线，并将主巢升至 2 级",
		"mission_ready": "可出征",
		"mission_done": "已完成",
		"remote_pantry_story": "远端样本接入了补给网络。主巢不再只依赖身边的养分；第一次接触挑战仍在制作，暂不能进入。",
		"inheritance_note": "继承主巢已解锁的兵种；食性专属兵需在本关重新激活对应食性。强化等级不继承。",
		"first_supply_title": "第一条补给线",
		"first_contact_title": "主巢挑战：第一次接触",
		"substrate_race_title": "培养基争夺",
		"lost_network_title": "失联网络",
		"two_fronts_title": "主巢挑战：双线压力",
		"toxic_frontier_title": "污染前缘",
		"boundary_counterattack_title": "边界反攻",
		"stable_colony_title": "主巢挑战：稳定菌落",
		"planned": "制作中，不能进入",
		"chapter_roster": "第一章任务计划"
	},
	"zh_TW": {
		"remote_pantry_title": "獨立任務：遠端糧倉",
		"remote_pantry_desc": "派孢子實際運回 {organic} 有機營養與 {mineral} 礦物。菌絲吸收量和現有庫存不計入目標。",
		"transport_progress": "運回有機 {organic}/{organic_goal} · 礦物 {mineral}/{mineral_goal}",
		"transport_progress_compact": "運回：有 {organic}/{organic_goal} 礦 {mineral}/{mineral_goal}",
		"hint_barracks": "先存 2 DNA，建立兵營",
		"hint_chelator": "商店：4 DNA 解鎖螯合孢子",
		"hint_transport_organic": "生產遊獵孢子，設定採區並運回有機",
		"hint_transport_mineral": "生產螯合孢子，設定採區並運回礦物",
		"choose_mission": "選擇任務",
		"mission_locked": "先完成第一條補給線，並將主巢升至 2 級",
		"mission_ready": "可出征",
		"mission_done": "已完成",
		"remote_pantry_story": "遠端樣本接入了補給網路。主巢不再只依賴身邊的養分；第一次接觸挑戰仍在製作，暫不能進入。",
		"inheritance_note": "繼承主巢已解鎖的兵種；食性專屬兵須在本關重新啟用對應食性。強化等級不繼承。",
		"first_supply_title": "第一條補給線",
		"first_contact_title": "主巢挑戰：第一次接觸",
		"substrate_race_title": "培養基爭奪",
		"lost_network_title": "失聯網路",
		"two_fronts_title": "主巢挑戰：雙線壓力",
		"toxic_frontier_title": "污染前緣",
		"boundary_counterattack_title": "邊界反攻",
		"stable_colony_title": "主巢挑戰：穩定菌落",
		"planned": "製作中，不能進入",
		"chapter_roster": "第一章任務計畫"
	},
	"en": {
		"remote_pantry_title": "Independent mission: Remote pantry",
		"remote_pantry_desc": "Have spores bring back {organic} organic nutrients and {mineral} minerals. Hyphal absorption and existing stock do not count.",
		"transport_progress": "Delivered organic {organic}/{organic_goal} · Minerals {mineral}/{mineral_goal}",
		"transport_progress_compact": "Back: O {organic}/{organic_goal} M {mineral}/{mineral_goal}",
		"hint_barracks": "Save 2 DNA and build barracks",
		"hint_chelator": "Shop: unlock Chelator Spore for 4 DNA",
		"hint_transport_organic": "Foragers: set a zone, bring organics home",
		"hint_transport_mineral": "Chelators: set a zone, bring minerals home",
		"choose_mission": "Choose mission",
		"mission_locked": "Complete First supply line and upgrade the nest to level 2 first",
		"mission_ready": "Available",
		"mission_done": "Completed",
		"remote_pantry_story": "Remote samples now feed the supply network. The nest no longer depends only on nearby nutrients. First contact is still in development and cannot be entered yet.",
		"inheritance_note": "Unit unlocks carry over from the home nest. Diet specialists require their diet to be activated again in this mission. Upgrade levels do not carry over.",
		"first_supply_title": "First supply line",
		"first_contact_title": "Nest challenge: First contact",
		"substrate_race_title": "Race for the substrate",
		"lost_network_title": "Disconnected network",
		"two_fronts_title": "Nest challenge: Two fronts",
		"toxic_frontier_title": "Toxic frontier",
		"boundary_counterattack_title": "Boundary counterattack",
		"stable_colony_title": "Nest challenge: Stable colony",
		"planned": "In development — unavailable",
		"chapter_roster": "Chapter 1 mission plan"
	},
	"ja": {
		"remote_pantry_title": "独立ミッション：遠方の貯蔵庫",
		"remote_pantry_desc": "胞子で有機栄養 {organic} とミネラル {mineral} を実際に運び戻そう。菌糸による吸収量と現在の在庫は目標に含まれない。",
		"transport_progress": "運搬済み：有機 {organic}/{organic_goal} · ミネラル {mineral}/{mineral_goal}",
		"transport_progress_compact": "運搬：有 {organic}/{organic_goal} 鉱 {mineral}/{mineral_goal}",
		"hint_barracks": "まず 2 DNA を貯めて兵舎を建てよう",
		"hint_chelator": "ショップ：4 DNA でキレート胞子を解放",
		"hint_transport_organic": "採集胞子を生産し、採集区から有機栄養を運ぼう",
		"hint_transport_mineral": "キレート胞子を生産し、採集区から鉱物を運ぼう",
		"choose_mission": "ミッションを選択",
		"mission_locked": "最初の補給路を達成し、母巣をレベル 2 にしよう",
		"mission_ready": "出征可能",
		"mission_done": "達成済み",
		"remote_pantry_story": "遠方のサンプルが補給網につながった。母巣は近くの栄養だけに頼らず成長できる。「最初の接触」は制作中のため、まだ挑戦できない。",
		"inheritance_note": "母巣で解放した兵種を引き継ぐ。食性特化兵は、このミッションで対応する食性を再び有効にする必要がある。強化レベルは引き継がない。",
		"first_supply_title": "最初の補給路",
		"first_contact_title": "母巣の挑戦：最初の接触",
		"substrate_race_title": "培養基の争奪",
		"lost_network_title": "途切れた菌糸網",
		"two_fronts_title": "母巣の挑戦：二方面の圧力",
		"toxic_frontier_title": "汚染の境界",
		"boundary_counterattack_title": "境界での反撃",
		"stable_colony_title": "母巣の挑戦：安定したコロニー",
		"planned": "制作中・まだ入れません",
		"chapter_roster": "第1章のミッション計画"
	},
	"es": {
		"remote_pantry_title": "Misión independiente: Despensa remota",
		"remote_pantry_desc": "Haz que las esporas traigan {organic} de nutrientes orgánicos y {mineral} de minerales. La absorción por hifas y las reservas existentes no cuentan.",
		"transport_progress": "Orgánico entregado {organic}/{organic_goal} · Minerales {mineral}/{mineral_goal}",
		"transport_progress_compact": "Entrega: O {organic}/{organic_goal} M {mineral}/{mineral_goal}",
		"hint_barracks": "Ahorra 2 ADN y construye un cuartel",
		"hint_chelator": "Tienda: espora quelante por 4 ADN",
		"hint_transport_organic": "Crea recolectoras; zona y entrega orgánica",
		"hint_transport_mineral": "Crea quelantes; zona y entrega mineral",
		"choose_mission": "Elegir misión",
		"mission_locked": "Completa Primera ruta de suministro y mejora el nido al nivel 2",
		"mission_ready": "Disponible",
		"mission_done": "Completada",
		"remote_pantry_story": "Las muestras remotas ya alimentan la red de suministro. El nido deja de depender solo de los nutrientes cercanos. Primer contacto sigue en desarrollo y aún no se puede jugar.",
		"inheritance_note": "Se conservan las unidades desbloqueadas en el nido. Las especialistas necesitan que actives de nuevo su dieta durante la misión. Los niveles de mejora no se conservan.",
		"first_supply_title": "Primera ruta de suministro",
		"first_contact_title": "Desafío del nido: Primer contacto",
		"substrate_race_title": "Disputa por el sustrato",
		"lost_network_title": "Red desconectada",
		"two_fronts_title": "Desafío del nido: Dos frentes",
		"toxic_frontier_title": "Frontera tóxica",
		"boundary_counterattack_title": "Contraataque en el límite",
		"stable_colony_title": "Desafío del nido: Colonia estable",
		"planned": "En desarrollo; no disponible",
		"chapter_roster": "Plan de misiones del capítulo 1"
	},
	"de": {
		"remote_pantry_title": "Separate Mission: Ferne Vorräte",
		"remote_pantry_desc": "Lass Sporen {organic} organische Nährstoffe und {mineral} Mineralien zurückbringen. Aufnahme durch Hyphen und vorhandene Vorräte zählen nicht.",
		"transport_progress": "Gelieferte Organik {organic}/{organic_goal} · Mineralien {mineral}/{mineral_goal}",
		"transport_progress_compact": "Geliefert: O {organic}/{organic_goal} M {mineral}/{mineral_goal}",
		"hint_barracks": "2 DNA sparen und eine Kaserne bauen",
		"hint_chelator": "Laden: Chelatspore für 4 DNA freischalten",
		"hint_transport_organic": "Sammler: Zone setzen, Organik heimbringen",
		"hint_transport_mineral": "Chelatsporen: Zone setzen, Mineralien holen",
		"choose_mission": "Mission wählen",
		"mission_locked": "Erste Versorgungslinie abschließen und das Nest auf Stufe 2 ausbauen",
		"mission_ready": "Verfügbar",
		"mission_done": "Abgeschlossen",
		"remote_pantry_story": "Ferne Proben versorgen nun das Netzwerk. Das Nest ist nicht mehr allein auf Nährstoffe in seiner Nähe angewiesen. Erster Kontakt ist noch in Entwicklung und nicht spielbar.",
		"inheritance_note": "Im Hauptnest freigeschaltete Einheiten bleiben verfügbar. Für Ernährungsspezialisten muss die passende Ernährung in dieser Mission erneut aktiviert werden. Verbesserungsstufen werden nicht übernommen.",
		"first_supply_title": "Erste Versorgungslinie",
		"first_contact_title": "Nestprüfung: Erster Kontakt",
		"substrate_race_title": "Kampf ums Substrat",
		"lost_network_title": "Getrenntes Netzwerk",
		"two_fronts_title": "Nestprüfung: Zwei Fronten",
		"toxic_frontier_title": "Giftige Grenze",
		"boundary_counterattack_title": "Gegenangriff an der Grenze",
		"stable_colony_title": "Nestprüfung: Stabile Kolonie",
		"planned": "In Entwicklung; nicht spielbar",
		"chapter_roster": "Missionsplan für Kapitel 1"
	},
	"ru": {
		"remote_pantry_title": "Отдельное задание: Дальние запасы",
		"remote_pantry_desc": "Доставьте спорами {organic} органики и {mineral} минералов. Поглощение гифами и имеющиеся запасы не учитываются.",
		"transport_progress": "Доставлено: органика {organic}/{organic_goal} · Минералы {mineral}/{mineral_goal}",
		"transport_progress_compact": "Доставка: О {organic}/{organic_goal} М {mineral}/{mineral_goal}",
		"hint_barracks": "Накопите 2 ДНК и постройте казарму",
		"hint_chelator": "Магазин: откройте спору-хелатор за 4 ДНК",
		"hint_transport_organic": "Сборщики: зона сбора и доставка органики",
		"hint_transport_mineral": "Хелаторы: зона сбора и доставка минералов",
		"choose_mission": "Выбрать задание",
		"mission_locked": "Пройдите Первую линию снабжения и улучшите гнездо до уровня 2",
		"mission_ready": "Доступно",
		"mission_done": "Пройдено",
		"remote_pantry_story": "Дальние образцы пополнили сеть снабжения. Гнездо больше не зависит только от ближайших питательных веществ. Первое соприкосновение ещё в разработке и пока недоступно.",
		"inheritance_note": "Открытые в главном гнезде типы бойцов сохраняются. Для пищевых специалистов нужно заново активировать нужный тип питания в этом задании. Уровни улучшений не переносятся.",
		"first_supply_title": "Первая линия снабжения",
		"first_contact_title": "Испытание гнезда: Первое соприкосновение",
		"substrate_race_title": "Борьба за субстрат",
		"lost_network_title": "Оборванная сеть",
		"two_fronts_title": "Испытание гнезда: Два фронта",
		"toxic_frontier_title": "Токсичный рубеж",
		"boundary_counterattack_title": "Контратака на границе",
		"stable_colony_title": "Испытание гнезда: Устойчивая колония",
		"planned": "В разработке; вход недоступен",
		"chapter_roster": "План заданий первой главы"
	}
}


static func normalize_locale(locale: String) -> String:
	return BaseWords.normalize_locale(locale)


static func text(locale: String, key: String, values: Dictionary = {}) -> String:
	var table: Dictionary = TEXTS.get(normalize_locale(locale), TEXTS["en"])
	var template := String(table.get(key, TEXTS["en"].get(key, key)))
	return template.format(values)
