extends RefCounted
class_name DeveloperLocalization


const LOCALES: Array[String] = ["zh_CN", "zh_TW", "en", "ja", "es", "de", "ru"]
const PAGE_IDS: Array[String] = ["colony", "world", "progress"]

const PAGE_ACTION_IDS := {
	"colony": [
		"speed_1", "speed_10", "speed_60", "add_resources",
		"add_dna", "heal_cores", "unlock_upgrades", "spawn_core",
		"spawn_barracks", "cycle_unit", "spawn_unit"
	],
	"world": [
		"reveal_map", "restore_fog", "place_organic", "place_mineral",
		"place_bacteria", "place_rival", "spawn_guard", "place_bloom", "place_toxin",
		"trigger_sporefall", "clear_hazards"
	],
	"progress": [
		"advance_task", "complete_chapter", "reset_chapter", "complete_goals",
		"reset_goals", "save_snapshot", "load_snapshot", "clear_dev_save"
	]
}

const TEXTS := {
	"zh_CN": {
		"mode_label_fmt": "开发者模式　%s",
		"state_enabled": "开启",
		"state_disabled": "关闭",
		"tools_entry": "开发者工具",
		"panel_title": "开发者工具 · 沙盒档案",
		"panel_subtitle": "三页测试工具只作用于独立开发档",
		"badge": "DEV · 独立存档",
		"separate_save_hint": "开发档使用独立存档，不影响普通培养与成就。",
		"switch_to_normal": "切换到普通档",
		"switch_to_developer": "切换到开发档",
		"switch_confirm_title": "确认切换档案",
		"switch_confirm_body": "将保存当前档案并切换到另一套独立存档。",
		"switch_applied_fmt": "当前档案：%s",
		"achievements_guard": "平台成就已保护；开发档不会提交正式成就。",
		"loading_title": "正在载入开发档案",
		"loading_progress_fmt": "载入开发档案 · %d%%",
		"loading_prepare": "准备沙盒环境",
		"loading_settings": "读取开发者设置",
		"loading_world": "构建培养世界",
		"loading_save": "载入独立存档",
		"loading_finalize": "同步界面与模拟",
		"loading_complete": "开发档案载入完成",
		"offline_settlement_title": "正在结算离线进度",
		"offline_settlement_progress_fmt": "离线进度 · %d%%",
		"loading_failed_fmt": "载入失败：%s",
		"page_label_fmt": "第 %d/%d 页 · %s",
		"page_colony": "菌落与资源",
		"page_world": "世界与事件",
		"page_progress": "进度与存档",
		"page_colony_desc": "调整速度、资源、核心与升级。",
		"page_world_desc": "揭示地图并放置资源、生物与事件。",
		"page_progress_desc": "测试章节、长期目标与开发快照。",
		"action_speed_1": "速度 1×",
		"action_speed_10": "速度 10×",
		"action_speed_60": "速度 60×",
		"speed_toast_fmt": "开发者速度：%d×",
		"action_add_resources": "+100 有机 · +10 矿物",
		"action_add_dna": "+10 DNA",
		"action_heal_cores": "恢复全部核心",
		"action_unlock_upgrades": "解锁全部升级",
		"action_spawn_core": "放置孢子核心",
		"action_spawn_barracks": "放置兵营核心",
		"action_cycle_unit_fmt": "切换兵种：%s",
		"action_spawn_unit_fmt": "生产单位：%s",
		"action_reveal_map": "揭示整张地图",
		"action_restore_fog": "恢复未探索黑幕",
		"action_place_organic": "放置有机富集区",
		"action_place_mineral": "放置矿物富集区",
		"action_place_bacteria": "放置细菌群落",
		"action_place_rival": "放置竞争菌落",
		"action_spawn_guard": "放置竞争菌守卫",
		"action_place_bloom": "放置细菌暴发",
		"action_place_toxin": "放置毒素区",
		"action_trigger_sporefall": "触发孢子雨",
		"action_clear_hazards": "清除事件与威胁",
		"action_advance_task": "完成当前章节任务",
		"action_complete_chapter": "完成第一章",
		"action_reset_chapter": "重置章节进度",
		"action_complete_goals": "完成全部长期目标",
		"action_reset_goals": "重置长期目标",
		"action_save_snapshot": "保存开发快照",
		"action_load_snapshot": "载入开发快照",
		"action_clear_dev_save": "清除开发存档",
		"clear_confirm_title": "确认清除开发存档",
		"clear_confirm_body": "只会删除独立开发存档；普通培养不会受影响。",
		"action_applied_fmt": "已执行：%s",
		"action_blocked": "此工具只可在开发档中使用",
		"placement_left_confirm": "左键放置 · 右键或 Esc 取消",
		"placement_cancel": "已取消放置",
		"placement_out_of_range": "目标位置超出培养世界范围",
		"placement_blocked": "此处被界面或现有结构占用",
		"placement_organic_hint": "点击地图放置有机营养富集区",
		"placement_mineral_hint": "点击地图放置矿物离子富集区",
		"placement_bacteria_hint": "点击地图放置静止扩张的细菌群落",
		"placement_rival_hint": "点击地图放置竞争性真菌核心",
		"placement_bloom_hint": "点击地图放置细菌暴发事件",
		"placement_toxin_hint": "点击地图放置生态毒素区",
		"placement_core_hint": "点击已探索区域放置己方孢子核心",
		"placement_done_fmt": "已放置：%s",
		"previous_page": "上一页",
		"next_page": "下一页",
		"back": "返回",
		"close": "关闭"
	},
	"zh_TW": {
		"mode_label_fmt": "開發者模式　%s",
		"state_enabled": "開啟",
		"state_disabled": "關閉",
		"tools_entry": "開發者工具",
		"panel_title": "開發者工具 · 沙盒存檔",
		"panel_subtitle": "三頁測試工具只作用於獨立開發存檔",
		"badge": "DEV · 獨立存檔",
		"separate_save_hint": "開發存檔使用獨立儲存，不影響一般培養與成就。",
		"switch_to_normal": "切換至一般存檔",
		"switch_to_developer": "切換至開發存檔",
		"switch_confirm_title": "確認切換存檔",
		"switch_confirm_body": "將儲存目前存檔並切換至另一套獨立存檔。",
		"switch_applied_fmt": "目前存檔：%s",
		"achievements_guard": "平台成就已受保護；開發存檔不會提交正式成就。",
		"loading_title": "正在載入開發存檔",
		"loading_progress_fmt": "載入開發存檔 · %d%%",
		"loading_prepare": "準備沙盒環境",
		"loading_settings": "讀取開發者設定",
		"loading_world": "建立培養世界",
		"loading_save": "載入獨立存檔",
		"loading_finalize": "同步介面與模擬",
		"loading_complete": "開發存檔載入完成",
		"offline_settlement_title": "正在結算離線進度",
		"offline_settlement_progress_fmt": "離線進度 · %d%%",
		"loading_failed_fmt": "載入失敗：%s",
		"page_label_fmt": "第 %d/%d 頁 · %s",
		"page_colony": "菌落與資源",
		"page_world": "世界與事件",
		"page_progress": "進度與存檔",
		"page_colony_desc": "調整速度、資源、核心與升級。",
		"page_world_desc": "揭示地圖並放置資源、生物與事件。",
		"page_progress_desc": "測試章節、長期目標與開發快照。",
		"action_speed_1": "速度 1×",
		"action_speed_10": "速度 10×",
		"action_speed_60": "速度 60×",
		"speed_toast_fmt": "開發者速度：%d×",
		"action_add_resources": "+100 有機 · +10 礦物",
		"action_add_dna": "+10 DNA",
		"action_heal_cores": "恢復全部核心",
		"action_unlock_upgrades": "解鎖全部升級",
		"action_spawn_core": "放置孢子核心",
		"action_spawn_barracks": "放置兵營核心",
		"action_cycle_unit_fmt": "切換兵種：%s",
		"action_spawn_unit_fmt": "生產單位：%s",
		"action_reveal_map": "揭示整張地圖",
		"action_restore_fog": "恢復未探索黑幕",
		"action_place_organic": "放置有機富集區",
		"action_place_mineral": "放置礦物富集區",
		"action_place_bacteria": "放置細菌群落",
		"action_place_rival": "放置競爭菌落",
		"action_spawn_guard": "放置競爭菌守衛",
		"action_place_bloom": "放置細菌暴發",
		"action_place_toxin": "放置毒素區",
		"action_trigger_sporefall": "觸發孢子雨",
		"action_clear_hazards": "清除事件與威脅",
		"action_advance_task": "完成目前章節任務",
		"action_complete_chapter": "完成第一章",
		"action_reset_chapter": "重設章節進度",
		"action_complete_goals": "完成全部長期目標",
		"action_reset_goals": "重設長期目標",
		"action_save_snapshot": "儲存開發快照",
		"action_load_snapshot": "載入開發快照",
		"action_clear_dev_save": "清除開發存檔",
		"clear_confirm_title": "確認清除開發存檔",
		"clear_confirm_body": "只會刪除獨立開發存檔；一般培養不受影響。",
		"action_applied_fmt": "已執行：%s",
		"action_blocked": "此工具只可在開發存檔中使用",
		"placement_left_confirm": "左鍵放置 · 右鍵或 Esc 取消",
		"placement_cancel": "已取消放置",
		"placement_out_of_range": "目標位置超出培養世界範圍",
		"placement_blocked": "此處被介面或現有結構占用",
		"placement_organic_hint": "點擊地圖放置有機營養富集區",
		"placement_mineral_hint": "點擊地圖放置礦物離子富集區",
		"placement_bacteria_hint": "點擊地圖放置靜止擴張的細菌群落",
		"placement_rival_hint": "點擊地圖放置競爭性真菌核心",
		"placement_bloom_hint": "點擊地圖放置細菌暴發事件",
		"placement_toxin_hint": "點擊地圖放置生態毒素區",
		"placement_core_hint": "點擊已探索區域放置己方孢子核心",
		"placement_done_fmt": "已放置：%s",
		"previous_page": "上一頁",
		"next_page": "下一頁",
		"back": "返回",
		"close": "關閉"
	},
	"en": {
		"mode_label_fmt": "Developer mode  %s",
		"state_enabled": "On",
		"state_disabled": "Off",
		"tools_entry": "Developer tools",
		"panel_title": "Developer tools · Sandbox profile",
		"panel_subtitle": "Three pages of test tools affect only the separate developer save",
		"badge": "DEV · Separate save",
		"separate_save_hint": "The developer profile uses a separate save and cannot affect regular progress or achievements.",
		"switch_to_normal": "Switch to regular profile",
		"switch_to_developer": "Switch to developer profile",
		"switch_confirm_title": "Confirm profile switch",
		"switch_confirm_body": "The current profile will be saved before switching to the other separate save.",
		"switch_applied_fmt": "Current profile: %s",
		"achievements_guard": "Platform achievements are protected and are never submitted by the developer profile.",
		"loading_title": "Loading developer profile",
		"loading_progress_fmt": "Loading developer profile · %d%%",
		"loading_prepare": "Preparing sandbox environment",
		"loading_settings": "Reading developer settings",
		"loading_world": "Building culture world",
		"loading_save": "Loading separate save",
		"loading_finalize": "Synchronizing interface and simulation",
		"loading_complete": "Developer profile loaded",
		"offline_settlement_title": "Settling offline progress",
		"offline_settlement_progress_fmt": "Offline progress · %d%%",
		"loading_failed_fmt": "Load failed: %s",
		"page_label_fmt": "Page %d/%d · %s",
		"page_colony": "Colony & resources",
		"page_world": "World & events",
		"page_progress": "Progress & saves",
		"page_colony_desc": "Adjust speed, resources, cores, and upgrades.",
		"page_world_desc": "Reveal the map and place resources, organisms, and events.",
		"page_progress_desc": "Test chapter flow, long-term goals, and developer snapshots.",
		"action_speed_1": "Speed 1×",
		"action_speed_10": "Speed 10×",
		"action_speed_60": "Speed 60×",
		"speed_toast_fmt": "Developer speed: %d×",
		"action_add_resources": "+100 organic · +10 minerals",
		"action_add_dna": "+10 DNA",
		"action_heal_cores": "Restore all cores",
		"action_unlock_upgrades": "Unlock all upgrades",
		"action_spawn_core": "Place spore core",
		"action_spawn_barracks": "Place barracks core",
		"action_cycle_unit_fmt": "Cycle unit: %s",
		"action_spawn_unit_fmt": "Spawn unit: %s",
		"action_reveal_map": "Reveal entire map",
		"action_restore_fog": "Restore unexplored fog",
		"action_place_organic": "Place organic hotspot",
		"action_place_mineral": "Place mineral hotspot",
		"action_place_bacteria": "Place bacterial colony",
		"action_place_rival": "Place rival colony",
		"action_spawn_guard": "Place rival guard",
		"action_place_bloom": "Place bacterial bloom",
		"action_place_toxin": "Place toxin zone",
		"action_trigger_sporefall": "Trigger sporefall",
		"action_clear_hazards": "Clear events and threats",
		"action_advance_task": "Complete current chapter task",
		"action_complete_chapter": "Complete Chapter 1",
		"action_reset_chapter": "Reset chapter progress",
		"action_complete_goals": "Complete all long-term goals",
		"action_reset_goals": "Reset long-term goals",
		"action_save_snapshot": "Save developer snapshot",
		"action_load_snapshot": "Load developer snapshot",
		"action_clear_dev_save": "Clear developer save",
		"clear_confirm_title": "Clear developer save?",
		"clear_confirm_body": "Only the separate developer save will be deleted. The regular culture is safe.",
		"action_applied_fmt": "Applied: %s",
		"action_blocked": "This tool is available only in the developer profile",
		"placement_left_confirm": "Left-click to place · Right-click or Esc to cancel",
		"placement_cancel": "Placement cancelled",
		"placement_out_of_range": "The target is outside the culture world",
		"placement_blocked": "The interface or an existing structure occupies this location",
		"placement_organic_hint": "Click the map to place an organic nutrient hotspot",
		"placement_mineral_hint": "Click the map to place a mineral ion hotspot",
		"placement_bacteria_hint": "Click the map to place a stationary expanding bacterial colony",
		"placement_rival_hint": "Click the map to place a rival fungal core",
		"placement_bloom_hint": "Click the map to place a bacterial bloom event",
		"placement_toxin_hint": "Click the map to place an ecological toxin zone",
		"placement_core_hint": "Click explored ground to place a friendly spore core",
		"placement_done_fmt": "Placed: %s",
		"previous_page": "Previous",
		"next_page": "Next",
		"back": "Back",
		"close": "Close"
	},
	"ja": {
		"mode_label_fmt": "開発者モード　%s",
		"state_enabled": "オン",
		"state_disabled": "オフ",
		"tools_entry": "開発者ツール",
		"panel_title": "開発者ツール · サンドボックス",
		"panel_subtitle": "3ページのテストツールは専用の開発セーブだけに作用します",
		"badge": "DEV · 専用セーブ",
		"separate_save_hint": "開発プロファイルは専用セーブを使い、通常の進行や実績には影響しません。",
		"switch_to_normal": "通常プロファイルへ切替",
		"switch_to_developer": "開発プロファイルへ切替",
		"switch_confirm_title": "プロファイル切替の確認",
		"switch_confirm_body": "現在のプロファイルを保存してから、もう一方の専用セーブへ切り替えます。",
		"switch_applied_fmt": "現在のプロファイル：%s",
		"achievements_guard": "プラットフォーム実績は保護され、開発プロファイルから送信されません。",
		"loading_title": "開発プロファイルを読み込み中",
		"loading_progress_fmt": "開発プロファイルを読み込み中 · %d%%",
		"loading_prepare": "サンドボックス環境を準備中",
		"loading_settings": "開発者設定を読み込み中",
		"loading_world": "培養世界を構築中",
		"loading_save": "専用セーブを読み込み中",
		"loading_finalize": "UIとシミュレーションを同期中",
		"loading_complete": "開発プロファイルを読み込みました",
		"offline_settlement_title": "オフライン進行を精算中",
		"offline_settlement_progress_fmt": "オフライン進行 · %d%%",
		"loading_failed_fmt": "読み込み失敗：%s",
		"page_label_fmt": "%d/%dページ · %s",
		"page_colony": "コロニーと資源",
		"page_world": "世界とイベント",
		"page_progress": "進行とセーブ",
		"page_colony_desc": "速度、資源、コア、アップグレードを調整します。",
		"page_world_desc": "マップを表示し、資源、生物、イベントを配置します。",
		"page_progress_desc": "章進行、長期目標、開発スナップショットをテストします。",
		"action_speed_1": "速度 1×",
		"action_speed_10": "速度 10×",
		"action_speed_60": "速度 60×",
		"speed_toast_fmt": "開発者速度：%d×",
		"action_add_resources": "有機栄養 +100 · ミネラル +10",
		"action_add_dna": "DNA +10",
		"action_heal_cores": "全コアを回復",
		"action_unlock_upgrades": "全アップグレードを解放",
		"action_spawn_core": "胞子核を配置",
		"action_spawn_barracks": "兵舎コアを配置",
		"action_cycle_unit_fmt": "兵種を切替：%s",
		"action_spawn_unit_fmt": "ユニットを生成：%s",
		"action_reveal_map": "マップ全体を表示",
		"action_restore_fog": "未探索の暗闇を復元",
		"action_place_organic": "有機栄養の密集域を配置",
		"action_place_mineral": "ミネラルの密集域を配置",
		"action_place_bacteria": "細菌コロニーを配置",
		"action_place_rival": "競争コロニーを配置",
		"action_spawn_guard": "競争菌の護衛を配置",
		"action_place_bloom": "細菌ブルームを配置",
		"action_place_toxin": "毒素区域を配置",
		"action_trigger_sporefall": "胞子雨を発生",
		"action_clear_hazards": "イベントと脅威を消去",
		"action_advance_task": "現在の章タスクを完了",
		"action_complete_chapter": "第1章を完了",
		"action_reset_chapter": "章進行をリセット",
		"action_complete_goals": "全長期目標を完了",
		"action_reset_goals": "長期目標をリセット",
		"action_save_snapshot": "開発スナップショットを保存",
		"action_load_snapshot": "開発スナップショットを読込",
		"action_clear_dev_save": "開発セーブを消去",
		"clear_confirm_title": "開発セーブを消去しますか？",
		"clear_confirm_body": "専用の開発セーブだけを削除します。通常の培養には影響しません。",
		"action_applied_fmt": "実行しました：%s",
		"action_blocked": "このツールは開発プロファイルでのみ使用できます",
		"placement_left_confirm": "左クリックで配置 · 右クリックまたはEscで取消",
		"placement_cancel": "配置をキャンセルしました",
		"placement_out_of_range": "対象地点は培養世界の範囲外です",
		"placement_blocked": "UIまたは既存の構造がこの地点を占有しています",
		"placement_organic_hint": "マップをクリックして有機栄養の密集域を配置",
		"placement_mineral_hint": "マップをクリックしてミネラルイオンの密集域を配置",
		"placement_bacteria_hint": "マップをクリックして静止増殖する細菌コロニーを配置",
		"placement_rival_hint": "マップをクリックして競争菌のコアを配置",
		"placement_bloom_hint": "マップをクリックして細菌ブルームイベントを配置",
		"placement_toxin_hint": "マップをクリックして生態毒素区域を配置",
		"placement_core_hint": "探索済み地点をクリックして味方の胞子核を配置",
		"placement_done_fmt": "配置しました：%s",
		"previous_page": "前のページ",
		"next_page": "次のページ",
		"back": "戻る",
		"close": "閉じる"
	},
	"es": {
		"mode_label_fmt": "Modo desarrollador  %s",
		"state_enabled": "Sí",
		"state_disabled": "No",
		"tools_entry": "Herramientas de desarrollo",
		"panel_title": "Herramientas de desarrollo · Perfil aislado",
		"panel_subtitle": "Tres páginas de pruebas que solo afectan a la partida de desarrollo",
		"badge": "DEV · Partida separada",
		"separate_save_hint": "El perfil de desarrollo usa una partida separada y no afecta al progreso ni a los logros normales.",
		"switch_to_normal": "Cambiar al perfil normal",
		"switch_to_developer": "Cambiar al perfil de desarrollo",
		"switch_confirm_title": "Confirmar cambio de perfil",
		"switch_confirm_body": "El perfil actual se guardará antes de cambiar a la otra partida separada.",
		"switch_applied_fmt": "Perfil actual: %s",
		"achievements_guard": "Los logros de la plataforma están protegidos y el perfil de desarrollo no los envía.",
		"loading_title": "Cargando perfil de desarrollo",
		"loading_progress_fmt": "Cargando perfil de desarrollo · %d%%",
		"loading_prepare": "Preparando entorno aislado",
		"loading_settings": "Leyendo ajustes de desarrollo",
		"loading_world": "Construyendo el mundo de cultivo",
		"loading_save": "Cargando partida separada",
		"loading_finalize": "Sincronizando interfaz y simulación",
		"loading_complete": "Perfil de desarrollo cargado",
		"offline_settlement_title": "Procesando progreso sin conexión",
		"offline_settlement_progress_fmt": "Progreso sin conexión · %d%%",
		"loading_failed_fmt": "Error de carga: %s",
		"page_label_fmt": "Página %d/%d · %s",
		"page_colony": "Colonia y recursos",
		"page_world": "Mundo y eventos",
		"page_progress": "Progreso y partidas",
		"page_colony_desc": "Ajusta la velocidad, los recursos, los núcleos y las mejoras.",
		"page_world_desc": "Revela el mapa y coloca recursos, organismos y eventos.",
		"page_progress_desc": "Prueba capítulos, objetivos a largo plazo y capturas de desarrollo.",
		"action_speed_1": "Velocidad 1×",
		"action_speed_10": "Velocidad 10×",
		"action_speed_60": "Velocidad 60×",
		"speed_toast_fmt": "Velocidad de desarrollo: %d×",
		"action_add_resources": "+100 de materia orgánica · +10 de minerales",
		"action_add_dna": "+10 de ADN",
		"action_heal_cores": "Restaurar todos los núcleos",
		"action_unlock_upgrades": "Desbloquear todas las mejoras",
		"action_spawn_core": "Colocar núcleo de espora",
		"action_spawn_barracks": "Colocar núcleo de cuartel",
		"action_cycle_unit_fmt": "Cambiar unidad: %s",
		"action_spawn_unit_fmt": "Generar unidad: %s",
		"action_reveal_map": "Revelar todo el mapa",
		"action_restore_fog": "Restaurar niebla sin explorar",
		"action_place_organic": "Colocar zona orgánica",
		"action_place_mineral": "Colocar zona mineral",
		"action_place_bacteria": "Colocar colonia bacteriana",
		"action_place_rival": "Colocar colonia rival",
		"action_spawn_guard": "Colocar guardia rival",
		"action_place_bloom": "Colocar proliferación bacteriana",
		"action_place_toxin": "Colocar zona de toxinas",
		"action_trigger_sporefall": "Activar lluvia de esporas",
		"action_clear_hazards": "Eliminar eventos y amenazas",
		"action_advance_task": "Completar tarea actual del capítulo",
		"action_complete_chapter": "Completar el Capítulo 1",
		"action_reset_chapter": "Reiniciar progreso del capítulo",
		"action_complete_goals": "Completar objetivos a largo plazo",
		"action_reset_goals": "Reiniciar objetivos a largo plazo",
		"action_save_snapshot": "Guardar captura de desarrollo",
		"action_load_snapshot": "Cargar captura de desarrollo",
		"action_clear_dev_save": "Borrar partida de desarrollo",
		"clear_confirm_title": "¿Borrar la partida de desarrollo?",
		"clear_confirm_body": "Solo se borrará la partida de desarrollo separada. El cultivo normal está a salvo.",
		"action_applied_fmt": "Aplicado: %s",
		"action_blocked": "Esta herramienta solo está disponible en el perfil de desarrollo",
		"placement_left_confirm": "Clic izquierdo para colocar · Clic derecho o Esc para cancelar",
		"placement_cancel": "Colocación cancelada",
		"placement_out_of_range": "El objetivo está fuera del mundo de cultivo",
		"placement_blocked": "La interfaz o una estructura existente ocupa esta posición",
		"placement_organic_hint": "Haz clic en el mapa para colocar una zona de nutrientes orgánicos",
		"placement_mineral_hint": "Haz clic en el mapa para colocar una zona de iones minerales",
		"placement_bacteria_hint": "Haz clic en el mapa para colocar una colonia bacteriana de expansión inmóvil",
		"placement_rival_hint": "Haz clic en el mapa para colocar un núcleo fúngico rival",
		"placement_bloom_hint": "Haz clic en el mapa para colocar un evento de proliferación bacteriana",
		"placement_toxin_hint": "Haz clic en el mapa para colocar una zona de toxinas ecológicas",
		"placement_core_hint": "Haz clic en terreno explorado para colocar un núcleo de espora aliado",
		"placement_done_fmt": "Colocado: %s",
		"previous_page": "Anterior",
		"next_page": "Siguiente",
		"back": "Volver",
		"close": "Cerrar"
	},
	"de": {
		"mode_label_fmt": "Entwicklermodus  %s",
		"state_enabled": "An",
		"state_disabled": "Aus",
		"tools_entry": "Entwicklerwerkzeuge",
		"panel_title": "Entwicklerwerkzeuge · Sandbox-Profil",
		"panel_subtitle": "Drei Werkzeugseiten wirken nur auf den separaten Entwickler-Spielstand",
		"badge": "DEV · Separater Spielstand",
		"separate_save_hint": "Das Entwicklerprofil verwendet einen separaten Spielstand und beeinflusst weder normalen Fortschritt noch Erfolge.",
		"switch_to_normal": "Zum normalen Profil wechseln",
		"switch_to_developer": "Zum Entwicklerprofil wechseln",
		"switch_confirm_title": "Profilwechsel bestätigen",
		"switch_confirm_body": "Das aktuelle Profil wird gespeichert, bevor zum anderen separaten Spielstand gewechselt wird.",
		"switch_applied_fmt": "Aktuelles Profil: %s",
		"achievements_guard": "Plattformerfolge sind geschützt und werden vom Entwicklerprofil nie übermittelt.",
		"loading_title": "Entwicklerprofil wird geladen",
		"loading_progress_fmt": "Entwicklerprofil wird geladen · %d%%",
		"loading_prepare": "Sandbox-Umgebung wird vorbereitet",
		"loading_settings": "Entwicklereinstellungen werden gelesen",
		"loading_world": "Kulturwelt wird aufgebaut",
		"loading_save": "Separater Spielstand wird geladen",
		"loading_finalize": "Oberfläche und Simulation werden synchronisiert",
		"loading_complete": "Entwicklerprofil geladen",
		"offline_settlement_title": "Offline-Fortschritt wird berechnet",
		"offline_settlement_progress_fmt": "Offline-Fortschritt · %d%%",
		"loading_failed_fmt": "Laden fehlgeschlagen: %s",
		"page_label_fmt": "Seite %d/%d · %s",
		"page_colony": "Kolonie & Ressourcen",
		"page_world": "Welt & Ereignisse",
		"page_progress": "Fortschritt & Spielstände",
		"page_colony_desc": "Tempo, Ressourcen, Kerne und Upgrades anpassen.",
		"page_world_desc": "Karte aufdecken und Ressourcen, Organismen und Ereignisse platzieren.",
		"page_progress_desc": "Kapitel, Langzeitziele und Entwickler-Snapshots testen.",
		"action_speed_1": "Tempo 1×",
		"action_speed_10": "Tempo 10×",
		"action_speed_60": "Tempo 60×",
		"speed_toast_fmt": "Entwicklertempo: %d×",
		"action_add_resources": "+100 Organik · +10 Mineralien",
		"action_add_dna": "+10 DNA",
		"action_heal_cores": "Alle Kerne wiederherstellen",
		"action_unlock_upgrades": "Alle Upgrades freischalten",
		"action_spawn_core": "Sporenkern platzieren",
		"action_spawn_barracks": "Kasernenkern platzieren",
		"action_cycle_unit_fmt": "Einheit wechseln: %s",
		"action_spawn_unit_fmt": "Einheit erzeugen: %s",
		"action_reveal_map": "Gesamte Karte aufdecken",
		"action_restore_fog": "Unerforschten Nebel wiederherstellen",
		"action_place_organic": "Organik-Hotspot platzieren",
		"action_place_mineral": "Mineral-Hotspot platzieren",
		"action_place_bacteria": "Bakterienkolonie platzieren",
		"action_place_rival": "Rivalenkolonie platzieren",
		"action_spawn_guard": "Rivalenwächter platzieren",
		"action_place_bloom": "Bakterienblüte platzieren",
		"action_place_toxin": "Toxinzone platzieren",
		"action_trigger_sporefall": "Sporenregen auslösen",
		"action_clear_hazards": "Ereignisse und Gefahren entfernen",
		"action_advance_task": "Aktuelle Kapitelaufgabe abschließen",
		"action_complete_chapter": "Kapitel 1 abschließen",
		"action_reset_chapter": "Kapitelfortschritt zurücksetzen",
		"action_complete_goals": "Alle Langzeitziele abschließen",
		"action_reset_goals": "Langzeitziele zurücksetzen",
		"action_save_snapshot": "Entwickler-Snapshot speichern",
		"action_load_snapshot": "Entwickler-Snapshot laden",
		"action_clear_dev_save": "Entwickler-Spielstand löschen",
		"clear_confirm_title": "Entwickler-Spielstand löschen?",
		"clear_confirm_body": "Nur der separate Entwickler-Spielstand wird gelöscht. Die normale Kultur bleibt sicher.",
		"action_applied_fmt": "Ausgeführt: %s",
		"action_blocked": "Dieses Werkzeug ist nur im Entwicklerprofil verfügbar",
		"placement_left_confirm": "Linksklick zum Platzieren · Rechtsklick oder Esc zum Abbrechen",
		"placement_cancel": "Platzierung abgebrochen",
		"placement_out_of_range": "Das Ziel liegt außerhalb der Kulturwelt",
		"placement_blocked": "Die Oberfläche oder eine vorhandene Struktur belegt diese Position",
		"placement_organic_hint": "Auf die Karte klicken, um einen Organik-Hotspot zu platzieren",
		"placement_mineral_hint": "Auf die Karte klicken, um einen Mineralionen-Hotspot zu platzieren",
		"placement_bacteria_hint": "Auf die Karte klicken, um eine ortsfeste wachsende Bakterienkolonie zu platzieren",
		"placement_rival_hint": "Auf die Karte klicken, um einen rivalisierenden Pilzkern zu platzieren",
		"placement_bloom_hint": "Auf die Karte klicken, um eine Bakterienblüte zu platzieren",
		"placement_toxin_hint": "Auf die Karte klicken, um eine ökologische Toxinzone zu platzieren",
		"placement_core_hint": "Auf erforschten Boden klicken, um einen eigenen Sporenkern zu platzieren",
		"placement_done_fmt": "Platziert: %s",
		"previous_page": "Zurück",
		"next_page": "Weiter",
		"back": "Zurück",
		"close": "Schließen"
	},
	"ru": {
		"mode_label_fmt": "Режим разработчика  %s",
		"state_enabled": "Вкл.",
		"state_disabled": "Выкл.",
		"tools_entry": "Инструменты разработчика",
		"panel_title": "Инструменты разработчика · Песочница",
		"panel_subtitle": "Три страницы тестов влияют только на отдельное сохранение разработчика",
		"badge": "DEV · Отдельное сохранение",
		"separate_save_hint": "Профиль разработчика использует отдельное сохранение и не влияет на обычный прогресс и достижения.",
		"switch_to_normal": "Перейти к обычному профилю",
		"switch_to_developer": "Перейти к профилю разработчика",
		"switch_confirm_title": "Подтвердите смену профиля",
		"switch_confirm_body": "Текущий профиль будет сохранён перед переходом к другому отдельному сохранению.",
		"switch_applied_fmt": "Текущий профиль: %s",
		"achievements_guard": "Достижения платформы защищены и не отправляются из профиля разработчика.",
		"loading_title": "Загрузка профиля разработчика",
		"loading_progress_fmt": "Загрузка профиля разработчика · %d%%",
		"loading_prepare": "Подготовка среды песочницы",
		"loading_settings": "Чтение настроек разработчика",
		"loading_world": "Создание мира культуры",
		"loading_save": "Загрузка отдельного сохранения",
		"loading_finalize": "Синхронизация интерфейса и симуляции",
		"loading_complete": "Профиль разработчика загружен",
		"offline_settlement_title": "Расчёт офлайн-прогресса",
		"offline_settlement_progress_fmt": "Офлайн-прогресс · %d%%",
		"loading_failed_fmt": "Ошибка загрузки: %s",
		"page_label_fmt": "Страница %d/%d · %s",
		"page_colony": "Колония и ресурсы",
		"page_world": "Мир и события",
		"page_progress": "Прогресс и сохранения",
		"page_colony_desc": "Настройка скорости, ресурсов, ядер и улучшений.",
		"page_world_desc": "Открытие карты и размещение ресурсов, организмов и событий.",
		"page_progress_desc": "Проверка глав, долгосрочных целей и снимков разработчика.",
		"action_speed_1": "Скорость 1×",
		"action_speed_10": "Скорость 10×",
		"action_speed_60": "Скорость 60×",
		"speed_toast_fmt": "Скорость разработчика: %d×",
		"action_add_resources": "+100 органики · +10 минералов",
		"action_add_dna": "+10 ДНК",
		"action_heal_cores": "Восстановить все ядра",
		"action_unlock_upgrades": "Открыть все улучшения",
		"action_spawn_core": "Разместить споровое ядро",
		"action_spawn_barracks": "Разместить ядро казармы",
		"action_cycle_unit_fmt": "Сменить тип бойца: %s",
		"action_spawn_unit_fmt": "Создать бойца: %s",
		"action_reveal_map": "Открыть всю карту",
		"action_restore_fog": "Восстановить туман исследования",
		"action_place_organic": "Разместить скопление органики",
		"action_place_mineral": "Разместить скопление минералов",
		"action_place_bacteria": "Разместить колонию бактерий",
		"action_place_rival": "Разместить колонию соперника",
		"action_spawn_guard": "Разместить стража соперника",
		"action_place_bloom": "Разместить вспышку бактерий",
		"action_place_toxin": "Разместить зону токсинов",
		"action_trigger_sporefall": "Вызвать споропад",
		"action_clear_hazards": "Удалить события и угрозы",
		"action_advance_task": "Завершить текущую задачу главы",
		"action_complete_chapter": "Завершить главу 1",
		"action_reset_chapter": "Сбросить прогресс главы",
		"action_complete_goals": "Завершить все долгосрочные цели",
		"action_reset_goals": "Сбросить долгосрочные цели",
		"action_save_snapshot": "Сохранить снимок разработчика",
		"action_load_snapshot": "Загрузить снимок разработчика",
		"action_clear_dev_save": "Удалить сохранение разработчика",
		"clear_confirm_title": "Удалить сохранение разработчика?",
		"clear_confirm_body": "Будет удалено только отдельное сохранение разработчика. Обычная культура не пострадает.",
		"action_applied_fmt": "Выполнено: %s",
		"action_blocked": "Этот инструмент доступен только в профиле разработчика",
		"placement_left_confirm": "ЛКМ — разместить · ПКМ или Esc — отменить",
		"placement_cancel": "Размещение отменено",
		"placement_out_of_range": "Цель находится за пределами мира культуры",
		"placement_blocked": "Это место занято интерфейсом или существующей структурой",
		"placement_organic_hint": "Нажмите на карту, чтобы разместить скопление органического питания",
		"placement_mineral_hint": "Нажмите на карту, чтобы разместить скопление минеральных ионов",
		"placement_bacteria_hint": "Нажмите на карту, чтобы разместить неподвижно растущую колонию бактерий",
		"placement_rival_hint": "Нажмите на карту, чтобы разместить ядро гриба-соперника",
		"placement_bloom_hint": "Нажмите на карту, чтобы разместить событие вспышки бактерий",
		"placement_toxin_hint": "Нажмите на карту, чтобы разместить экологическую зону токсинов",
		"placement_core_hint": "Нажмите на исследованную область, чтобы разместить дружественное споровое ядро",
		"placement_done_fmt": "Размещено: %s",
		"previous_page": "Назад",
		"next_page": "Далее",
		"back": "Назад",
		"close": "Закрыть"
	}
}


static func normalize_locale(locale_id: String) -> String:
	var value := locale_id.strip_edges().replace("-", "_").to_lower()
	if value.begins_with("zh_hant") or value.begins_with("zh_tw") or value.begins_with("zh_hk") or value.begins_with("zh_mo"):
		return "zh_TW"
	if value.begins_with("zh"):
		return "zh_CN"
	for candidate in ["en", "ja", "es", "de", "ru"]:
		if value == candidate or value.begins_with(candidate + "_"):
			return candidate
	return "en"


static func text(key: String, locale_id: String) -> String:
	var locale := normalize_locale(locale_id)
	var table: Dictionary = TEXTS.get(locale, TEXTS["en"])
	if table.has(key):
		return String(table[key])
	return String((TEXTS["en"] as Dictionary).get(key, key))


static func page_title(page_id: String, locale_id: String) -> String:
	return text("page_%s" % page_id, locale_id)


static func page_description(page_id: String, locale_id: String) -> String:
	return text("page_%s_desc" % page_id, locale_id)


static func page_actions(page_id: String) -> Array[String]:
	var result: Array[String] = []
	for action_id in PAGE_ACTION_IDS.get(page_id, []):
		result.append(String(action_id))
	return result


static func action_label(action_id: String, locale_id: String) -> String:
	return text("action_%s" % action_id, locale_id)
