extends RefCounted


const LOCALES: Array[String] = ["zh_CN", "zh_TW", "en", "ja", "es", "de", "ru"]

const SHORT_KEYS: Array[String] = [
	"core_action_extend_short",
	"core_action_dna_short",
	"core_action_produce_short",
	"core_action_upgrade_short",
	"core_action_status_short",
	"core_action_repair_short",
	"core_action_barracks_short",
	"core_action_switch_short",
	"core_action_core_short"
]

# Short labels are designed for the 50 px radial buttons. Keep full action names
# in tooltips instead of expanding these strings.
const SHORT_ALLOW_SHRINK: Array[String] = []

const TEXTS := {
	"zh_CN": {
		"hud_water_fmt": "水分  ∞",
		"hud_organic_fmt": "有机营养  %.3f",
		"hud_mineral_fmt": "矿物  %.3f",
		"hud_dna_fmt": "DNA  %d",
		"hud_water_compact_fmt": "水  ∞",
		"hud_organic_compact_fmt": "营养  %.3f",
		"hud_mineral_compact_fmt": "矿  %.3f",
		"hud_dna_compact_fmt": "DNA  %d",
		"hud_explore_fmt": "探索 %.1f%% · 发现 %d",
		"hud_pause": "暂停",
		"hud_upgrade": "升级 [E]",
		"hud_goals": "目标 [G]",
		"hud_goals_ready_fmt": "目标 [G]  %d",
		"core_action_extend_short": "延伸",
		"core_action_dna_short": "DNA",
		"core_action_produce_short": "生产",
		"core_action_upgrade_short": "强化",
		"core_action_status_short": "状态",
		"core_action_repair_short": "修复",
		"core_action_barracks_short": "兵营",
		"core_action_switch_short": "切换",
		"core_action_core_short": "核心",
		"core_extend_title": "延伸主菌丝",
		"core_extend_tip_title": "继续延伸主菌丝",
		"core_extend_cost": "有机营养 1.000 / 11 μm\n最终消耗按长度向上取整",
		"core_dna_title_fmt": "生产 %d DNA · 共 %.1f 秒",
		"core_dna_cost_fmt": "有机营养 %.3f\n矿物离子 %.3f\nShift：×5 · Ctrl：×10",
		"core_produce_title_fmt": "生产%s · %.1f 秒",
		"core_produce_cost_fmt": "有机 %.3f\n矿物 %.3f",
		"core_upgrade_title_fmt": "增强细菌丝范围 · Lv.%d",
		"core_upgrade_max": "已达到当前上限",
		"core_upgrade_range_fmt": "范围 %.0f → %.0f μm",
		"core_upgrade_speed_fmt": "DNA 速度 +%d%% → +%d%%",
		"core_upgrade_cost_fmt": "有机营养 %.3f",
		"core_status_title": "查看核心状态",
		"core_no_cost": "不消耗资源",
		"core_repair_title": "添加缓慢修复储备",
		"core_repair_cost_fmt": "储备 +%.3f\n恢复 %.3f / 秒\n有机营养 %.3f",
		"core_current_unit_fmt": "当前兵种：%s",
		"core_switch_hint": "点击切换已解锁兵种\n商店 → 兵营/食性专属升级",
		"core_barracks_build_title": "选择菌丝末端建造兵营",
		"core_barracks_build_cost_fmt": "有机 %.3f\n矿物 %.3f\nDNA %d",
		"core_new_core_title": "形成次级孢子核心",
		"core_new_core_cost": "有机营养 70.000\n矿物离子 6.000",
		"core_type_spore": "孢子核心",
		"core_type_barracks": "兵营核心",
		"core_name_fmt": "%s %d",
		"stat_biomass_fmt": "生物量  %.1f%%",
		"stat_repair_fmt": "修复储备  %.3f  (+%.3f/秒)",
		"stat_toxin_fmt": "毒素伤害  %.3f/秒",
		"stat_lifestyle": "营生方式  腐生",
		"stat_hypha_fmt": "菌丝长度  %d / %d μm",
		"stat_dna_queue_fmt": "DNA 队列  %d",
		"stat_unit_queue_fmt": "%s队列  %d / %d",
		"stat_water": "水分供应  稳定（无限）",
		"stat_feeder_fmt": "细菌丝范围  %.0f μm  Lv.%d",
		"stat_dna_speed_fmt": "DNA 速度  +%d%%  %.1f 秒/点",
		"stat_build_queue_fmt": "生产队列  %d / %d",
		"stat_barracks_range_fmt": "活动范围  %.0f μm",
		"stat_barracks_counts_fmt": "现役 %d · 负伤 %d · 返巢 %d · 修复 %d",
		"hover_core_fmt": "%s %d · 生物量 %.1f%%",
		"unit_forager": "游猎孢子",
		"unit_carrier": "囊载孢子",
		"unit_chelator": "螯合孢子",
		"unit_scout": "嗅营孢子",
		"unit_lytic": "裂菌孢子",
		"unit_suppressor": "抑菌囊体",
		"unit_disperser": "溶菌散播体",
		"unit_piercer": "穿壁孢子",
		"unit_coil": "缠丝猎手",
		"unit_antifungal": "抗真菌囊体",
		"state_idle": "待命",
		"state_moving": "移动",
		"state_gathering": "采集",
		"state_attack_bacteria": "猎食细菌",
		"state_attack_fungus": "攻击竞争真菌",
		"state_attack_hypha": "切断敌方菌丝",
		"state_attack_guard": "迎战竞争菌守卫",
		"state_deploying": "展开部署",
		"state_deployed": "作用区已展开",
		"state_returning": "返巢卸载",
		"state_retreating": "负伤撤退",
		"state_repairing": "兵营修复",
		"state_wounded": "重伤待援",
		"state_guarding": "警戒",
		"hover_biomass_fmt": "生物量 %.3f / %.3f (%.1f%%)",
		"hover_state_fmt": "状态  %s",
		"hover_cargo_fmt": "携带  有机 %.3f · 矿物 %.3f",
		"hover_home_fmt": "归属兵营  %s",
		"hover_home_core_fmt": "核心 %d",
		"hover_no_barracks": "暂无可用兵营",
		"hover_defense_zone_fmt": "持久防区 %.0f × %.0f μm",
		"hover_harvest_zone_fmt": "持久采区 %s · %.0f × %.0f μm",
		"hover_purge_zone_fmt": "细菌清剿区 %.0f × %.0f μm",
		"resource_organic": "有机",
		"resource_mineral": "矿物",
		"bacteria_normal": "静止细菌",
		"bacteria_bloom": "暴发型细菌",
		"bacteria_behavior_normal": "原地吸收并分裂",
		"bacteria_behavior_bloom": "生态事件中的高活性菌群",
		"bacteria_absorb_fmt": "吸收 %.3f/秒 · 真菌初始速率的 1/20",
		"bacteria_division_fmt": "分裂营养 %.3f / %.3f",
		"bacteria_genome": "复制自身基因组 · 不消耗真菌 DNA",
		"bacteria_toxin_1": "被摄食时释放少量毒素",
		"bacteria_toxin_2": "体外孢子会缓慢损失生物量",
		"suppress_source_capsule": "前沿抑菌囊体",
		"suppress_source_core": "核心抗生素",
		"bacteria_suppressed_fmt": "受%s抑制 · 代谢 %.0f%%"
	},
	"zh_TW": {
		"hud_water_fmt": "水分  ∞",
		"hud_organic_fmt": "有機營養  %.3f",
		"hud_mineral_fmt": "礦物  %.3f",
		"hud_dna_fmt": "DNA  %d",
		"hud_water_compact_fmt": "水  ∞",
		"hud_organic_compact_fmt": "營養  %.3f",
		"hud_mineral_compact_fmt": "礦  %.3f",
		"hud_dna_compact_fmt": "DNA  %d",
		"hud_explore_fmt": "探索 %.1f%% · 發現 %d",
		"hud_pause": "暫停",
		"hud_upgrade": "升級 [E]",
		"hud_goals": "目標 [G]",
		"hud_goals_ready_fmt": "目標 [G]  %d",
		"core_action_extend_short": "延伸",
		"core_action_dna_short": "DNA",
		"core_action_produce_short": "生產",
		"core_action_upgrade_short": "強化",
		"core_action_status_short": "狀態",
		"core_action_repair_short": "修復",
		"core_action_barracks_short": "兵營",
		"core_action_switch_short": "切換",
		"core_action_core_short": "核心",
		"core_extend_title": "延伸主菌絲",
		"core_extend_tip_title": "繼續延伸主菌絲",
		"core_extend_cost": "有機營養 1.000 / 11 μm\n最終消耗依長度無條件進位",
		"core_dna_title_fmt": "生產 %d DNA · 共 %.1f 秒",
		"core_dna_cost_fmt": "有機營養 %.3f\n礦物離子 %.3f\nShift：×5 · Ctrl：×10",
		"core_produce_title_fmt": "生產%s · %.1f 秒",
		"core_produce_cost_fmt": "有機 %.3f\n礦物 %.3f",
		"core_upgrade_title_fmt": "增強細菌絲範圍 · Lv.%d",
		"core_upgrade_max": "已達目前上限",
		"core_upgrade_range_fmt": "範圍 %.0f → %.0f μm",
		"core_upgrade_speed_fmt": "DNA 速度 +%d%% → +%d%%",
		"core_upgrade_cost_fmt": "有機營養 %.3f",
		"core_status_title": "查看核心狀態",
		"core_no_cost": "不消耗資源",
		"core_repair_title": "新增緩慢修復儲備",
		"core_repair_cost_fmt": "儲備 +%.3f\n恢復 %.3f / 秒\n有機營養 %.3f",
		"core_current_unit_fmt": "目前兵種：%s",
		"core_switch_hint": "點擊切換已解鎖兵種\n商店 → 兵營/食性專屬升級",
		"core_barracks_build_title": "選擇菌絲末端建造兵營",
		"core_barracks_build_cost_fmt": "有機 %.3f\n礦物 %.3f\nDNA %d",
		"core_new_core_title": "形成次級孢子核心",
		"core_new_core_cost": "有機營養 70.000\n礦物離子 6.000",
		"core_type_spore": "孢子核心",
		"core_type_barracks": "兵營核心",
		"core_name_fmt": "%s %d",
		"stat_biomass_fmt": "生物量  %.1f%%",
		"stat_repair_fmt": "修復儲備  %.3f  (+%.3f/秒)",
		"stat_toxin_fmt": "毒素傷害  %.3f/秒",
		"stat_lifestyle": "營生方式  腐生",
		"stat_hypha_fmt": "菌絲長度  %d / %d μm",
		"stat_dna_queue_fmt": "DNA 佇列  %d",
		"stat_unit_queue_fmt": "%s佇列  %d / %d",
		"stat_water": "水分供應  穩定（無限）",
		"stat_feeder_fmt": "細菌絲範圍  %.0f μm  Lv.%d",
		"stat_dna_speed_fmt": "DNA 速度  +%d%%  %.1f 秒/點",
		"stat_build_queue_fmt": "生產佇列  %d / %d",
		"stat_barracks_range_fmt": "活動範圍  %.0f μm",
		"stat_barracks_counts_fmt": "現役 %d · 負傷 %d · 返巢 %d · 修復 %d",
		"hover_core_fmt": "%s %d · 生物量 %.1f%%",
		"unit_forager": "遊獵孢子",
		"unit_carrier": "囊載孢子",
		"unit_chelator": "螯合孢子",
		"unit_scout": "嗅營孢子",
		"unit_lytic": "裂菌孢子",
		"unit_suppressor": "抑菌囊體",
		"unit_disperser": "溶菌散播體",
		"unit_piercer": "穿壁孢子",
		"unit_coil": "纏絲獵手",
		"unit_antifungal": "抗真菌囊體",
		"state_idle": "待命",
		"state_moving": "移動",
		"state_gathering": "採集",
		"state_attack_bacteria": "獵食細菌",
		"state_attack_fungus": "攻擊競爭真菌",
		"state_attack_hypha": "切斷敵方菌絲",
		"state_attack_guard": "迎戰競爭菌守衛",
		"state_deploying": "展開部署",
		"state_deployed": "作用區已展開",
		"state_returning": "返巢卸載",
		"state_retreating": "負傷撤退",
		"state_repairing": "兵營修復",
		"state_wounded": "重傷待援",
		"state_guarding": "警戒",
		"hover_biomass_fmt": "生物量 %.3f / %.3f (%.1f%%)",
		"hover_state_fmt": "狀態  %s",
		"hover_cargo_fmt": "攜帶  有機 %.3f · 礦物 %.3f",
		"hover_home_fmt": "所屬兵營  %s",
		"hover_home_core_fmt": "核心 %d",
		"hover_no_barracks": "暫無可用兵營",
		"hover_defense_zone_fmt": "持久防區 %.0f × %.0f μm",
		"hover_harvest_zone_fmt": "持久採區 %s · %.0f × %.0f μm",
		"hover_purge_zone_fmt": "細菌清剿區 %.0f × %.0f μm",
		"resource_organic": "有機",
		"resource_mineral": "礦物",
		"bacteria_normal": "靜止細菌",
		"bacteria_bloom": "爆發型細菌",
		"bacteria_behavior_normal": "原地吸收並分裂",
		"bacteria_behavior_bloom": "生態事件中的高活性菌群",
		"bacteria_absorb_fmt": "吸收 %.3f/秒 · 真菌初始速率的 1/20",
		"bacteria_division_fmt": "分裂營養 %.3f / %.3f",
		"bacteria_genome": "複製自身基因組 · 不消耗真菌 DNA",
		"bacteria_toxin_1": "被攝食時釋放少量毒素",
		"bacteria_toxin_2": "體外孢子會緩慢損失生物量",
		"suppress_source_capsule": "前沿抑菌囊體",
		"suppress_source_core": "核心抗生素",
		"bacteria_suppressed_fmt": "受%s抑制 · 代謝 %.0f%%"
	},
	"en": {
		"hud_water_fmt": "Water  ∞",
		"hud_organic_fmt": "Organic  %.3f",
		"hud_mineral_fmt": "Minerals  %.3f",
		"hud_dna_fmt": "DNA  %d",
		"hud_water_compact_fmt": "H2O ∞",
		"hud_organic_compact_fmt": "Food %.3f",
		"hud_mineral_compact_fmt": "Ion %.3f",
		"hud_dna_compact_fmt": "DNA %d",
		"hud_explore_fmt": "Explored %.1f%% · Sites %d",
		"hud_pause": "Pause",
		"hud_upgrade": "Evolve [E]",
		"hud_goals": "Goals [G]",
		"hud_goals_ready_fmt": "Goals [G]  %d",
		"core_action_extend_short": "Ext",
		"core_action_dna_short": "DNA",
		"core_action_produce_short": "Make",
		"core_action_upgrade_short": "Up",
		"core_action_status_short": "Info",
		"core_action_repair_short": "Fix",
		"core_action_barracks_short": "Barr",
		"core_action_switch_short": "Swap",
		"core_action_core_short": "Core",
		"core_extend_title": "Extend main hypha",
		"core_extend_tip_title": "Continue main hypha",
		"core_extend_cost": "Organic 1.000 / 11 μm\nFinal cost rounds up",
		"core_dna_title_fmt": "Produce %d DNA · %.1f s total",
		"core_dna_cost_fmt": "Organic %.3f\nMinerals %.3f\nShift: ×5 · Ctrl: ×10",
		"core_produce_title_fmt": "Build %s · %.1f s",
		"core_produce_cost_fmt": "Organic %.3f\nMinerals %.3f",
		"core_upgrade_title_fmt": "Expand feeder reach · Lv.%d",
		"core_upgrade_max": "Current limit reached",
		"core_upgrade_range_fmt": "Reach %.0f → %.0f μm",
		"core_upgrade_speed_fmt": "DNA speed +%d%% → +%d%%",
		"core_upgrade_cost_fmt": "Organic %.3f",
		"core_status_title": "View core status",
		"core_no_cost": "No resource cost",
		"core_repair_title": "Add repair reserve",
		"core_repair_cost_fmt": "Reserve +%.3f\nRecovery %.3f / s\nOrganic %.3f",
		"core_current_unit_fmt": "Current unit: %s",
		"core_switch_hint": "Click to switch unlocked units\nShop → Barracks / diet upgrades",
		"core_barracks_build_title": "Build barracks at a hypha tip",
		"core_barracks_build_cost_fmt": "Organic %.3f\nMinerals %.3f\nDNA %d",
		"core_new_core_title": "Form a secondary spore core",
		"core_new_core_cost": "Organic 70.000\nMinerals 6.000",
		"core_type_spore": "Spore Core",
		"core_type_barracks": "Barracks Core",
		"core_name_fmt": "%s %d",
		"stat_biomass_fmt": "Biomass  %.1f%%",
		"stat_repair_fmt": "Repair reserve  %.3f  (+%.3f/s)",
		"stat_toxin_fmt": "Toxin damage  %.3f/s",
		"stat_lifestyle": "Nutrition  Saprotrophic",
		"stat_hypha_fmt": "Hypha length  %d / %d μm",
		"stat_dna_queue_fmt": "DNA queue  %d",
		"stat_unit_queue_fmt": "%s queue  %d / %d",
		"stat_water": "Water  Stable (unlimited)",
		"stat_feeder_fmt": "Feeder reach  %.0f μm  Lv.%d",
		"stat_dna_speed_fmt": "DNA speed  +%d%%  %.1f s/point",
		"stat_build_queue_fmt": "Build queue  %d / %d",
		"stat_barracks_range_fmt": "Operating range  %.0f μm",
		"stat_barracks_counts_fmt": "Active %d · Wounded %d · Return %d · Repair %d",
		"hover_core_fmt": "%s %d · Biomass %.1f%%",
		"unit_forager": "Forager Spore",
		"unit_carrier": "Carrier Spore",
		"unit_chelator": "Chelator Spore",
		"unit_scout": "Scout Spore",
		"unit_lytic": "Lytic Spore",
		"unit_suppressor": "Suppressor Capsule",
		"unit_disperser": "Lytic Disperser",
		"unit_piercer": "Piercer Spore",
		"unit_coil": "Hypha Hunter",
		"unit_antifungal": "Antifungal Capsule",
		"state_idle": "Idle",
		"state_moving": "Moving",
		"state_gathering": "Gathering",
		"state_attack_bacteria": "Hunting bacteria",
		"state_attack_fungus": "Attacking rival fungus",
		"state_attack_hypha": "Severing rival hypha",
		"state_attack_guard": "Fighting spore guard",
		"state_deploying": "Deploying",
		"state_deployed": "Field active",
		"state_returning": "Returning with cargo",
		"state_retreating": "Wounded retreat",
		"state_repairing": "Repairing at barracks",
		"state_wounded": "Wounded, awaiting barracks",
		"state_guarding": "Guarding",
		"hover_biomass_fmt": "Biomass %.3f / %.3f (%.1f%%)",
		"hover_state_fmt": "Status  %s",
		"hover_cargo_fmt": "Cargo  Org. %.3f · Min. %.3f",
		"hover_home_fmt": "Home barracks  %s",
		"hover_home_core_fmt": "Core %d",
		"hover_no_barracks": "No barracks available",
		"hover_defense_zone_fmt": "Defense zone %.0f × %.0f μm",
		"hover_harvest_zone_fmt": "Harvest zone %s · %.0f × %.0f μm",
		"hover_purge_zone_fmt": "Bacteria purge %.0f × %.0f μm",
		"resource_organic": "Organic",
		"resource_mineral": "Minerals",
		"bacteria_normal": "Stationary Bacteria",
		"bacteria_bloom": "Bloom Bacteria",
		"bacteria_behavior_normal": "Absorbs and divides in place",
		"bacteria_behavior_bloom": "High-activity event colony",
		"bacteria_absorb_fmt": "Absorption %.3f/s · 1/20 base fungal rate",
		"bacteria_division_fmt": "Division nutrients %.3f / %.3f",
		"bacteria_genome": "Copies own genome · No fungal DNA used",
		"bacteria_toxin_1": "Releases a little toxin when eaten",
		"bacteria_toxin_2": "Expedition spores slowly lose biomass",
		"suppress_source_capsule": "Suppressor capsule",
		"suppress_source_core": "Core antibiotic",
		"bacteria_suppressed_fmt": "Suppressed by %s · Metabolism %.0f%%"
	},
	"ja": {
		"hud_water_fmt": "水分  ∞",
		"hud_organic_fmt": "有機栄養  %.3f",
		"hud_mineral_fmt": "ミネラル  %.3f",
		"hud_dna_fmt": "DNA  %d",
		"hud_water_compact_fmt": "水  ∞",
		"hud_organic_compact_fmt": "栄養  %.3f",
		"hud_mineral_compact_fmt": "鉱  %.3f",
		"hud_dna_compact_fmt": "DNA  %d",
		"hud_explore_fmt": "探索 %.1f%% · 発見 %d",
		"hud_pause": "一時停止",
		"hud_upgrade": "進化 [E]",
		"hud_goals": "目標 [G]",
		"hud_goals_ready_fmt": "目標 [G]  %d",
		"core_action_extend_short": "延長",
		"core_action_dna_short": "DNA",
		"core_action_produce_short": "生産",
		"core_action_upgrade_short": "強化",
		"core_action_status_short": "状態",
		"core_action_repair_short": "修復",
		"core_action_barracks_short": "兵舎",
		"core_action_switch_short": "切替",
		"core_action_core_short": "胞子核",
		"core_extend_title": "主菌糸を延長",
		"core_extend_tip_title": "主菌糸をさらに延長",
		"core_extend_cost": "有機栄養 1.000 / 11 μm\n最終コストは切り上げ",
		"core_dna_title_fmt": "DNAを%d生産 · 合計%.1f秒",
		"core_dna_cost_fmt": "有機栄養 %.3f\nミネラル %.3f\nShift：×5 · Ctrl：×10",
		"core_produce_title_fmt": "%sを生産 · %.1f秒",
		"core_produce_cost_fmt": "有機栄養 %.3f\nミネラル %.3f",
		"core_upgrade_title_fmt": "吸収菌糸の範囲を拡張 · Lv.%d",
		"core_upgrade_max": "現在の上限",
		"core_upgrade_range_fmt": "範囲 %.0f → %.0f μm",
		"core_upgrade_speed_fmt": "DNA速度 +%d%% → +%d%%",
		"core_upgrade_cost_fmt": "有機栄養 %.3f",
		"core_status_title": "胞子核の状態を見る",
		"core_no_cost": "資源消費なし",
		"core_repair_title": "修復備蓄を追加",
		"core_repair_cost_fmt": "備蓄 +%.3f\n回復 %.3f /秒\n有機栄養 %.3f",
		"core_current_unit_fmt": "現在の兵種：%s",
		"core_switch_hint": "クリックで解放済み兵種を切替\nショップ → 兵舎/食性専用進化",
		"core_barracks_build_title": "菌糸先端に兵舎を建設",
		"core_barracks_build_cost_fmt": "有機栄養 %.3f\nミネラル %.3f\nDNA %d",
		"core_new_core_title": "二次胞子核を形成",
		"core_new_core_cost": "有機栄養 70.000\nミネラル 6.000",
		"core_type_spore": "胞子核",
		"core_type_barracks": "兵舎核",
		"core_name_fmt": "%s %d",
		"stat_biomass_fmt": "バイオマス  %.1f%%",
		"stat_repair_fmt": "修復備蓄  %.3f  (+%.3f/秒)",
		"stat_toxin_fmt": "毒素ダメージ  %.3f/秒",
		"stat_lifestyle": "栄養様式  腐生",
		"stat_hypha_fmt": "菌糸長  %d / %d μm",
		"stat_dna_queue_fmt": "DNAキュー  %d",
		"stat_unit_queue_fmt": "%sキュー  %d / %d",
		"stat_water": "水分供給  安定（無限）",
		"stat_feeder_fmt": "吸収菌糸範囲  %.0f μm  Lv.%d",
		"stat_dna_speed_fmt": "DNA速度  +%d%%  %.1f秒/点",
		"stat_build_queue_fmt": "生産キュー  %d / %d",
		"stat_barracks_range_fmt": "行動範囲  %.0f μm",
		"stat_barracks_counts_fmt": "稼働 %d · 負傷 %d · 帰還 %d · 修復 %d",
		"hover_core_fmt": "%s %d · バイオマス %.1f%%",
		"unit_forager": "採餌胞子",
		"unit_carrier": "運搬胞子",
		"unit_chelator": "キレート胞子",
		"unit_scout": "偵察胞子",
		"unit_lytic": "溶菌胞子",
		"unit_suppressor": "抑菌嚢体",
		"unit_disperser": "溶菌散布体",
		"unit_piercer": "穿壁胞子",
		"unit_coil": "巻糸ハンター",
		"unit_antifungal": "抗真菌嚢体",
		"state_idle": "待機",
		"state_moving": "移動",
		"state_gathering": "採集",
		"state_attack_bacteria": "細菌を捕食",
		"state_attack_fungus": "競合菌を攻撃",
		"state_attack_hypha": "敵菌糸を切断",
		"state_attack_guard": "胞子衛兵と交戦",
		"state_deploying": "展開中",
		"state_deployed": "作用域を展開済み",
		"state_returning": "帰巣・荷下ろし",
		"state_retreating": "負傷撤退",
		"state_repairing": "兵舎で修復中",
		"state_wounded": "重傷・兵舎待ち",
		"state_guarding": "警戒",
		"hover_biomass_fmt": "バイオマス %.3f / %.3f (%.1f%%)",
		"hover_state_fmt": "状態  %s",
		"hover_cargo_fmt": "積載  有機 %.3f · ミネラル %.3f",
		"hover_home_fmt": "所属兵舎  %s",
		"hover_home_core_fmt": "胞子核 %d",
		"hover_no_barracks": "利用可能な兵舎なし",
		"hover_defense_zone_fmt": "持続防衛区 %.0f × %.0f μm",
		"hover_harvest_zone_fmt": "持続採集区 %s · %.0f × %.0f μm",
		"hover_purge_zone_fmt": "細菌掃討区 %.0f × %.0f μm",
		"resource_organic": "有機",
		"resource_mineral": "ミネラル",
		"bacteria_normal": "静止細菌",
		"bacteria_bloom": "高活性細菌",
		"bacteria_behavior_normal": "その場で吸収・分裂",
		"bacteria_behavior_bloom": "生態イベントの高活性菌群",
		"bacteria_absorb_fmt": "吸収 %.3f/秒 · 初期真菌の1/20",
		"bacteria_division_fmt": "分裂栄養 %.3f / %.3f",
		"bacteria_genome": "自身のゲノムを複製 · 真菌DNA不要",
		"bacteria_toxin_1": "捕食されると少量の毒素を放出",
		"bacteria_toxin_2": "体外胞子のバイオマスが徐々に低下",
		"suppress_source_capsule": "前線抑菌嚢体",
		"suppress_source_core": "胞子核の抗生物質",
		"bacteria_suppressed_fmt": "%sで抑制 · 代謝 %.0f%%"
	},
	"es": {
		"hud_water_fmt": "Agua  ∞",
		"hud_organic_fmt": "Orgánico  %.3f",
		"hud_mineral_fmt": "Minerales  %.3f",
		"hud_dna_fmt": "DNA  %d",
		"hud_water_compact_fmt": "H2O ∞",
		"hud_organic_compact_fmt": "Org. %.3f",
		"hud_mineral_compact_fmt": "Min. %.3f",
		"hud_dna_compact_fmt": "DNA %d",
		"hud_explore_fmt": "Explorado %.1f%% · Hallazgos %d",
		"hud_pause": "Pausa",
		"hud_upgrade": "Evolución [E]",
		"hud_goals": "Metas [G]",
		"hud_goals_ready_fmt": "Metas [G]  %d",
		"core_action_extend_short": "Ext",
		"core_action_dna_short": "DNA",
		"core_action_produce_short": "Prod",
		"core_action_upgrade_short": "Mej.",
		"core_action_status_short": "Info",
		"core_action_repair_short": "Rep.",
		"core_action_barracks_short": "Cuar",
		"core_action_switch_short": "Camb",
		"core_action_core_short": "Núcl",
		"core_extend_title": "Extender hifa principal",
		"core_extend_tip_title": "Continuar hifa principal",
		"core_extend_cost": "Orgánico 1.000 / 11 μm\nCoste final redondeado arriba",
		"core_dna_title_fmt": "Producir %d DNA · %.1f s total",
		"core_dna_cost_fmt": "Orgánico %.3f\nMinerales %.3f\nShift: ×5 · Ctrl: ×10",
		"core_produce_title_fmt": "Crear %s · %.1f s",
		"core_produce_cost_fmt": "Orgánico %.3f\nMinerales %.3f",
		"core_upgrade_title_fmt": "Ampliar alcance · Nv.%d",
		"core_upgrade_max": "Límite actual alcanzado",
		"core_upgrade_range_fmt": "Alcance %.0f → %.0f μm",
		"core_upgrade_speed_fmt": "Vel. DNA +%d%% → +%d%%",
		"core_upgrade_cost_fmt": "Orgánico %.3f",
		"core_status_title": "Ver estado del núcleo",
		"core_no_cost": "Sin coste",
		"core_repair_title": "Añadir reserva de reparación",
		"core_repair_cost_fmt": "Reserva +%.3f\nRecuperación %.3f/s\nOrgánico %.3f",
		"core_current_unit_fmt": "Unidad actual: %s",
		"core_switch_hint": "Clic para cambiar unidades desbloqueadas\nTienda → Cuartel / mejoras de dieta",
		"core_barracks_build_title": "Construir cuartel en punta de hifa",
		"core_barracks_build_cost_fmt": "Orgánico %.3f\nMinerales %.3f\nDNA %d",
		"core_new_core_title": "Formar núcleo de espora secundario",
		"core_new_core_cost": "Orgánico 70.000\nMinerales 6.000",
		"core_type_spore": "Núcleo de espora",
		"core_type_barracks": "Núcleo cuartel",
		"core_name_fmt": "%s %d",
		"stat_biomass_fmt": "Biomasa  %.1f%%",
		"stat_repair_fmt": "Reserva  %.3f  (+%.3f/s)",
		"stat_toxin_fmt": "Daño tóxico  %.3f/s",
		"stat_lifestyle": "Nutrición  Saprótrofa",
		"stat_hypha_fmt": "Longitud de hifa  %d / %d μm",
		"stat_dna_queue_fmt": "Cola de DNA  %d",
		"stat_unit_queue_fmt": "Cola: %s  %d / %d",
		"stat_water": "Agua  Estable (ilimitada)",
		"stat_feeder_fmt": "Alcance absorbente  %.0f μm  Nv.%d",
		"stat_dna_speed_fmt": "Vel. DNA  +%d%%  %.1f s/punto",
		"stat_build_queue_fmt": "Cola de producción  %d / %d",
		"stat_barracks_range_fmt": "Radio operativo  %.0f μm",
		"stat_barracks_counts_fmt": "Activos %d · Heridos %d · Vuelven %d · Reparan %d",
		"hover_core_fmt": "%s %d · Biomasa %.1f%%",
		"unit_forager": "Espora recolectora",
		"unit_carrier": "Espora portadora",
		"unit_chelator": "Espora quelante",
		"unit_scout": "Espora exploradora",
		"unit_lytic": "Espora lítica",
		"unit_suppressor": "Cápsula supresora",
		"unit_disperser": "Dispersor lítico",
		"unit_piercer": "Espora perforadora",
		"unit_coil": "Cazador de hifas",
		"unit_antifungal": "Cápsula antifúngica",
		"state_idle": "En espera",
		"state_moving": "En ruta",
		"state_gathering": "Recolectando",
		"state_attack_bacteria": "Cazando bacterias",
		"state_attack_fungus": "Atacando hongo rival",
		"state_attack_hypha": "Cortando hifa rival",
		"state_attack_guard": "Luchando con guardia",
		"state_deploying": "Desplegando",
		"state_deployed": "Campo activo",
		"state_returning": "Volviendo con carga",
		"state_retreating": "Retirada por heridas",
		"state_repairing": "Reparando en cuartel",
		"state_wounded": "Herido, espera cuartel",
		"state_guarding": "En guardia",
		"hover_biomass_fmt": "Biomasa %.3f / %.3f (%.1f%%)",
		"hover_state_fmt": "Estado  %s",
		"hover_cargo_fmt": "Carga  Org. %.3f · Min. %.3f",
		"hover_home_fmt": "Cuartel base  %s",
		"hover_home_core_fmt": "Núcleo %d",
		"hover_no_barracks": "Sin cuartel disponible",
		"hover_defense_zone_fmt": "Zona defensiva %.0f × %.0f μm",
		"hover_harvest_zone_fmt": "Zona de cosecha %s · %.0f × %.0f μm",
		"hover_purge_zone_fmt": "Purga bacteriana %.0f × %.0f μm",
		"resource_organic": "Orgánico",
		"resource_mineral": "Minerales",
		"bacteria_normal": "Bacteria inmóvil",
		"bacteria_bloom": "Bacteria de brote",
		"bacteria_behavior_normal": "Absorbe y se divide aquí",
		"bacteria_behavior_bloom": "Colonia activa del evento",
		"bacteria_absorb_fmt": "Absorción %.3f/s · 1/20 del hongo inicial",
		"bacteria_division_fmt": "Nutriente de división %.3f / %.3f",
		"bacteria_genome": "Copia su genoma · No usa DNA fúngico",
		"bacteria_toxin_1": "Libera algo de toxina al ser comida",
		"bacteria_toxin_2": "Las esporas pierden biomasa lentamente",
		"suppress_source_capsule": "Cápsula supresora",
		"suppress_source_core": "Antibiótico del núcleo",
		"bacteria_suppressed_fmt": "Suprimida por %s · Metabolismo %.0f%%"
	},
	"de": {
		"hud_water_fmt": "Wasser  ∞",
		"hud_organic_fmt": "Organik  %.3f",
		"hud_mineral_fmt": "Mineralien  %.3f",
		"hud_dna_fmt": "DNA  %d",
		"hud_water_compact_fmt": "H2O ∞",
		"hud_organic_compact_fmt": "Org. %.3f",
		"hud_mineral_compact_fmt": "Min. %.3f",
		"hud_dna_compact_fmt": "DNA %d",
		"hud_explore_fmt": "Erkundet %.1f%% · Funde %d",
		"hud_pause": "Pause",
		"hud_upgrade": "Evolution [E]",
		"hud_goals": "Ziele [G]",
		"hud_goals_ready_fmt": "Ziele [G]  %d",
		"core_action_extend_short": "Wach",
		"core_action_dna_short": "DNA",
		"core_action_produce_short": "Bau",
		"core_action_upgrade_short": "Stär",
		"core_action_status_short": "Info",
		"core_action_repair_short": "Rep.",
		"core_action_barracks_short": "Kas.",
		"core_action_switch_short": "Wahl",
		"core_action_core_short": "Kern",
		"core_extend_title": "Haupthyphe verlängern",
		"core_extend_tip_title": "Haupthyphe fortsetzen",
		"core_extend_cost": "Organik 1.000 / 11 μm\nEndkosten werden aufgerundet",
		"core_dna_title_fmt": "%d DNA erzeugen · %.1f s gesamt",
		"core_dna_cost_fmt": "Organik %.3f\nMineralien %.3f\nShift: ×5 · Ctrl: ×10",
		"core_produce_title_fmt": "%s bauen · %.1f s",
		"core_produce_cost_fmt": "Organik %.3f\nMineralien %.3f",
		"core_upgrade_title_fmt": "Nährreichweite · St.%d",
		"core_upgrade_max": "Aktuelles Limit erreicht",
		"core_upgrade_range_fmt": "Reichweite %.0f → %.0f μm",
		"core_upgrade_speed_fmt": "DNA-Tempo +%d%% → +%d%%",
		"core_upgrade_cost_fmt": "Organik %.3f",
		"core_status_title": "Kernstatus ansehen",
		"core_no_cost": "Keine Kosten",
		"core_repair_title": "Reparaturvorrat hinzufügen",
		"core_repair_cost_fmt": "Vorrat +%.3f\nRegeneration %.3f/s\nOrganik %.3f",
		"core_current_unit_fmt": "Aktuelle Einheit: %s",
		"core_switch_hint": "Klicken: Freigeschaltete Einheit wechseln\nShop → Kaserne / Nahrungsupgrades",
		"core_barracks_build_title": "Kaserne an Hyphenspitze bauen",
		"core_barracks_build_cost_fmt": "Organik %.3f\nMineralien %.3f\nDNA %d",
		"core_new_core_title": "Sekundären Sporenkern bilden",
		"core_new_core_cost": "Organik 70.000\nMineralien 6.000",
		"core_type_spore": "Sporenkern",
		"core_type_barracks": "Kasernenkern",
		"core_name_fmt": "%s %d",
		"stat_biomass_fmt": "Biomasse  %.1f%%",
		"stat_repair_fmt": "Reparaturvorrat  %.3f  (+%.3f/s)",
		"stat_toxin_fmt": "Toxinschaden  %.3f/s",
		"stat_lifestyle": "Ernährung  Saprotroph",
		"stat_hypha_fmt": "Hyphenlänge  %d / %d μm",
		"stat_dna_queue_fmt": "DNA-Warteschlange  %d",
		"stat_unit_queue_fmt": "%s-Warteschlange  %d / %d",
		"stat_water": "Wasser  Stabil (unbegrenzt)",
		"stat_feeder_fmt": "Nährreichweite  %.0f μm  St.%d",
		"stat_dna_speed_fmt": "DNA-Tempo  +%d%%  %.1f s/Punkt",
		"stat_build_queue_fmt": "Bauwarteschlange  %d / %d",
		"stat_barracks_range_fmt": "Aktionsradius  %.0f μm",
		"stat_barracks_counts_fmt": "Aktiv %d · Verwundet %d · Rückkehr %d · Reparatur %d",
		"hover_core_fmt": "%s %d · Biomasse %.1f%%",
		"unit_forager": "Jagdspore",
		"unit_carrier": "Transportspore",
		"unit_chelator": "Chelatspore",
		"unit_scout": "Spähspore",
		"unit_lytic": "Lysespore",
		"unit_suppressor": "Hemmkapsel",
		"unit_disperser": "Lyseverteiler",
		"unit_piercer": "Bohrspore",
		"unit_coil": "Fadenjäger",
		"unit_antifungal": "Antipilzkapsel",
		"state_idle": "Bereit",
		"state_moving": "Unterwegs",
		"state_gathering": "Sammeln",
		"state_attack_bacteria": "Bakterienjagd",
		"state_attack_fungus": "Pilzangriff",
		"state_attack_hypha": "Feindhyphe trennen",
		"state_attack_guard": "Sporenwache bekämpfen",
		"state_deploying": "Entfalten",
		"state_deployed": "Feld aktiv",
		"state_returning": "Rückkehr mit Fracht",
		"state_retreating": "Verwundet: Rückzug",
		"state_repairing": "Reparatur in Kaserne",
		"state_wounded": "Verwundet, wartet",
		"state_guarding": "Wache",
		"hover_biomass_fmt": "Biomasse %.3f / %.3f (%.1f%%)",
		"hover_state_fmt": "Status  %s",
		"hover_cargo_fmt": "Fracht  Org. %.3f · Min. %.3f",
		"hover_home_fmt": "Heimatkaserne  %s",
		"hover_home_core_fmt": "Kern %d",
		"hover_no_barracks": "Keine Kaserne verfügbar",
		"hover_defense_zone_fmt": "Schutzzone %.0f × %.0f μm",
		"hover_harvest_zone_fmt": "Sammelzone %s · %.0f × %.0f μm",
		"hover_purge_zone_fmt": "Bakterienjagd %.0f × %.0f μm",
		"resource_organic": "Organik",
		"resource_mineral": "Mineralien",
		"bacteria_normal": "Ortsfeste Bakterie",
		"bacteria_bloom": "Ausbruchsbakterie",
		"bacteria_behavior_normal": "Nimmt auf und teilt sich vor Ort",
		"bacteria_behavior_bloom": "Hochaktive Ereigniskolonie",
		"bacteria_absorb_fmt": "Aufnahme %.3f/s · 1/20 der Pilzstartrate",
		"bacteria_division_fmt": "Teilungsnahrung %.3f / %.3f",
		"bacteria_genome": "Kopiert eigenes Genom · Keine Pilz-DNA",
		"bacteria_toxin_1": "Gibt beim Fressen etwas Toxin ab",
		"bacteria_toxin_2": "Außensporen verlieren langsam Biomasse",
		"suppress_source_capsule": "Hemmkapsel",
		"suppress_source_core": "Kernantibiotikum",
		"bacteria_suppressed_fmt": "Gehemmt durch %s · Stoffwechsel %.0f%%"
	},
	"ru": {
		"hud_water_fmt": "Вода  ∞",
		"hud_organic_fmt": "Органика  %.3f",
		"hud_mineral_fmt": "Минералы  %.3f",
		"hud_dna_fmt": "ДНК  %d",
		"hud_water_compact_fmt": "Вода ∞",
		"hud_organic_compact_fmt": "Орг. %.3f",
		"hud_mineral_compact_fmt": "Мин. %.3f",
		"hud_dna_compact_fmt": "ДНК %d",
		"hud_explore_fmt": "Разведано %.1f%% · Находки %d",
		"hud_pause": "Пауза",
		"hud_upgrade": "Эволюция [E]",
		"hud_goals": "Цели [G]",
		"hud_goals_ready_fmt": "Цели [G]  %d",
		"core_action_extend_short": "Рост",
		"core_action_dna_short": "ДНК",
		"core_action_produce_short": "Созд",
		"core_action_upgrade_short": "Усил",
		"core_action_status_short": "Инфо",
		"core_action_repair_short": "Рем.",
		"core_action_barracks_short": "Каз.",
		"core_action_switch_short": "Смен",
		"core_action_core_short": "Ядро",
		"core_extend_title": "Удлинить главную гифу",
		"core_extend_tip_title": "Продолжить главную гифу",
		"core_extend_cost": "Органика 1.000 / 11 μm\nИтог округляется вверх",
		"core_dna_title_fmt": "Создать %d ДНК · всего %.1f с",
		"core_dna_cost_fmt": "Органика %.3f\nМинералы %.3f\nShift: ×5 · Ctrl: ×10",
		"core_produce_title_fmt": "Создать %s · %.1f с",
		"core_produce_cost_fmt": "Органика %.3f\nМинералы %.3f",
		"core_upgrade_title_fmt": "Радиус гиф · ур.%d",
		"core_upgrade_max": "Достигнут текущий предел",
		"core_upgrade_range_fmt": "Радиус %.0f → %.0f μm",
		"core_upgrade_speed_fmt": "Скорость ДНК +%d%% → +%d%%",
		"core_upgrade_cost_fmt": "Органика %.3f",
		"core_status_title": "Статус ядра",
		"core_no_cost": "Без затрат",
		"core_repair_title": "Добавить запас ремонта",
		"core_repair_cost_fmt": "Запас +%.3f\nРегенерация %.3f/с\nОрганика %.3f",
		"core_current_unit_fmt": "Текущий боец: %s",
		"core_switch_hint": "Щёлкните для смены открытых бойцов\nМагазин → Казарма / питание",
		"core_barracks_build_title": "Построить казарму на конце гифы",
		"core_barracks_build_cost_fmt": "Органика %.3f\nМинералы %.3f\nДНК %d",
		"core_new_core_title": "Создать вторичное споровое ядро",
		"core_new_core_cost": "Органика 70.000\nМинералы 6.000",
		"core_type_spore": "Споровое ядро",
		"core_type_barracks": "Ядро-казарма",
		"core_name_fmt": "%s %d",
		"stat_biomass_fmt": "Биомасса  %.1f%%",
		"stat_repair_fmt": "Запас ремонта  %.3f  (+%.3f/с)",
		"stat_toxin_fmt": "Урон токсина  %.3f/с",
		"stat_lifestyle": "Питание  Сапротрофия",
		"stat_hypha_fmt": "Длина гиф  %d / %d μm",
		"stat_dna_queue_fmt": "Очередь ДНК  %d",
		"stat_unit_queue_fmt": "Очередь: %s  %d / %d",
		"stat_water": "Вода  Стабильно (∞)",
		"stat_feeder_fmt": "Радиус гиф  %.0f μm  ур.%d",
		"stat_dna_speed_fmt": "Скорость ДНК  +%d%%  %.1f с/ед.",
		"stat_build_queue_fmt": "Очередь создания  %d / %d",
		"stat_barracks_range_fmt": "Радиус действий  %.0f μm",
		"stat_barracks_counts_fmt": "Активно %d · Ранено %d · Возврат %d · Ремонт %d",
		"hover_core_fmt": "%s %d · Биомасса %.1f%%",
		"unit_forager": "Спора-фуражир",
		"unit_carrier": "Спора-носитель",
		"unit_chelator": "Спора-хелатор",
		"unit_scout": "Спора-разведчик",
		"unit_lytic": "Литическая спора",
		"unit_suppressor": "Подавляющая капсула",
		"unit_disperser": "Литический рассеиватель",
		"unit_piercer": "Буровая спора",
		"unit_coil": "Нитяной охотник",
		"unit_antifungal": "Противогрибковая капсула",
		"state_idle": "Ожидание",
		"state_moving": "В пути",
		"state_gathering": "Сбор",
		"state_attack_bacteria": "Охота на бактерий",
		"state_attack_fungus": "Атака гриба-соперника",
		"state_attack_hypha": "Разрыв вражеской гифы",
		"state_attack_guard": "Бой со спорой-стражем",
		"state_deploying": "Развёртывание",
		"state_deployed": "Поле активно",
		"state_returning": "Возврат с грузом",
		"state_retreating": "Ранен: отход",
		"state_repairing": "Ремонт в казарме",
		"state_wounded": "Ранен, ждёт казарму",
		"state_guarding": "Охрана",
		"hover_biomass_fmt": "Биомасса %.3f / %.3f (%.1f%%)",
		"hover_state_fmt": "Статус  %s",
		"hover_cargo_fmt": "Груз  Орг. %.3f · Мин. %.3f",
		"hover_home_fmt": "Своя казарма  %s",
		"hover_home_core_fmt": "Ядро %d",
		"hover_no_barracks": "Нет доступной казармы",
		"hover_defense_zone_fmt": "Зона защиты %.0f × %.0f μm",
		"hover_harvest_zone_fmt": "Зона сбора %s · %.0f × %.0f μm",
		"hover_purge_zone_fmt": "Очистка бактерий %.0f × %.0f μm",
		"resource_organic": "Органика",
		"resource_mineral": "Минералы",
		"bacteria_normal": "Неподвижная бактерия",
		"bacteria_bloom": "Очаговая бактерия",
		"bacteria_behavior_normal": "Поглощает и делится на месте",
		"bacteria_behavior_bloom": "Активная колония события",
		"bacteria_absorb_fmt": "Поглощение %.3f/с · 1/20 старта гриба",
		"bacteria_division_fmt": "Питание для деления %.3f / %.3f",
		"bacteria_genome": "Копирует свой геном · Без ДНК гриба",
		"bacteria_toxin_1": "При поедании выделяет немного токсина",
		"bacteria_toxin_2": "Внешние споры медленно теряют биомассу",
		"suppress_source_capsule": "Подавляющая капсула",
		"suppress_source_core": "Антибиотик ядра",
		"bacteria_suppressed_fmt": "Подавление: %s · Метаболизм %.0f%%"
	}
}


static func normalize_locale(locale: String) -> String:
	var normalized := locale.strip_edges().replace("-", "_")
	if LOCALES.has(normalized):
		return normalized
	var lowered := normalized.to_lower()
	if lowered.begins_with("zh_tw") or lowered.begins_with("zh_hk") or lowered.begins_with("zh_mo") or lowered.begins_with("zh_hant"):
		return "zh_TW"
	if lowered.begins_with("zh"):
		return "zh_CN"
	for locale_id in ["en", "ja", "es", "de", "ru"]:
		if lowered.begins_with(locale_id):
			return locale_id
	return "en"


static func text(key: String, locale: String) -> String:
	var normalized := normalize_locale(locale)
	var localized: Dictionary = TEXTS.get(normalized, {})
	if localized.has(key):
		return String(localized[key])
	var fallback: Dictionary = TEXTS["en"]
	return String(fallback.get(key, key))
