extends RefCounted


const LOCALES: Array[String] = ["zh_CN", "zh_TW", "en", "ja", "es", "de", "ru"]
const KEYS: Array[String] = [
	"title", "cap_note_fmt", "absence_fmt", "collection", "feeder_organic_fmt",
	"feeder_mineral_fmt", "expedition_organic_fmt", "expedition_mineral_fmt",
	"balance_fmt", "growth", "dna_fmt", "units_fmt", "exploration_fmt",
	"hotspots_fmt", "bacteria_fmt", "biomass_fmt", "rules_fmt", "capped_fmt", "close"
]

const TEXTS := {
	"zh_CN": {
		"title": "休眠培养报告",
		"cap_note_fmt": " · 已达 %d 小时上限",
		"absence_fmt": "离开 %s · 结算 %s%s",
		"collection": "真实采集",
		"feeder_organic_fmt": "吸收丝有机 +%.3f",
		"feeder_mineral_fmt": "吸收丝矿物 +%.3f",
		"expedition_organic_fmt": "远征有机 +%.3f",
		"expedition_mineral_fmt": "远征矿物 +%.3f",
		"balance_fmt": "余额：有机 %+.3f · 矿物 %+.3f",
		"growth": "成长与探索",
		"dna_fmt": "完成 DNA +%d",
		"units_fmt": "孢子：建造 +%d · 修复 +%d · 损失 %d",
		"exploration_fmt": "探索格 +%d（%+.2f%%）",
		"hotspots_fmt": "发现异常区 +%d",
		"bacteria_fmt": "细菌：出生 %d · 消灭 %d",
		"biomass_fmt": "核心生物量 %+.3f · 存活核心 %d → %d",
		"rules_fmt": "真实资源结算：收益最多 %d 小时；细菌及风险最多 %d 小时。",
		"capped_fmt": "超过 %d 小时的离开时间不再结算。",
		"close": "返回培养皿"
	},
	"zh_TW": {
		"title": "休眠培養報告",
		"cap_note_fmt": " · 已達 %d 小時上限",
		"absence_fmt": "離開 %s · 結算 %s%s",
		"collection": "實際採集",
		"feeder_organic_fmt": "吸收絲有機 +%.3f",
		"feeder_mineral_fmt": "吸收絲礦物 +%.3f",
		"expedition_organic_fmt": "遠征有機 +%.3f",
		"expedition_mineral_fmt": "遠征礦物 +%.3f",
		"balance_fmt": "餘額：有機 %+.3f · 礦物 %+.3f",
		"growth": "成長與探索",
		"dna_fmt": "完成 DNA +%d",
		"units_fmt": "胞子：建造 +%d · 修復 +%d · 損失 %d",
		"exploration_fmt": "探索格 +%d（%+.2f%%）",
		"hotspots_fmt": "發現異常區 +%d",
		"bacteria_fmt": "細菌：出生 %d · 消滅 %d",
		"biomass_fmt": "核心生物量 %+.3f · 存活核心 %d → %d",
		"rules_fmt": "實際資源結算：收益最多 %d 小時；細菌及風險最多 %d 小時。",
		"capped_fmt": "超過 %d 小時的離開時間不再結算。",
		"close": "返回培養皿"
	},
	"en": {
		"title": "Offline culture report",
		"cap_note_fmt": " · %dh limit reached",
		"absence_fmt": "Away %s · Settled %s%s",
		"collection": "Actual collection",
		"feeder_organic_fmt": "Feeders: organic +%.3f",
		"feeder_mineral_fmt": "Feeders: minerals +%.3f",
		"expedition_organic_fmt": "Expeditions: organic +%.3f",
		"expedition_mineral_fmt": "Expeditions: minerals +%.3f",
		"balance_fmt": "Balance: organic %+.3f · minerals %+.3f",
		"growth": "Growth and exploration",
		"dna_fmt": "DNA completed +%d",
		"units_fmt": "Spores: built +%d · repaired +%d · lost %d",
		"exploration_fmt": "Cells explored +%d (%+.2f%%)",
		"hotspots_fmt": "Hotspots found +%d",
		"bacteria_fmt": "Bacteria: born %d · killed %d",
		"biomass_fmt": "Core biomass %+.3f · Living cores %d → %d",
		"rules_fmt": "Real resources only: gains up to %dh; bacteria and risks up to %dh.",
		"capped_fmt": "Time away beyond %dh grants no further settlement.",
		"close": "Return to culture"
	},
	"ja": {
		"title": "休眠培養レポート",
		"cap_note_fmt": " · 上限%d時間に到達",
		"absence_fmt": "不在 %s · 精算 %s%s",
		"collection": "実際の採集",
		"feeder_organic_fmt": "吸収菌糸：有機 +%.3f",
		"feeder_mineral_fmt": "吸収菌糸：ミネラル +%.3f",
		"expedition_organic_fmt": "遠征：有機 +%.3f",
		"expedition_mineral_fmt": "遠征：ミネラル +%.3f",
		"balance_fmt": "残高：有機 %+.3f · ミネラル %+.3f",
		"growth": "成長と探索",
		"dna_fmt": "DNA 完了 +%d",
		"units_fmt": "胞子：生産 +%d · 修復 +%d · 損失 %d",
		"exploration_fmt": "探索マス +%d（%+.2f%%）",
		"hotspots_fmt": "異常区域の発見 +%d",
		"bacteria_fmt": "細菌：誕生 %d · 撃破 %d",
		"biomass_fmt": "コア生物量 %+.3f · 生存コア %d → %d",
		"rules_fmt": "実資源のみ：収益は最大%d時間、細菌と危険は最大%d時間。",
		"capped_fmt": "%d時間を超えた不在時間は精算されません。",
		"close": "培養皿に戻る"
	},
	"es": {
		"title": "Informe del cultivo sin conexión",
		"cap_note_fmt": " · Límite de %d h alcanzado",
		"absence_fmt": "Ausencia %s · Calculado %s%s",
		"collection": "Recolección real",
		"feeder_organic_fmt": "Hifas: orgánico +%.3f",
		"feeder_mineral_fmt": "Hifas: minerales +%.3f",
		"expedition_organic_fmt": "Expediciones: orgánico +%.3f",
		"expedition_mineral_fmt": "Expediciones: minerales +%.3f",
		"balance_fmt": "Saldo: orgánico %+.3f · minerales %+.3f",
		"growth": "Crecimiento y exploración",
		"dna_fmt": "ADN completado +%d",
		"units_fmt": "Esporas: creadas +%d · reparadas +%d · perdidas %d",
		"exploration_fmt": "Casillas exploradas +%d (%+.2f%%)",
		"hotspots_fmt": "Anomalías halladas +%d",
		"bacteria_fmt": "Bacterias: nacidas %d · eliminadas %d",
		"biomass_fmt": "Biomasa de núcleos %+.3f · Núcleos vivos %d → %d",
		"rules_fmt": "Recursos reales: ganancias hasta %d h; bacterias y riesgos hasta %d h.",
		"capped_fmt": "La ausencia que supere %d h no se calcula.",
		"close": "Volver al cultivo"
	},
	"de": {
		"title": "Offline-Kulturbericht",
		"cap_note_fmt": " · Grenze von %d h erreicht",
		"absence_fmt": "Abwesend %s · Berechnet %s%s",
		"collection": "Tatsächliche Sammlung",
		"feeder_organic_fmt": "Saughyphen: Organik +%.3f",
		"feeder_mineral_fmt": "Saughyphen: Mineralien +%.3f",
		"expedition_organic_fmt": "Expeditionen: Organik +%.3f",
		"expedition_mineral_fmt": "Expeditionen: Mineralien +%.3f",
		"balance_fmt": "Bilanz: Organik %+.3f · Mineralien %+.3f",
		"growth": "Wachstum und Erkundung",
		"dna_fmt": "DNA fertig +%d",
		"units_fmt": "Sporen: gebaut +%d · repariert +%d · verloren %d",
		"exploration_fmt": "Erkundete Felder +%d (%+.2f%%)",
		"hotspots_fmt": "Anomalien entdeckt +%d",
		"bacteria_fmt": "Bakterien: geboren %d · vernichtet %d",
		"biomass_fmt": "Kernbiomasse %+.3f · Lebende Kerne %d → %d",
		"rules_fmt": "Reale Ressourcen: Erträge bis %d h; Bakterien und Risiken bis %d h.",
		"capped_fmt": "Abwesenheit über %d h hinaus wird nicht berechnet.",
		"close": "Zur Kultur zurück"
	},
	"ru": {
		"title": "Отчёт о культуре офлайн",
		"cap_note_fmt": " · Достигнут предел %d ч",
		"absence_fmt": "Отсутствие %s · Учтено %s%s",
		"collection": "Фактический сбор",
		"feeder_organic_fmt": "Гифы: органика +%.3f",
		"feeder_mineral_fmt": "Гифы: минералы +%.3f",
		"expedition_organic_fmt": "Экспедиции: органика +%.3f",
		"expedition_mineral_fmt": "Экспедиции: минералы +%.3f",
		"balance_fmt": "Баланс: органика %+.3f · минералы %+.3f",
		"growth": "Рост и разведка",
		"dna_fmt": "ДНК завершено +%d",
		"units_fmt": "Споры: создано +%d · восстановлено +%d · потери %d",
		"exploration_fmt": "Разведано клеток +%d (%+.2f%%)",
		"hotspots_fmt": "Найдено аномалий +%d",
		"bacteria_fmt": "Бактерии: родилось %d · уничтожено %d",
		"biomass_fmt": "Биомасса ядер %+.3f · Живые ядра %d → %d",
		"rules_fmt": "Реальные ресурсы: доход до %d ч; бактерии и риски до %d ч.",
		"capped_fmt": "Время отсутствия свыше %d ч не учитывается.",
		"close": "Вернуться к культуре"
	}
}


static func text(key: String, locale: String) -> String:
	var table: Dictionary = TEXTS.get(locale, TEXTS["en"])
	return String(table.get(key, (TEXTS["en"] as Dictionary).get(key, key)))
