extends RefCounted


const LOCALES: Array[String] = ["zh_CN", "zh_TW", "en", "ja", "es", "de", "ru"]

const LOCALE_NAMES := {
	"zh_CN": "简体中文",
	"zh_TW": "繁體中文",
	"en": "English",
	"ja": "日本語",
	"es": "Español",
	"de": "Deutsch",
	"ru": "Русский"
}

const TEXTS := {
	"zh_CN": {
		"brand_title": "游戏：超级无聊真菌",
		"chapter_subtitle": "第一章 · 实验室培养",
		"settings_title": "设置 · 像素实验室星云",
		"settings_subtitle": "语言与五路音量独立保存 · 0% 即静音",
		"language_title": "选择语言",
		"language_subtitle": "立即生效 · 自动保存",
		"language_hint": "选择界面语言 · Esc 返回设置",
		"language_label": "语言　%s",
		"display_mode": "显示模式　%s",
		"fullscreen": "全屏",
		"windowed": "窗口",
		"pixel_cursor": "像素鼠标　%s",
		"enabled": "开启",
		"disabled": "关闭",
		"volume_master": "总音量　%d%%",
		"volume_ui": "界面音效　%d%%",
		"volume_world": "菌落音效　%d%%",
		"volume_combat": "战斗音效　%d%%",
		"volume_ambient": "背景音　%d%%",
		"back": "返回",
		"confirm_new": "确认覆盖并开始",
		"cancel": "取消",
		"view_failed": "查看失活培养",
		"continue_culture": "继续培养",
		"load_save": "读取存档",
		"start_new": "开始新培养",
		"settings": "设置",
		"exit": "退出",
		"start": "开始培养",
		"hint_save": "检测到培养记录 · 可继续或开始新培养",
		"hint_no_save": "尚无培养记录 · 将从一个孢子核心开始",
		"hint_settings": "设置会自动保存 · Esc 返回",
		"hint_new_confirm": "现有培养记录将被永久覆盖",
		"pause_title": "培养已暂停",
		"pause_settings": "暂停设置",
		"pause_language": "选择界面语言",
		"pause_restart_confirm": "确认重新培养",
		"confirm_restart": "确认覆盖并重新开始",
		"save_now": "立即保存",
		"save_return": "保存并返回主菜单",
		"restart_culture": "重新开始培养",
		"pause_hint_restart": "当前培养记录将被永久覆盖，此操作不可撤销。",
		"pause_hint_main": "Esc 继续培养 · 暂停期间模拟完全冻结",
		"save_notice": "培养记录已保存",
		"game_over_title": "菌落失活",
		"game_over_detail": "所有孢子核心的生物量均已归零",
		"game_over_body": "培养已真正暂停；你可以重新开始或返回主菜单。",
		"game_over_restart": "重新培养",
		"back_main": "返回主菜单"
	},
	"zh_TW": {
		"brand_title": "遊戲：超級無聊真菌",
		"chapter_subtitle": "第一章 · 實驗室培養",
		"settings_title": "設定 · 像素實驗室星雲",
		"settings_subtitle": "語言與五路音量分別儲存 · 0% 即靜音",
		"language_title": "選擇語言",
		"language_subtitle": "立即套用 · 自動儲存",
		"language_hint": "選擇介面語言 · Esc 返回設定",
		"language_label": "語言　%s",
		"display_mode": "顯示模式　%s",
		"fullscreen": "全螢幕",
		"windowed": "視窗",
		"pixel_cursor": "像素滑鼠　%s",
		"enabled": "開啟",
		"disabled": "關閉",
		"volume_master": "總音量　%d%%",
		"volume_ui": "介面音效　%d%%",
		"volume_world": "菌落音效　%d%%",
		"volume_combat": "戰鬥音效　%d%%",
		"volume_ambient": "背景音　%d%%",
		"back": "返回",
		"confirm_new": "確認覆蓋並開始",
		"cancel": "取消",
		"view_failed": "查看失活培養",
		"continue_culture": "繼續培養",
		"load_save": "讀取存檔",
		"start_new": "開始新培養",
		"settings": "設定",
		"exit": "退出",
		"start": "開始培養",
		"hint_save": "偵測到培養記錄 · 可繼續或開始新培養",
		"hint_no_save": "尚無培養記錄 · 將從一個孢子核心開始",
		"hint_settings": "設定會自動儲存 · Esc 返回",
		"hint_new_confirm": "現有培養記錄將被永久覆蓋",
		"pause_title": "培養已暫停",
		"pause_settings": "暫停設定",
		"pause_language": "選擇介面語言",
		"pause_restart_confirm": "確認重新培養",
		"confirm_restart": "確認覆蓋並重新開始",
		"save_now": "立即儲存",
		"save_return": "儲存並返回主選單",
		"restart_culture": "重新開始培養",
		"pause_hint_restart": "目前培養記錄將被永久覆蓋，此操作無法復原。",
		"pause_hint_main": "Esc 繼續培養 · 暫停期間模擬完全凍結",
		"save_notice": "培養記錄已儲存",
		"game_over_title": "菌落失活",
		"game_over_detail": "所有孢子核心的生物量均已歸零",
		"game_over_body": "培養已真正暫停；你可以重新開始或返回主選單。",
		"game_over_restart": "重新培養",
		"back_main": "返回主選單"
	},
	"en": {
		"brand_title": "Game: Super boring fungi",
		"chapter_subtitle": "Chapter 1 · Laboratory Culture",
		"settings_title": "Settings · Pixel Laboratory Nebula",
		"settings_subtitle": "Language and five audio channels save separately · 0% mutes",
		"language_title": "Choose Language",
		"language_subtitle": "Applies instantly · Saves automatically",
		"language_hint": "Choose the interface language · Esc returns to settings",
		"language_label": "Language  %s",
		"display_mode": "Display mode  %s",
		"fullscreen": "Fullscreen",
		"windowed": "Windowed",
		"pixel_cursor": "Pixel cursor  %s",
		"enabled": "On",
		"disabled": "Off",
		"volume_master": "Master volume  %d%%",
		"volume_ui": "UI sounds  %d%%",
		"volume_world": "Colony sounds  %d%%",
		"volume_combat": "Combat sounds  %d%%",
		"volume_ambient": "Background audio  %d%%",
		"back": "Back",
		"confirm_new": "Overwrite and start",
		"cancel": "Cancel",
		"view_failed": "View inactive culture",
		"continue_culture": "Continue culture",
		"load_save": "Load save",
		"start_new": "Start new culture",
		"settings": "Settings",
		"exit": "Exit",
		"start": "Start culture",
		"hint_save": "Culture save detected · Continue or start a new culture",
		"hint_no_save": "No culture save · Begin with one spore core",
		"hint_settings": "Settings save automatically · Esc returns",
		"hint_new_confirm": "The existing culture save will be permanently overwritten",
		"pause_title": "Culture Paused",
		"pause_settings": "Pause Settings",
		"pause_language": "Choose Interface Language",
		"pause_restart_confirm": "Confirm Restart",
		"confirm_restart": "Overwrite and restart",
		"save_now": "Save now",
		"save_return": "Save and return to main menu",
		"restart_culture": "Restart culture",
		"pause_hint_restart": "This permanently overwrites the current save. It cannot be undone.",
		"pause_hint_main": "Esc continues · Simulation is fully frozen while paused",
		"save_notice": "Culture saved",
		"game_over_title": "Colony Inactive",
		"game_over_detail": "Every spore core has reached zero biomass",
		"game_over_body": "The culture is paused. Restart or return to the main menu.",
		"game_over_restart": "Restart",
		"back_main": "Return to main menu"
	},
	"ja": {
		"brand_title": "ゲーム：超退屈な菌類",
		"chapter_subtitle": "第1章 · 実験室培養",
		"settings_title": "設定 · ピクセル実験室星雲",
		"settings_subtitle": "言語と5系統の音量を個別保存 · 0%でミュート",
		"language_title": "言語を選択",
		"language_subtitle": "即時反映 · 自動保存",
		"language_hint": "表示言語を選択 · Escで設定へ戻る",
		"language_label": "言語　%s",
		"display_mode": "表示モード　%s",
		"fullscreen": "フルスクリーン",
		"windowed": "ウィンドウ",
		"pixel_cursor": "ピクセルカーソル　%s",
		"enabled": "オン",
		"disabled": "オフ",
		"volume_master": "全体音量　%d%%",
		"volume_ui": "UI効果音　%d%%",
		"volume_world": "コロニー音　%d%%",
		"volume_combat": "戦闘音　%d%%",
		"volume_ambient": "BGM　%d%%",
		"back": "戻る",
		"confirm_new": "上書きして開始",
		"cancel": "キャンセル",
		"view_failed": "失活した培養を見る",
		"continue_culture": "培養を続ける",
		"load_save": "セーブを読み込む",
		"start_new": "新しい培養を始める",
		"settings": "設定",
		"exit": "終了",
		"start": "培養を始める",
		"hint_save": "培養記録があります · 続行または新規培養を選べます",
		"hint_no_save": "培養記録はありません · 1つの胞子核から始まります",
		"hint_settings": "設定は自動保存 · Escで戻る",
		"hint_new_confirm": "現在の培養記録は完全に上書きされます",
		"pause_title": "培養を一時停止中",
		"pause_settings": "一時停止設定",
		"pause_language": "表示言語を選択",
		"pause_restart_confirm": "再培養の確認",
		"confirm_restart": "上書きして再開",
		"save_now": "今すぐ保存",
		"save_return": "保存してメインメニューへ",
		"restart_culture": "培養を最初からやり直す",
		"pause_hint_restart": "現在の培養記録は完全に上書きされます。この操作は取り消せません。",
		"pause_hint_main": "Escで培養を続行 · 停止中はシミュレーションも完全停止",
		"save_notice": "培養記録を保存しました",
		"game_over_title": "コロニー失活",
		"game_over_detail": "すべての胞子核のバイオマスがゼロになりました",
		"game_over_body": "培養は停止中です。再開するかメインメニューへ戻れます。",
		"game_over_restart": "再培養",
		"back_main": "メインメニューへ"
	},
	"es": {
		"brand_title": "Juego: Hongos superaburridos",
		"chapter_subtitle": "Capítulo 1 · Cultivo de laboratorio",
		"settings_title": "Ajustes · Nebulosa de laboratorio píxel",
		"settings_subtitle": "Idioma y cinco canales de audio · 0% silencia",
		"language_title": "Elegir idioma",
		"language_subtitle": "Aplicación inmediata · Guardado automático",
		"language_hint": "Elige el idioma de la interfaz · Esc vuelve a ajustes",
		"language_label": "Idioma  %s",
		"display_mode": "Modo de pantalla  %s",
		"fullscreen": "Pantalla completa",
		"windowed": "Ventana",
		"pixel_cursor": "Cursor píxel  %s",
		"enabled": "Sí",
		"disabled": "No",
		"volume_master": "Volumen general  %d%%",
		"volume_ui": "Sonidos de interfaz  %d%%",
		"volume_world": "Sonidos de colonia  %d%%",
		"volume_combat": "Sonidos de combate  %d%%",
		"volume_ambient": "Audio de fondo  %d%%",
		"back": "Volver",
		"confirm_new": "Sobrescribir e iniciar",
		"cancel": "Cancelar",
		"view_failed": "Ver cultivo inactivo",
		"continue_culture": "Continuar cultivo",
		"load_save": "Cargar partida",
		"start_new": "Iniciar nuevo cultivo",
		"settings": "Ajustes",
		"exit": "Salir",
		"start": "Iniciar cultivo",
		"hint_save": "Cultivo guardado detectado · Continúa o inicia uno nuevo",
		"hint_no_save": "Sin cultivo guardado · Empieza con un núcleo de espora",
		"hint_settings": "Los ajustes se guardan solos · Esc vuelve",
		"hint_new_confirm": "El cultivo existente se sobrescribirá para siempre",
		"pause_title": "Cultivo en pausa",
		"pause_settings": "Ajustes de pausa",
		"pause_language": "Elegir idioma de interfaz",
		"pause_restart_confirm": "Confirmar reinicio",
		"confirm_restart": "Sobrescribir y reiniciar",
		"save_now": "Guardar ahora",
		"save_return": "Guardar y volver al menú",
		"restart_culture": "Reiniciar cultivo",
		"pause_hint_restart": "La partida actual se sobrescribirá. No se puede deshacer.",
		"pause_hint_main": "Esc continúa · La simulación se congela durante la pausa",
		"save_notice": "Cultivo guardado",
		"game_over_title": "Colonia inactiva",
		"game_over_detail": "Todos los núcleos de espora llegaron a cero biomasa",
		"game_over_body": "El cultivo está en pausa. Reinícialo o vuelve al menú principal.",
		"game_over_restart": "Reiniciar",
		"back_main": "Volver al menú"
	},
	"de": {
		"brand_title": "Spiel: Superlangweilige Pilze",
		"chapter_subtitle": "Kapitel 1 · Laborkultur",
		"settings_title": "Einstellungen · Pixel-Labornebel",
		"settings_subtitle": "Sprache und fünf Audiokanäle · 0% schaltet stumm",
		"language_title": "Sprache wählen",
		"language_subtitle": "Sofort aktiv · Automatisch gespeichert",
		"language_hint": "Oberflächensprache wählen · Esc zurück zu den Einstellungen",
		"language_label": "Sprache  %s",
		"display_mode": "Anzeigemodus  %s",
		"fullscreen": "Vollbild",
		"windowed": "Fenster",
		"pixel_cursor": "Pixelzeiger  %s",
		"enabled": "An",
		"disabled": "Aus",
		"volume_master": "Gesamtlautstärke  %d%%",
		"volume_ui": "UI-Klänge  %d%%",
		"volume_world": "Kolonieklänge  %d%%",
		"volume_combat": "Kampfklänge  %d%%",
		"volume_ambient": "Hintergrundklang  %d%%",
		"back": "Zurück",
		"confirm_new": "Überschreiben und starten",
		"cancel": "Abbrechen",
		"view_failed": "Inaktive Kultur ansehen",
		"continue_culture": "Kultur fortsetzen",
		"load_save": "Spielstand laden",
		"start_new": "Neue Kultur starten",
		"settings": "Einstellungen",
		"exit": "Beenden",
		"start": "Kultur starten",
		"hint_save": "Kulturstand gefunden · Fortsetzen oder neu beginnen",
		"hint_no_save": "Kein Kulturstand · Start mit einem Sporenkern",
		"hint_settings": "Einstellungen speichern automatisch · Esc zurück",
		"hint_new_confirm": "Der vorhandene Kulturstand wird dauerhaft überschrieben",
		"pause_title": "Kultur pausiert",
		"pause_settings": "Pauseneinstellungen",
		"pause_language": "Oberflächensprache wählen",
		"pause_restart_confirm": "Neustart bestätigen",
		"confirm_restart": "Überschreiben und neu starten",
		"save_now": "Jetzt speichern",
		"save_return": "Speichern und zum Hauptmenü",
		"restart_culture": "Kultur neu starten",
		"pause_hint_restart": "Dieser Spielstand wird unwiderruflich überschrieben.",
		"pause_hint_main": "Esc setzt fort · Während der Pause ist die Simulation eingefroren",
		"save_notice": "Kultur gespeichert",
		"game_over_title": "Kolonie inaktiv",
		"game_over_detail": "Die Biomasse aller Sporenkerne ist auf null gefallen",
		"game_over_body": "Die Kultur pausiert. Neu starten oder zum Hauptmenü.",
		"game_over_restart": "Neu starten",
		"back_main": "Zum Hauptmenü"
	},
	"ru": {
		"brand_title": "Игра: Очень скучные грибы",
		"chapter_subtitle": "Глава 1 · Лабораторная культура",
		"settings_title": "Настройки · Пиксельная лабораторная туманность",
		"settings_subtitle": "Язык и пять каналов звука · 0% отключает звук",
		"language_title": "Выберите язык",
		"language_subtitle": "Сразу применяется · Автосохранение",
		"language_hint": "Выберите язык интерфейса · Esc вернёт к настройкам",
		"language_label": "Язык  %s",
		"display_mode": "Режим экрана  %s",
		"fullscreen": "Полный экран",
		"windowed": "Окно",
		"pixel_cursor": "Пиксельный курсор  %s",
		"enabled": "Вкл.",
		"disabled": "Выкл.",
		"volume_master": "Общая громкость  %d%%",
		"volume_ui": "Звуки интерфейса  %d%%",
		"volume_world": "Звуки колонии  %d%%",
		"volume_combat": "Звуки боя  %d%%",
		"volume_ambient": "Фоновый звук  %d%%",
		"back": "Назад",
		"confirm_new": "Перезаписать и начать",
		"cancel": "Отмена",
		"view_failed": "Показать неактивную культуру",
		"continue_culture": "Продолжить культуру",
		"load_save": "Загрузить сохранение",
		"start_new": "Начать новую культуру",
		"settings": "Настройки",
		"exit": "Выход",
		"start": "Начать культуру",
		"hint_save": "Найдена запись культуры · Продолжите или начните новую",
		"hint_no_save": "Нет записи культуры · Начните с одного спорового ядра",
		"hint_settings": "Настройки сохраняются автоматически · Esc назад",
		"hint_new_confirm": "Текущая запись культуры будет навсегда перезаписана",
		"pause_title": "Культура на паузе",
		"pause_settings": "Настройки паузы",
		"pause_language": "Выберите язык интерфейса",
		"pause_restart_confirm": "Подтвердите перезапуск",
		"confirm_restart": "Перезаписать и начать заново",
		"save_now": "Сохранить сейчас",
		"save_return": "Сохранить и выйти в меню",
		"restart_culture": "Начать культуру заново",
		"pause_hint_restart": "Сохранение будет безвозвратно перезаписано.",
		"pause_hint_main": "Esc продолжает · На паузе симуляция полностью заморожена",
		"save_notice": "Культура сохранена",
		"game_over_title": "Колония неактивна",
		"game_over_detail": "Биомасса всех споровых ядер упала до нуля",
		"game_over_body": "Культура на паузе. Начните заново или вернитесь в меню.",
		"game_over_restart": "Начать заново",
		"back_main": "В главное меню"
	}
}


static func normalize_locale(locale: String) -> String:
	var normalized := locale.strip_edges().replace("-", "_")
	if LOCALES.has(normalized):
		return normalized
	var lowered := normalized.to_lower()
	if lowered.begins_with("zh_tw") or lowered.begins_with("zh_hk") or lowered.begins_with("zh_hant"):
		return "zh_TW"
	if lowered.begins_with("zh"):
		return "zh_CN"
	for locale_id in ["en", "ja", "es", "de", "ru"]:
		if lowered.begins_with(locale_id):
			return locale_id
	return "zh_CN"


static func locale_name(locale: String) -> String:
	var normalized := normalize_locale(locale)
	return String(LOCALE_NAMES.get(normalized, LOCALE_NAMES["zh_CN"]))


static func text(key: String, locale: String) -> String:
	var normalized := normalize_locale(locale)
	var localized: Dictionary = TEXTS.get(normalized, {})
	if localized.has(key):
		return String(localized[key])
	var fallback: Dictionary = TEXTS["en"]
	return String(fallback.get(key, key))
