extends RefCounted


const LOCALES: Array[String] = ["zh_CN", "zh_TW", "en", "ja", "es", "de", "ru"]

# Upgrade-shop copy is isolated from gameplay state: callers pass stable IDs and
# only resolve names/descriptions at draw or feedback time.
const TEXTS := {
	"zh_CN": {
		"title": "进化与结构", "dna_fmt": "DNA %d", "simulation_running": "模拟继续运行",
		"tab_self": "自身能力", "tab_diet": "食性", "tab_structure": "结构", "tab_barracks": "兵营", "tab_environment": "环境适应",
		"placeholder_title": "分页已建立", "environment_placeholder": "实验室环境无需气候适应；该分页留给后续章节",
		"maxed": "已满级", "maxed_short": "已满", "evolve_dna_fmt": "进化 %d DNA", "unlock_dna_fmt": "解锁 %d DNA", "establish_dna_fmt": "确立 %d DNA", "locked": "尚未开放", "mastered": "已掌握",
		"node_level_fmt": "吸收节点 · Lv.%d / %d", "node_core_fmt": "孢子核心 %d", "node_range_fmt": "细菌丝范围 %.0f μm", "node_speed_fmt": "DNA 生产速度 +%d%%", "node_time_fmt": "单次 DNA 时间 %.1f 秒",
		"node_per_level": "每级：范围 +12 μm，DNA 速度 +15%", "node_cost_note": "升级只消耗有机营养，不消耗 DNA", "node_action_fmt": "强化 %.3f", "survival_title": "核心生存进化",
		"survival_wall": "细胞壁增厚", "survival_detox": "解毒代谢", "survival_repair": "修复酶系", "survival_storage": "储备囊泡",
		"survival_level_fmt": "%s · %d/4", "survival_wall_effect_fmt": "核心上限 %.3f", "survival_detox_effect_fmt": "毒素伤害 %d%%", "survival_repair_effect_fmt": "自然 %.3f · 储备 %.3f", "survival_storage_effect_fmt": "每次储备 %.3f", "dna_cost_fmt": "%d DNA",
		"diet_animal_name": "肉食性", "diet_plant_name": "植食性", "diet_bacteria_name": "细菌食性", "diet_fungi_name": "真菌食性",
		"diet_animal_target": "动物组织与小型动物宿主", "diet_plant_target": "植物组织与植物宿主", "diet_bacteria_target": "细菌群落", "diet_fungi_target": "其他真菌与菌落",
		"diet_order_level_fmt": "第 %d 食性 · Lv.%d / 5", "diet_efficiency_fmt": "吸收效率 %d%%", "diet_special": "专属升级", "diet_unset": "尚未确立；新食性成本按十倍增长", "diet_footer": "腐生始终是实验室阶段的基础能力；食性决定未来可利用的生物对象。",
		"diet_back": "返回食性", "diet_components_tab": "能力组件", "diet_units_tab": "专属兵种",
		"component_trap_name": "黏性捕食器", "component_enzymes_name": "胞外消化酶", "component_antibiotic_name": "抗生素分泌",
		"component_trap_desc": "生成细捕食丝，扩大细菌捕获距离", "component_enzymes_desc": "提高捕获细菌转化为有机营养的速度", "component_antibiotic_desc": "压低邻近细菌的吸收与分裂速度",
		"component_level_fmt": "%s · Lv.%d / 3", "component_trap_effect_fmt": "捕获距离 %.0f μm", "component_enzymes_effect_fmt": "消化速度 ×%.2f", "component_antibiotic_effect_fmt": "抑制半径 %.0f μm · 细菌速度 %d%%", "component_antibiotic_none": "尚未形成抑菌区", "component_footer": "三个组件可以并行升级；抗生素会同时减慢细菌吸收与分裂冷却。",
		"unit_animal_attach": "捕食附着体", "unit_animal_pierce": "穿刺孢子", "unit_animal_digest": "消化囊体", "unit_plant_fiber": "纤维分解体", "unit_plant_attach": "表皮附着体", "unit_plant_vessel": "导管扩散体",
		"unit_animal_attach_desc": "附着动物组织并建立消化点", "unit_animal_pierce_desc": "攻击动物表层与运动结构", "unit_animal_digest_desc": "范围分解动物性有机物", "unit_plant_fiber_desc": "针对植物细胞壁的采食单位", "unit_plant_attach_desc": "固定于植物表面建立侵入点", "unit_plant_vessel_desc": "沿植物输导结构进行扩张",
		"unit_lytic_desc": "高速追猎细菌，击杀后携带营养返巢", "unit_suppressor_desc": "右键部署前沿抑菌区，可收拢后重新定位", "unit_disperser_desc": "保持距离，周期释放范围裂解酶", "unit_coil_desc": "切断敌方菌丝；断联分支会失去供给并衰败", "unit_piercer_desc": "附着敌方核心并蓄力穿透", "unit_antifungal_desc": "压低敌菌吸收与扩张，加速断联菌丝衰败",
		"unit_future_animal": "等待小型动物生态", "unit_future_plant": "等待植物组织生态", "unit_available": "解锁后进入兵营生产列表", "unit_future": "后续开放", "unit_unlocked": "已解锁", "diet_unit_footer_fmt": "%s专属部队仅在确立对应食性后出现，并受该食性效率加成。",
		"unit_forager_desc": "通用采集与自卫单位", "unit_carrier_desc": "低速、大容量有机营养运输", "unit_chelator_desc": "专门寻找并运输矿物离子", "unit_scout_desc": "高速移动并自动揭开周围探索黑幕",
		"barracks_mastered": "已掌握，可在兵营切换", "barracks_unlock_all": "解锁后进入所有兵营", "scout_stats_fmt": "感知 Lv.%d · 运动 Lv.%d · 视野 %.0f μm", "scout_vision": "感知网络", "scout_speed": "鞭毛运动", "scout_upgrade_fmt": "%s %d DNA", "barracks_footer": "通用兵种在此解锁；食性特攻部队位于各食性的“专属升级”页面。",
		"structure_branching_name": "菌丝分枝", "structure_elongation_name": "顶端延伸", "structure_feeders_name": "吸收网络", "structure_growth_name": "生长代谢",
		"structure_branching_desc": "提高每个孢子核心可维持的主菌丝总长度", "structure_elongation_desc": "提高一次操作能够延伸的最大菌丝长度", "structure_feeders_desc": "增加同时连接营养点的细吸收菌丝数量", "structure_growth_desc": "缩短新生主菌丝完成生长所需的时间",
		"structure_level_fmt": "%s · Lv.%d / 4", "structure_capacity_fmt": "每个核心容量 %.0f μm", "structure_segment_fmt": "单段上限 %.0f μm", "structure_feeders_fmt": "同时吸收 %d 条", "structure_growth_fmt": "生长时间 %.1f 秒", "structure_footer": "结构升级对所有孢子核心生效，同一阶段内可以继续追加等级。",
		"toast_node_max": "细菌丝延展范围已达到当前上限", "toast_node_need_fmt": "有机营养不足：本次强化需要 %.3f", "toast_node_done_fmt": "节点 Lv.%d · 范围 %.0f μm · DNA 速度 +%d%%",
		"toast_diet_need_fmt": "DNA 不足：建立新食性需要 %d", "toast_diet_established_fmt": "已确立%s · 初始吸收效率 20%%", "toast_diet_max_fmt": "%s吸收效率已达到 100%%", "toast_diet_level_need_fmt": "DNA 不足：效率升级需要 %d", "toast_diet_done_fmt": "%s效率提升至 %d%%",
		"toast_unlock_need_fmt": "DNA 不足：解锁%s需要 %d", "toast_barracks_unlocked_fmt": "已解锁%s；现在可在兵营切换生产", "toast_upgrade_max_fmt": "%s已达到最高等级", "toast_upgrade_need_fmt": "DNA 不足：强化%s需要 %d", "toast_upgrade_done_fmt": "%s提升至 Lv.%d", "toast_diet_required_fmt": "需要先确立%s", "toast_unit_unlocked_fmt": "已解锁%s；兵营生产列表已更新", "toast_component_need_fmt": "DNA 不足：本次进化需要 %d", "toast_structure_need_fmt": "DNA 不足：本次结构进化需要 %d", "toast_survival_need_fmt": "DNA 不足：本次生存进化需要 %d", "toast_current_max_fmt": "%s已达到当前上限", "toast_level3_fmt": "%s · Lv.%d / 3", "toast_level4_fmt": "%s · Lv.%d / 4"
	},
	"zh_TW": {
		"title": "進化與結構", "dna_fmt": "DNA %d", "simulation_running": "模擬持續運行", "tab_self": "自身能力", "tab_diet": "食性", "tab_structure": "結構", "tab_barracks": "兵營", "tab_environment": "環境適應", "placeholder_title": "分頁已建立", "environment_placeholder": "實驗室環境無需氣候適應；此分頁留給後續章節", "maxed": "已滿級", "maxed_short": "已滿", "evolve_dna_fmt": "進化 %d DNA", "unlock_dna_fmt": "解鎖 %d DNA", "establish_dna_fmt": "確立 %d DNA", "locked": "尚未開放", "mastered": "已掌握",
		"node_level_fmt": "吸收節點 · Lv.%d / %d", "node_core_fmt": "孢子核心 %d", "node_range_fmt": "細菌絲範圍 %.0f μm", "node_speed_fmt": "DNA 生產速度 +%d%%", "node_time_fmt": "單次 DNA 時間 %.1f 秒", "node_per_level": "每級：範圍 +12 μm，DNA 速度 +15%", "node_cost_note": "升級只消耗有機營養，不消耗 DNA", "node_action_fmt": "強化 %.3f", "survival_title": "核心生存進化", "survival_wall": "細胞壁增厚", "survival_detox": "解毒代謝", "survival_repair": "修復酶系", "survival_storage": "儲備囊泡", "survival_level_fmt": "%s · %d/4", "survival_wall_effect_fmt": "核心上限 %.3f", "survival_detox_effect_fmt": "毒素傷害 %d%%", "survival_repair_effect_fmt": "自然 %.3f · 儲備 %.3f", "survival_storage_effect_fmt": "每次儲備 %.3f", "dna_cost_fmt": "%d DNA",
		"diet_animal_name": "肉食性", "diet_plant_name": "植食性", "diet_bacteria_name": "細菌食性", "diet_fungi_name": "真菌食性", "diet_animal_target": "動物組織與小型動物宿主", "diet_plant_target": "植物組織與植物宿主", "diet_bacteria_target": "細菌群落", "diet_fungi_target": "其他真菌與菌落", "diet_order_level_fmt": "第 %d 食性 · Lv.%d / 5", "diet_efficiency_fmt": "吸收效率 %d%%", "diet_special": "專屬升級", "diet_unset": "尚未確立；新食性成本按十倍增長", "diet_footer": "腐生始終是實驗室階段的基礎能力；食性決定未來可利用的生物對象。", "diet_back": "返回食性", "diet_components_tab": "能力組件", "diet_units_tab": "專屬兵種",
		"component_trap_name": "黏性捕食器", "component_enzymes_name": "胞外消化酶", "component_antibiotic_name": "抗生素分泌", "component_trap_desc": "生成細捕食絲，擴大細菌捕獲距離", "component_enzymes_desc": "提高捕獲細菌轉化為有機營養的速度", "component_antibiotic_desc": "壓低鄰近細菌的吸收與分裂速度", "component_level_fmt": "%s · Lv.%d / 3", "component_trap_effect_fmt": "捕獲距離 %.0f μm", "component_enzymes_effect_fmt": "消化速度 ×%.2f", "component_antibiotic_effect_fmt": "抑制半徑 %.0f μm · 細菌速度 %d%%", "component_antibiotic_none": "尚未形成抑菌區", "component_footer": "三個組件可以並行升級；抗生素會同時減慢細菌吸收與分裂冷卻。",
		"unit_animal_attach": "捕食附著體", "unit_animal_pierce": "穿刺孢子", "unit_animal_digest": "消化囊體", "unit_plant_fiber": "纖維分解體", "unit_plant_attach": "表皮附著體", "unit_plant_vessel": "導管擴散體", "unit_animal_attach_desc": "附著動物組織並建立消化點", "unit_animal_pierce_desc": "攻擊動物表層與運動結構", "unit_animal_digest_desc": "範圍分解動物性有機物", "unit_plant_fiber_desc": "針對植物細胞壁的採食單位", "unit_plant_attach_desc": "固定於植物表面建立侵入點", "unit_plant_vessel_desc": "沿植物輸導結構進行擴張", "unit_lytic_desc": "高速追獵細菌，擊殺後攜帶營養返巢", "unit_suppressor_desc": "右鍵部署前沿抑菌區，可收攏後重新定位", "unit_disperser_desc": "保持距離，週期釋放範圍裂解酶", "unit_coil_desc": "切斷敵方菌絲；斷聯分支會失去供給並衰敗", "unit_piercer_desc": "附著敵方核心並蓄力穿透", "unit_antifungal_desc": "壓低敵菌吸收與擴張，加速斷聯菌絲衰敗", "unit_future_animal": "等待小型動物生態", "unit_future_plant": "等待植物組織生態", "unit_available": "解鎖後進入兵營生產列表", "unit_future": "後續開放", "unit_unlocked": "已解鎖", "diet_unit_footer_fmt": "%s專屬部隊僅在確立對應食性後出現，並受該食性效率加成。",
		"unit_forager_desc": "通用採集與自衛單位", "unit_carrier_desc": "低速、大容量有機營養運輸", "unit_chelator_desc": "專門尋找並運輸礦物離子", "unit_scout_desc": "高速移動並自動揭開周圍探索黑幕", "barracks_mastered": "已掌握，可在兵營切換", "barracks_unlock_all": "解鎖後進入所有兵營", "scout_stats_fmt": "感知 Lv.%d · 運動 Lv.%d · 視野 %.0f μm", "scout_vision": "感知網路", "scout_speed": "鞭毛運動", "scout_upgrade_fmt": "%s %d DNA", "barracks_footer": "通用兵種在此解鎖；食性特攻部隊位於各食性的「專屬升級」頁面。",
		"structure_branching_name": "菌絲分枝", "structure_elongation_name": "頂端延伸", "structure_feeders_name": "吸收網路", "structure_growth_name": "生長代謝", "structure_branching_desc": "提高每個孢子核心可維持的主菌絲總長度", "structure_elongation_desc": "提高一次操作能延伸的最大菌絲長度", "structure_feeders_desc": "增加同時連接營養點的細吸收菌絲數量", "structure_growth_desc": "縮短新生主菌絲完成生長所需的時間", "structure_level_fmt": "%s · Lv.%d / 4", "structure_capacity_fmt": "每個核心容量 %.0f μm", "structure_segment_fmt": "單段上限 %.0f μm", "structure_feeders_fmt": "同時吸收 %d 條", "structure_growth_fmt": "生長時間 %.1f 秒", "structure_footer": "結構升級對所有孢子核心生效，同一階段內可以繼續追加等級。",
		"toast_node_max": "細菌絲延展範圍已達目前上限", "toast_node_need_fmt": "有機營養不足：本次強化需要 %.3f", "toast_node_done_fmt": "節點 Lv.%d · 範圍 %.0f μm · DNA 速度 +%d%%", "toast_diet_need_fmt": "DNA 不足：建立新食性需要 %d", "toast_diet_established_fmt": "已確立%s · 初始吸收效率 20%%", "toast_diet_max_fmt": "%s吸收效率已達 100%%", "toast_diet_level_need_fmt": "DNA 不足：效率升級需要 %d", "toast_diet_done_fmt": "%s效率提升至 %d%%", "toast_unlock_need_fmt": "DNA 不足：解鎖%s需要 %d", "toast_barracks_unlocked_fmt": "已解鎖%s；現在可在兵營切換生產", "toast_upgrade_max_fmt": "%s已達最高等級", "toast_upgrade_need_fmt": "DNA 不足：強化%s需要 %d", "toast_upgrade_done_fmt": "%s提升至 Lv.%d", "toast_diet_required_fmt": "需要先確立%s", "toast_unit_unlocked_fmt": "已解鎖%s；兵營生產列表已更新", "toast_component_need_fmt": "DNA 不足：本次進化需要 %d", "toast_structure_need_fmt": "DNA 不足：本次結構進化需要 %d", "toast_survival_need_fmt": "DNA 不足：本次生存進化需要 %d", "toast_current_max_fmt": "%s已達目前上限", "toast_level3_fmt": "%s · Lv.%d / 3", "toast_level4_fmt": "%s · Lv.%d / 4"
	},
	"en": {
		"title": "Evolution & Structure", "dna_fmt": "DNA %d", "simulation_running": "Simulation continues", "tab_self": "Self", "tab_diet": "Diet", "tab_structure": "Structure", "tab_barracks": "Barracks", "tab_environment": "Adaptation", "placeholder_title": "Page ready", "environment_placeholder": "The laboratory needs no climate adaptation; this page is reserved for later chapters.", "maxed": "Max level", "maxed_short": "Max", "evolve_dna_fmt": "Evolve %d DNA", "unlock_dna_fmt": "Unlock %d DNA", "establish_dna_fmt": "Adopt %d DNA", "locked": "Not available", "mastered": "Mastered",
		"node_level_fmt": "Feeder node · Lv.%d / %d", "node_core_fmt": "Spore core %d", "node_range_fmt": "Feeder reach %.0f μm", "node_speed_fmt": "DNA production +%d%%", "node_time_fmt": "Time per DNA %.1f s", "node_per_level": "Each level: +12 μm reach, +15% DNA speed", "node_cost_note": "Uses organic nutrients only; no DNA cost", "node_action_fmt": "Enhance %.3f", "survival_title": "Core survival", "survival_wall": "Thicker wall", "survival_detox": "Detox metabolism", "survival_repair": "Repair enzymes", "survival_storage": "Reserve vesicles", "survival_level_fmt": "%s · %d/4", "survival_wall_effect_fmt": "Core cap %.3f", "survival_detox_effect_fmt": "Toxin damage %d%%", "survival_repair_effect_fmt": "Passive %.3f · reserve %.3f", "survival_storage_effect_fmt": "Reserve dose %.3f", "dna_cost_fmt": "%d DNA",
		"diet_animal_name": "Carnivory", "diet_plant_name": "Herbivory", "diet_bacteria_name": "Bacterivory", "diet_fungi_name": "Mycophagy", "diet_animal_target": "Animal tissue and small hosts", "diet_plant_target": "Plant tissue and hosts", "diet_bacteria_target": "Bacterial colonies", "diet_fungi_target": "Other fungi and colonies", "diet_order_level_fmt": "Diet %d · Lv.%d / 5", "diet_efficiency_fmt": "Absorption %d%%", "diet_special": "Special upgrades", "diet_unset": "Not adopted; each new diet costs 10× more", "diet_footer": "Saprotrophy remains the laboratory baseline; diets decide which organisms can be used.", "diet_back": "Back to diets", "diet_components_tab": "Components", "diet_units_tab": "Special units",
		"component_trap_name": "Sticky trap", "component_enzymes_name": "External enzymes", "component_antibiotic_name": "Antibiotic secretion", "component_trap_desc": "Grows fine hunting hyphae to catch bacteria farther away", "component_enzymes_desc": "Converts captured bacteria into organic nutrients faster", "component_antibiotic_desc": "Slows nearby bacterial absorption and division", "component_level_fmt": "%s · Lv.%d / 3", "component_trap_effect_fmt": "Capture reach %.0f μm", "component_enzymes_effect_fmt": "Digestion ×%.2f", "component_antibiotic_effect_fmt": "Suppression %.0f μm · bacteria %d%%", "component_antibiotic_none": "No suppression zone yet", "component_footer": "All three components can evolve in parallel; antibiotics slow absorption and division.",
		"unit_animal_attach": "Predatory holdfast", "unit_animal_pierce": "Piercing spore", "unit_animal_digest": "Digestive capsule", "unit_plant_fiber": "Fiber degrader", "unit_plant_attach": "Epidermal holdfast", "unit_plant_vessel": "Vessel disperser", "unit_animal_attach_desc": "Attaches to animal tissue and forms a digestive site", "unit_animal_pierce_desc": "Attacks animal surfaces and movement structures", "unit_animal_digest_desc": "Breaks down animal organics over an area", "unit_plant_fiber_desc": "Feeds on plant cell walls", "unit_plant_attach_desc": "Anchors to plant surfaces and starts invasion", "unit_plant_vessel_desc": "Spreads along plant transport tissue", "unit_lytic_desc": "Hunts bacteria quickly and returns nutrients home", "unit_suppressor_desc": "Deploys a movable forward suppression zone", "unit_disperser_desc": "Keeps range and releases lytic enzymes in bursts", "unit_coil_desc": "Cuts enemy hyphae; isolated branches wither", "unit_piercer_desc": "Attaches to enemy cores and charges a piercing attack", "unit_antifungal_desc": "Slows enemy feeding and growth; isolated hyphae decay faster", "unit_future_animal": "Requires small-animal ecology", "unit_future_plant": "Requires plant-tissue ecology", "unit_available": "Adds to barracks production", "unit_future": "Coming later", "unit_unlocked": "Unlocked", "diet_unit_footer_fmt": "%s units appear only after adopting that diet and scale with its efficiency.",
		"unit_forager_desc": "General gathering and self-defense", "unit_carrier_desc": "Slow, high-capacity organic transport", "unit_chelator_desc": "Finds and transports mineral ions", "unit_scout_desc": "Moves quickly and reveals fog automatically", "barracks_mastered": "Mastered; selectable in barracks", "barracks_unlock_all": "Adds to every barracks", "scout_stats_fmt": "Sense Lv.%d · motion Lv.%d · vision %.0f μm", "scout_vision": "Sensory net", "scout_speed": "Flagellar motion", "scout_upgrade_fmt": "%s %d DNA", "barracks_footer": "Unlock general units here; diet specialists are under each diet's Special Upgrades.",
		"structure_branching_name": "Hyphal branching", "structure_elongation_name": "Tip extension", "structure_feeders_name": "Feeder network", "structure_growth_name": "Growth metabolism", "structure_branching_desc": "Raises the main-hypha length supported by each core", "structure_elongation_desc": "Raises the maximum length of one extension", "structure_feeders_desc": "Connects more nutrient points at once", "structure_growth_desc": "Shortens growth time for new main hyphae", "structure_level_fmt": "%s · Lv.%d / 4", "structure_capacity_fmt": "Capacity per core %.0f μm", "structure_segment_fmt": "Segment cap %.0f μm", "structure_feeders_fmt": "%d simultaneous feeders", "structure_growth_fmt": "Growth time %.1f s", "structure_footer": "Structure upgrades affect every spore core and can gain more levels in this stage.",
		"toast_node_max": "Feeder reach is at the current limit", "toast_node_need_fmt": "Not enough organic nutrients: enhancement needs %.3f", "toast_node_done_fmt": "Node Lv.%d · reach %.0f μm · DNA speed +%d%%", "toast_diet_need_fmt": "Not enough DNA: a new diet needs %d", "toast_diet_established_fmt": "%s adopted · initial absorption 20%%", "toast_diet_max_fmt": "%s absorption has reached 100%%", "toast_diet_level_need_fmt": "Not enough DNA: efficiency needs %d", "toast_diet_done_fmt": "%s efficiency raised to %d%%", "toast_unlock_need_fmt": "Not enough DNA: unlocking %s needs %d", "toast_barracks_unlocked_fmt": "%s unlocked; barracks can now produce it", "toast_upgrade_max_fmt": "%s is at maximum level", "toast_upgrade_need_fmt": "Not enough DNA: improving %s needs %d", "toast_upgrade_done_fmt": "%s raised to Lv.%d", "toast_diet_required_fmt": "Adopt %s first", "toast_unit_unlocked_fmt": "%s unlocked; barracks list updated", "toast_component_need_fmt": "Not enough DNA: this evolution needs %d", "toast_structure_need_fmt": "Not enough DNA: this structure evolution needs %d", "toast_survival_need_fmt": "Not enough DNA: this survival evolution needs %d", "toast_current_max_fmt": "%s is at the current limit", "toast_level3_fmt": "%s · Lv.%d / 3", "toast_level4_fmt": "%s · Lv.%d / 4"
	},
	"ja": {
		"title": "進化と構造", "dna_fmt": "DNA %d", "simulation_running": "シミュレーション継続中", "tab_self": "自己能力", "tab_diet": "食性", "tab_structure": "構造", "tab_barracks": "兵舎", "tab_environment": "環境適応", "placeholder_title": "ページ準備済み", "environment_placeholder": "研究室では気候適応は不要です。後の章で使用します。", "maxed": "最大レベル", "maxed_short": "最大", "evolve_dna_fmt": "進化 %d DNA", "unlock_dna_fmt": "解放 %d DNA", "establish_dna_fmt": "確立 %d DNA", "locked": "未開放", "mastered": "習得済み",
		"node_level_fmt": "吸収ノード · Lv.%d / %d", "node_core_fmt": "胞子コア %d", "node_range_fmt": "吸収菌糸範囲 %.0f μm", "node_speed_fmt": "DNA生産速度 +%d%%", "node_time_fmt": "DNA 1個の時間 %.1f秒", "node_per_level": "各レベル：範囲 +12 μm、DNA速度 +15%", "node_cost_note": "有機栄養のみ消費し、DNAは不要", "node_action_fmt": "強化 %.3f", "survival_title": "コア生存進化", "survival_wall": "細胞壁肥厚", "survival_detox": "解毒代謝", "survival_repair": "修復酵素", "survival_storage": "貯蔵小胞", "survival_level_fmt": "%s · %d/4", "survival_wall_effect_fmt": "コア上限 %.3f", "survival_detox_effect_fmt": "毒素ダメージ %d%%", "survival_repair_effect_fmt": "自然 %.3f · 備蓄 %.3f", "survival_storage_effect_fmt": "備蓄量 %.3f", "dna_cost_fmt": "%d DNA",
		"diet_animal_name": "肉食性", "diet_plant_name": "植物食性", "diet_bacteria_name": "細菌食性", "diet_fungi_name": "菌食性", "diet_animal_target": "動物組織と小型宿主", "diet_plant_target": "植物組織と宿主", "diet_bacteria_target": "細菌コロニー", "diet_fungi_target": "他の真菌とコロニー", "diet_order_level_fmt": "第%d食性 · Lv.%d / 5", "diet_efficiency_fmt": "吸収効率 %d%%", "diet_special": "専用進化", "diet_unset": "未確立。新食性ごとにコスト10倍", "diet_footer": "腐生は研究室での基礎能力です。食性が利用できる生物を決めます。", "diet_back": "食性へ戻る", "diet_components_tab": "能力部品", "diet_units_tab": "専用兵種",
		"component_trap_name": "粘着捕食器", "component_enzymes_name": "細胞外酵素", "component_antibiotic_name": "抗生物質分泌", "component_trap_desc": "細い捕食菌糸で遠くの細菌を捕獲", "component_enzymes_desc": "捕獲細菌を有機栄養へ速く変換", "component_antibiotic_desc": "近くの細菌の吸収と分裂を低下", "component_level_fmt": "%s · Lv.%d / 3", "component_trap_effect_fmt": "捕獲範囲 %.0f μm", "component_enzymes_effect_fmt": "消化速度 ×%.2f", "component_antibiotic_effect_fmt": "抑制半径 %.0f μm · 細菌速度 %d%%", "component_antibiotic_none": "抑菌域なし", "component_footer": "3部品は並行進化可能。抗生物質は吸収と分裂を遅らせます。",
		"unit_animal_attach": "捕食付着体", "unit_animal_pierce": "穿刺胞子", "unit_animal_digest": "消化嚢体", "unit_plant_fiber": "繊維分解体", "unit_plant_attach": "表皮付着体", "unit_plant_vessel": "導管拡散体", "unit_animal_attach_desc": "動物組織に付着して消化点を形成", "unit_animal_pierce_desc": "動物表面と運動構造を攻撃", "unit_animal_digest_desc": "動物性有機物を範囲分解", "unit_plant_fiber_desc": "植物細胞壁を摂食", "unit_plant_attach_desc": "植物表面に固定して侵入", "unit_plant_vessel_desc": "植物の輸送組織に沿って拡散", "unit_lytic_desc": "細菌を高速追跡し栄養を持ち帰る", "unit_suppressor_desc": "移動可能な前線抑菌域を展開", "unit_disperser_desc": "距離を保ち溶菌酵素を範囲放出", "unit_coil_desc": "敵菌糸を切断し孤立枝を衰弱", "unit_piercer_desc": "敵コアに付着し穿孔攻撃を蓄力", "unit_antifungal_desc": "敵の吸収と成長を抑え孤立菌糸を加速崩壊", "unit_future_animal": "小動物生態が必要", "unit_future_plant": "植物組織生態が必要", "unit_available": "兵舎の生産一覧へ追加", "unit_future": "今後開放", "unit_unlocked": "解放済み", "diet_unit_footer_fmt": "%s専用部隊は対応食性の確立後に現れ、その効率で強化されます。",
		"unit_forager_desc": "汎用採集・自衛ユニット", "unit_carrier_desc": "低速・大容量の有機栄養輸送", "unit_chelator_desc": "鉱物イオンを探索・輸送", "unit_scout_desc": "高速移動して霧を自動探索", "barracks_mastered": "習得済み・兵舎で切替可能", "barracks_unlock_all": "全兵舎へ追加", "scout_stats_fmt": "感知 Lv.%d · 運動 Lv.%d · 視野 %.0f μm", "scout_vision": "感知網", "scout_speed": "鞭毛運動", "scout_upgrade_fmt": "%s %d DNA", "barracks_footer": "汎用兵種はここで、食性特化兵は各食性の専用進化で解放します。",
		"structure_branching_name": "菌糸分岐", "structure_elongation_name": "先端伸長", "structure_feeders_name": "吸収網", "structure_growth_name": "成長代謝", "structure_branching_desc": "各コアが維持できる主菌糸長を増加", "structure_elongation_desc": "1回の最大伸長距離を増加", "structure_feeders_desc": "同時に接続できる栄養点を増加", "structure_growth_desc": "新しい主菌糸の成長時間を短縮", "structure_level_fmt": "%s · Lv.%d / 4", "structure_capacity_fmt": "コア容量 %.0f μm", "structure_segment_fmt": "区間上限 %.0f μm", "structure_feeders_fmt": "同時吸収 %d本", "structure_growth_fmt": "成長時間 %.1f秒", "structure_footer": "構造進化は全胞子コアに作用し、この段階で追加レベルを取得できます。",
		"toast_node_max": "吸収菌糸範囲は現在の上限です", "toast_node_need_fmt": "有機栄養不足：強化に %.3f 必要", "toast_node_done_fmt": "ノード Lv.%d · 範囲 %.0f μm · DNA速度 +%d%%", "toast_diet_need_fmt": "DNA不足：新食性に %d 必要", "toast_diet_established_fmt": "%s確立 · 初期吸収効率 20%%", "toast_diet_max_fmt": "%sの吸収効率は100%%です", "toast_diet_level_need_fmt": "DNA不足：効率進化に %d 必要", "toast_diet_done_fmt": "%s効率が %d%% に上昇", "toast_unlock_need_fmt": "DNA不足：%sの解放に %d 必要", "toast_barracks_unlocked_fmt": "%s解放。兵舎で生産可能", "toast_upgrade_max_fmt": "%sは最大レベルです", "toast_upgrade_need_fmt": "DNA不足：%s強化に %d 必要", "toast_upgrade_done_fmt": "%sが Lv.%d に上昇", "toast_diet_required_fmt": "先に%sを確立してください", "toast_unit_unlocked_fmt": "%s解放。兵舎一覧を更新", "toast_component_need_fmt": "DNA不足：この進化に %d 必要", "toast_structure_need_fmt": "DNA不足：構造進化に %d 必要", "toast_survival_need_fmt": "DNA不足：生存進化に %d 必要", "toast_current_max_fmt": "%sは現在の上限です", "toast_level3_fmt": "%s · Lv.%d / 3", "toast_level4_fmt": "%s · Lv.%d / 4"
	},
	"es": {
		"title": "Evolución y estructura", "dna_fmt": "ADN %d", "simulation_running": "La simulación continúa", "tab_self": "Capacidades", "tab_diet": "Dieta", "tab_structure": "Estructura", "tab_barracks": "Cuartel", "tab_environment": "Adaptación", "placeholder_title": "Página preparada", "environment_placeholder": "El laboratorio no requiere adaptación climática; se usará en capítulos posteriores.", "maxed": "Nivel máximo", "maxed_short": "Máx.", "evolve_dna_fmt": "Evolucionar %d ADN", "unlock_dna_fmt": "Desbloquear %d ADN", "establish_dna_fmt": "Adoptar %d ADN", "locked": "No disponible", "mastered": "Dominado",
		"node_level_fmt": "Nodo absorbente · Nv.%d / %d", "node_core_fmt": "Núcleo de espora %d", "node_range_fmt": "Alcance de hifas %.0f μm", "node_speed_fmt": "Producción de ADN +%d%%", "node_time_fmt": "Tiempo por ADN %.1f s", "node_per_level": "Por nivel: +12 μm de alcance, +15% de velocidad", "node_cost_note": "Solo usa nutrientes orgánicos; no consume ADN", "node_action_fmt": "Mejorar %.3f", "survival_title": "Supervivencia del núcleo", "survival_wall": "Pared engrosada", "survival_detox": "Metabolismo detox", "survival_repair": "Enzimas reparadoras", "survival_storage": "Vesículas de reserva", "survival_level_fmt": "%s · %d/4", "survival_wall_effect_fmt": "Límite del núcleo %.3f", "survival_detox_effect_fmt": "Daño de toxinas %d%%", "survival_repair_effect_fmt": "Pasiva %.3f · reserva %.3f", "survival_storage_effect_fmt": "Dosis de reserva %.3f", "dna_cost_fmt": "%d ADN",
		"diet_animal_name": "Carnivoría", "diet_plant_name": "Herbivoría", "diet_bacteria_name": "Bacterivoría", "diet_fungi_name": "Micofagia", "diet_animal_target": "Tejido animal y huéspedes pequeños", "diet_plant_target": "Tejido vegetal y huéspedes", "diet_bacteria_target": "Colonias bacterianas", "diet_fungi_target": "Otros hongos y colonias", "diet_order_level_fmt": "Dieta %d · Nv.%d / 5", "diet_efficiency_fmt": "Absorción %d%%", "diet_special": "Mejoras propias", "diet_unset": "Sin adoptar; cada dieta nueva cuesta 10× más", "diet_footer": "La saprotrofia es la base del laboratorio; la dieta decide qué organismos se aprovechan.", "diet_back": "Volver a dietas", "diet_components_tab": "Componentes", "diet_units_tab": "Unidades propias",
		"component_trap_name": "Trampa adhesiva", "component_enzymes_name": "Enzimas externas", "component_antibiotic_name": "Secreción antibiótica", "component_trap_desc": "Crea hifas cazadoras finas para capturar bacterias lejanas", "component_enzymes_desc": "Convierte bacterias capturadas en nutrientes más rápido", "component_antibiotic_desc": "Ralentiza la absorción y división bacteriana cercana", "component_level_fmt": "%s · Nv.%d / 3", "component_trap_effect_fmt": "Alcance %.0f μm", "component_enzymes_effect_fmt": "Digestión ×%.2f", "component_antibiotic_effect_fmt": "Supresión %.0f μm · bacterias %d%%", "component_antibiotic_none": "Aún no hay zona", "component_footer": "Los tres componentes evolucionan en paralelo; los antibióticos frenan absorción y división.",
		"unit_animal_attach": "Anclaje depredador", "unit_animal_pierce": "Espora perforadora", "unit_animal_digest": "Cápsula digestiva", "unit_plant_fiber": "Degradador de fibra", "unit_plant_attach": "Anclaje epidérmico", "unit_plant_vessel": "Dispersor vascular", "unit_animal_attach_desc": "Se fija al tejido animal y crea un punto digestivo", "unit_animal_pierce_desc": "Ataca superficies y estructuras móviles animales", "unit_animal_digest_desc": "Descompone materia animal en un área", "unit_plant_fiber_desc": "Se alimenta de paredes celulares vegetales", "unit_plant_attach_desc": "Se fija a la superficie vegetal e inicia invasión", "unit_plant_vessel_desc": "Se extiende por el tejido conductor vegetal", "unit_lytic_desc": "Caza bacterias rápido y lleva nutrientes al nido", "unit_suppressor_desc": "Despliega una zona móvil de supresión", "unit_disperser_desc": "Mantiene distancia y libera enzimas líticas", "unit_coil_desc": "Corta hifas enemigas; las ramas aisladas mueren", "unit_piercer_desc": "Se fija a núcleos enemigos y carga un ataque", "unit_antifungal_desc": "Frena nutrición y expansión enemiga y acelera la descomposición", "unit_future_animal": "Requiere ecología de animales pequeños", "unit_future_plant": "Requiere ecología de tejido vegetal", "unit_available": "Se añade a la producción del cuartel", "unit_future": "Disponible más adelante", "unit_unlocked": "Desbloqueada", "diet_unit_footer_fmt": "Las unidades de %s aparecen tras adoptar esa dieta y escalan con su eficiencia.",
		"unit_forager_desc": "Recolección general y autodefensa", "unit_carrier_desc": "Transporte orgánico lento y de gran capacidad", "unit_chelator_desc": "Busca y transporta iones minerales", "unit_scout_desc": "Se mueve rápido y revela la niebla", "barracks_mastered": "Dominado; se elige en el cuartel", "barracks_unlock_all": "Se añade a todos los cuarteles", "scout_stats_fmt": "Sentido Nv.%d · movimiento Nv.%d · visión %.0f μm", "scout_vision": "Red sensorial", "scout_speed": "Movimiento flagelar", "scout_upgrade_fmt": "%s %d ADN", "barracks_footer": "Desbloquea aquí unidades generales; las especialistas están en cada dieta.",
		"structure_branching_name": "Ramificación hifal", "structure_elongation_name": "Extensión apical", "structure_feeders_name": "Red absorbente", "structure_growth_name": "Metabolismo de crecimiento", "structure_branching_desc": "Aumenta la longitud de hifas mantenida por cada núcleo", "structure_elongation_desc": "Aumenta la longitud máxima de una extensión", "structure_feeders_desc": "Conecta más puntos nutritivos a la vez", "structure_growth_desc": "Reduce el tiempo de crecimiento de hifas nuevas", "structure_level_fmt": "%s · Nv.%d / 4", "structure_capacity_fmt": "Capacidad por núcleo %.0f μm", "structure_segment_fmt": "Límite de segmento %.0f μm", "structure_feeders_fmt": "%d absorbentes simultáneos", "structure_growth_fmt": "Tiempo de crecimiento %.1f s", "structure_footer": "Las mejoras estructurales afectan a todos los núcleos y admiten más niveles en esta fase.",
		"toast_node_max": "El alcance está en su límite actual", "toast_node_need_fmt": "Faltan nutrientes orgánicos: se necesitan %.3f", "toast_node_done_fmt": "Nodo Nv.%d · alcance %.0f μm · velocidad ADN +%d%%", "toast_diet_need_fmt": "ADN insuficiente: una dieta nueva requiere %d", "toast_diet_established_fmt": "%s adoptada · absorción inicial 20%%", "toast_diet_max_fmt": "La absorción de %s llegó al 100%%", "toast_diet_level_need_fmt": "ADN insuficiente: la eficiencia requiere %d", "toast_diet_done_fmt": "Eficiencia de %s aumentada al %d%%", "toast_unlock_need_fmt": "ADN insuficiente: desbloquear %s requiere %d", "toast_barracks_unlocked_fmt": "%s desbloqueada; ya se produce en el cuartel", "toast_upgrade_max_fmt": "%s está al nivel máximo", "toast_upgrade_need_fmt": "ADN insuficiente: mejorar %s requiere %d", "toast_upgrade_done_fmt": "%s sube a Nv.%d", "toast_diet_required_fmt": "Primero adopta %s", "toast_unit_unlocked_fmt": "%s desbloqueada; lista del cuartel actualizada", "toast_component_need_fmt": "ADN insuficiente: esta evolución requiere %d", "toast_structure_need_fmt": "ADN insuficiente: esta evolución estructural requiere %d", "toast_survival_need_fmt": "ADN insuficiente: esta evolución de supervivencia requiere %d", "toast_current_max_fmt": "%s está en el límite actual", "toast_level3_fmt": "%s · Nv.%d / 3", "toast_level4_fmt": "%s · Nv.%d / 4"
	},
	"de": {
		"title": "Evolution & Struktur", "dna_fmt": "DNA %d", "simulation_running": "Simulation läuft weiter", "tab_self": "Fähigkeiten", "tab_diet": "Ernährung", "tab_structure": "Struktur", "tab_barracks": "Kaserne", "tab_environment": "Anpassung", "placeholder_title": "Seite vorbereitet", "environment_placeholder": "Im Labor ist keine Klimaanpassung nötig; diese Seite folgt in späteren Kapiteln.", "maxed": "Maximalstufe", "maxed_short": "Max.", "evolve_dna_fmt": "Entwickeln %d DNA", "unlock_dna_fmt": "Freischalten %d DNA", "establish_dna_fmt": "Wählen %d DNA", "locked": "Nicht verfügbar", "mastered": "Erlernt",
		"node_level_fmt": "Nährknoten · St.%d / %d", "node_core_fmt": "Sporenkern %d", "node_range_fmt": "Nährhyphen %.0f μm", "node_speed_fmt": "DNA-Produktion +%d%%", "node_time_fmt": "Zeit je DNA %.1f s", "node_per_level": "Je Stufe: +12 μm Reichweite, +15% DNA-Tempo", "node_cost_note": "Kostet nur Organik, keine DNA", "node_action_fmt": "Stärken %.3f", "survival_title": "Kernüberleben", "survival_wall": "Dickere Zellwand", "survival_detox": "Entgiftung", "survival_repair": "Reparaturenzyme", "survival_storage": "Reservevesikel", "survival_level_fmt": "%s · %d/4", "survival_wall_effect_fmt": "Kernlimit %.3f", "survival_detox_effect_fmt": "Toxinschaden %d%%", "survival_repair_effect_fmt": "Passiv %.3f · Reserve %.3f", "survival_storage_effect_fmt": "Reservedosis %.3f", "dna_cost_fmt": "%d DNA",
		"diet_animal_name": "Karnivorie", "diet_plant_name": "Herbivorie", "diet_bacteria_name": "Bakterivorie", "diet_fungi_name": "Mykophagie", "diet_animal_target": "Tiergewebe und kleine Wirte", "diet_plant_target": "Pflanzengewebe und Wirte", "diet_bacteria_target": "Bakterienkolonien", "diet_fungi_target": "Andere Pilze und Kolonien", "diet_order_level_fmt": "Ernährung %d · St.%d / 5", "diet_efficiency_fmt": "Aufnahme %d%%", "diet_special": "Spezial-Upgrades", "diet_unset": "Nicht gewählt; jede neue Ernährung kostet 10× mehr", "diet_footer": "Saprotrophie bleibt die Laborbasis; die Ernährung bestimmt nutzbare Organismen.", "diet_back": "Zurück", "diet_components_tab": "Komponenten", "diet_units_tab": "Spezialeinheiten",
		"component_trap_name": "Klebefalle", "component_enzymes_name": "Außenenzyme", "component_antibiotic_name": "Antibiotikasekretion", "component_trap_desc": "Feine Jagdhyphen fangen Bakterien aus größerer Entfernung", "component_enzymes_desc": "Wandelt gefangene Bakterien schneller in Organik um", "component_antibiotic_desc": "Bremst Aufnahme und Teilung naher Bakterien", "component_level_fmt": "%s · St.%d / 3", "component_trap_effect_fmt": "Fangweite %.0f μm", "component_enzymes_effect_fmt": "Verdauung ×%.2f", "component_antibiotic_effect_fmt": "Hemmung %.0f μm · Bakterien %d%%", "component_antibiotic_none": "Noch keine Hemmzone", "component_footer": "Alle drei Komponenten entwickeln sich parallel; Antibiotika bremsen Aufnahme und Teilung.",
		"unit_animal_attach": "Räuber-Haftkörper", "unit_animal_pierce": "Stechspore", "unit_animal_digest": "Verdauungskapsel", "unit_plant_fiber": "Faserabbauer", "unit_plant_attach": "Epidermis-Haftkörper", "unit_plant_vessel": "Leitbahn-Verteiler", "unit_animal_attach_desc": "Haftet an Tiergewebe und bildet eine Verdauungsstelle", "unit_animal_pierce_desc": "Greift Tieroberflächen und Bewegungsstrukturen an", "unit_animal_digest_desc": "Zersetzt tierische Organik im Umkreis", "unit_plant_fiber_desc": "Frisst pflanzliche Zellwände", "unit_plant_attach_desc": "Verankert sich an Pflanzen und beginnt den Befall", "unit_plant_vessel_desc": "Breitet sich entlang pflanzlicher Leitgewebe aus", "unit_lytic_desc": "Jagt Bakterien schnell und bringt Nährstoffe zurück", "unit_suppressor_desc": "Errichtet eine versetzbare Hemmzone", "unit_disperser_desc": "Hält Abstand und setzt Lyseenzyme frei", "unit_coil_desc": "Trennt Feindhyphen; isolierte Äste welken", "unit_piercer_desc": "Haftet an Feindkernen und lädt einen Bohrangriff", "unit_antifungal_desc": "Bremst Feindaufnahme und -wachstum; isolierte Hyphen zerfallen schneller", "unit_future_animal": "Benötigt Kleintier-Ökologie", "unit_future_plant": "Benötigt Pflanzengewebe-Ökologie", "unit_available": "Zur Kasernenproduktion hinzufügen", "unit_future": "Später verfügbar", "unit_unlocked": "Freigeschaltet", "diet_unit_footer_fmt": "%s-Einheiten erscheinen erst nach Wahl dieser Ernährung und skalieren mit ihrer Effizienz.",
		"unit_forager_desc": "Allgemeines Sammeln und Selbstschutz", "unit_carrier_desc": "Langsamer Organiktransport mit hoher Kapazität", "unit_chelator_desc": "Sucht und transportiert Mineralionen", "unit_scout_desc": "Bewegt sich schnell und deckt Nebel auf", "barracks_mastered": "Erlernt; in Kasernen wählbar", "barracks_unlock_all": "Für alle Kasernen freischalten", "scout_stats_fmt": "Sinn St.%d · Bewegung St.%d · Sicht %.0f μm", "scout_vision": "Sensornetz", "scout_speed": "Geißelbewegung", "scout_upgrade_fmt": "%s %d DNA", "barracks_footer": "Allgemeine Einheiten hier; Ernährungsspezialisten unter Spezial-Upgrades.",
		"structure_branching_name": "Hyphenverzweigung", "structure_elongation_name": "Spitzenwachstum", "structure_feeders_name": "Nährnetz", "structure_growth_name": "Wachstumsstoffwechsel", "structure_branching_desc": "Erhöht die von jedem Kern getragene Haupthyphenlänge", "structure_elongation_desc": "Erhöht die maximale Länge einer Verlängerung", "structure_feeders_desc": "Verbindet mehr Nährpunkte gleichzeitig", "structure_growth_desc": "Verkürzt die Wachstumszeit neuer Haupthyphen", "structure_level_fmt": "%s · St.%d / 4", "structure_capacity_fmt": "Kapazität je Kern %.0f μm", "structure_segment_fmt": "Segmentlimit %.0f μm", "structure_feeders_fmt": "%d Nährhyphen gleichzeitig", "structure_growth_fmt": "Wachstumszeit %.1f s", "structure_footer": "Struktur-Upgrades wirken auf alle Sporenkerne und können in dieser Phase weiter steigen.",
		"toast_node_max": "Nährreichweite am aktuellen Limit", "toast_node_need_fmt": "Zu wenig Organik: Verstärkung benötigt %.3f", "toast_node_done_fmt": "Knoten St.%d · Reichweite %.0f μm · DNA-Tempo +%d%%", "toast_diet_need_fmt": "Zu wenig DNA: neue Ernährung benötigt %d", "toast_diet_established_fmt": "%s gewählt · Startaufnahme 20%%", "toast_diet_max_fmt": "%s-Aufnahme hat 100%% erreicht", "toast_diet_level_need_fmt": "Zu wenig DNA: Effizienz benötigt %d", "toast_diet_done_fmt": "%s-Effizienz auf %d%% erhöht", "toast_unlock_need_fmt": "Zu wenig DNA: %s benötigt %d", "toast_barracks_unlocked_fmt": "%s freigeschaltet; jetzt in Kasernen produzierbar", "toast_upgrade_max_fmt": "%s ist auf Maximalstufe", "toast_upgrade_need_fmt": "Zu wenig DNA: %s benötigt %d", "toast_upgrade_done_fmt": "%s auf St.%d erhöht", "toast_diet_required_fmt": "Zuerst %s wählen", "toast_unit_unlocked_fmt": "%s freigeschaltet; Kasernenliste aktualisiert", "toast_component_need_fmt": "Zu wenig DNA: diese Evolution benötigt %d", "toast_structure_need_fmt": "Zu wenig DNA: Strukturevolution benötigt %d", "toast_survival_need_fmt": "Zu wenig DNA: Überlebensevolution benötigt %d", "toast_current_max_fmt": "%s ist am aktuellen Limit", "toast_level3_fmt": "%s · St.%d / 3", "toast_level4_fmt": "%s · St.%d / 4"
	},
	"ru": {
		"title": "Эволюция и структура", "dna_fmt": "ДНК %d", "simulation_running": "Симуляция продолжается", "tab_self": "Способности", "tab_diet": "Питание", "tab_structure": "Структура", "tab_barracks": "Казарма", "tab_environment": "Адаптация", "placeholder_title": "Раздел готов", "environment_placeholder": "В лаборатории климатическая адаптация не нужна; раздел появится в следующих главах.", "maxed": "Макс. уровень", "maxed_short": "Макс.", "evolve_dna_fmt": "Эволюция %d ДНК", "unlock_dna_fmt": "Открыть %d ДНК", "establish_dna_fmt": "Принять %d ДНК", "locked": "Недоступно", "mastered": "Освоено",
		"node_level_fmt": "Питающий узел · ур.%d / %d", "node_core_fmt": "Споровое ядро %d", "node_range_fmt": "Радиус гиф %.0f μm", "node_speed_fmt": "Производство ДНК +%d%%", "node_time_fmt": "Время на ДНК %.1f с", "node_per_level": "За уровень: +12 μm радиуса, +15% скорости ДНК", "node_cost_note": "Тратит только органику, без ДНК", "node_action_fmt": "Усилить %.3f", "survival_title": "Выживание ядра", "survival_wall": "Толстая стенка", "survival_detox": "Детоксикация", "survival_repair": "Ферменты ремонта", "survival_storage": "Запасные везикулы", "survival_level_fmt": "%s · %d/4", "survival_wall_effect_fmt": "Предел ядра %.3f", "survival_detox_effect_fmt": "Урон токсинов %d%%", "survival_repair_effect_fmt": "Пассивно %.3f · запас %.3f", "survival_storage_effect_fmt": "Порция запаса %.3f", "dna_cost_fmt": "%d ДНК",
		"diet_animal_name": "Плотоядность", "diet_plant_name": "Растительноядность", "diet_bacteria_name": "Бактериофагия", "diet_fungi_name": "Микофагия", "diet_animal_target": "Ткани животных и малые хозяева", "diet_plant_target": "Ткани растений и хозяева", "diet_bacteria_target": "Колонии бактерий", "diet_fungi_target": "Другие грибы и колонии", "diet_order_level_fmt": "Питание %d · ур.%d / 5", "diet_efficiency_fmt": "Поглощение %d%%", "diet_special": "Особые улучшения", "diet_unset": "Не принято; каждое новое питание дороже в 10×", "diet_footer": "Сапротрофия остаётся основой лаборатории; питание определяет доступные организмы.", "diet_back": "Назад к питанию", "diet_components_tab": "Компоненты", "diet_units_tab": "Особые бойцы",
		"component_trap_name": "Липкая ловушка", "component_enzymes_name": "Внешние ферменты", "component_antibiotic_name": "Секреция антибиотика", "component_trap_desc": "Тонкие охотничьи гифы ловят далёкие бактерии", "component_enzymes_desc": "Быстрее превращает бактерии в органику", "component_antibiotic_desc": "Замедляет питание и деление близких бактерий", "component_level_fmt": "%s · ур.%d / 3", "component_trap_effect_fmt": "Радиус захвата %.0f μm", "component_enzymes_effect_fmt": "Пищеварение ×%.2f", "component_antibiotic_effect_fmt": "Подавление %.0f μm · бактерии %d%%", "component_antibiotic_none": "Зоны подавления нет", "component_footer": "Три компонента развиваются параллельно; антибиотик тормозит питание и деление.",
		"unit_animal_attach": "Хищный фиксатор", "unit_animal_pierce": "Прокалывающая спора", "unit_animal_digest": "Пищеварительная капсула", "unit_plant_fiber": "Расщепитель волокон", "unit_plant_attach": "Эпидермальный фиксатор", "unit_plant_vessel": "Сосудистый рассеватель", "unit_animal_attach_desc": "Крепится к ткани животного и создаёт точку пищеварения", "unit_animal_pierce_desc": "Атакует поверхность и органы движения животного", "unit_animal_digest_desc": "Расщепляет животную органику по площади", "unit_plant_fiber_desc": "Питается клеточными стенками растений", "unit_plant_attach_desc": "Крепится к растению и начинает вторжение", "unit_plant_vessel_desc": "Распространяется по проводящим тканям растения", "unit_lytic_desc": "Быстро охотится на бактерии и несёт питание домой", "unit_suppressor_desc": "Развёртывает переносную зону подавления", "unit_disperser_desc": "Держит дистанцию и выпускает лизирующие ферменты", "unit_coil_desc": "Режет гифы врага; изолированные ветви увядают", "unit_piercer_desc": "Крепится к ядру врага и заряжает прокол", "unit_antifungal_desc": "Тормозит питание и рост врага; изолированные гифы распадаются быстрее", "unit_future_animal": "Нужна экология малых животных", "unit_future_plant": "Нужна экология растительных тканей", "unit_available": "Добавить в производство казарм", "unit_future": "Будет позже", "unit_unlocked": "Открыто", "diet_unit_footer_fmt": "Бойцы %s появляются после принятия этого питания и усиливаются его эффективностью.",
		"unit_forager_desc": "Общий сбор и самооборона", "unit_carrier_desc": "Медленная перевозка большого объёма органики", "unit_chelator_desc": "Ищет и переносит минеральные ионы", "unit_scout_desc": "Быстро движется и открывает туман", "barracks_mastered": "Освоено; доступно в казармах", "barracks_unlock_all": "Добавить во все казармы", "scout_stats_fmt": "Чутьё ур.%d · движение ур.%d · обзор %.0f μm", "scout_vision": "Сенсорная сеть", "scout_speed": "Движение жгутиков", "scout_upgrade_fmt": "%s %d ДНК", "barracks_footer": "Общие бойцы открываются здесь; специалисты — в особых улучшениях питания.",
		"structure_branching_name": "Ветвление гиф", "structure_elongation_name": "Рост кончика", "structure_feeders_name": "Питающая сеть", "structure_growth_name": "Метаболизм роста", "structure_branching_desc": "Увеличивает длину главных гиф на каждое ядро", "structure_elongation_desc": "Увеличивает длину одного удлинения", "structure_feeders_desc": "Соединяет больше точек питания одновременно", "structure_growth_desc": "Сокращает рост новых главных гиф", "structure_level_fmt": "%s · ур.%d / 4", "structure_capacity_fmt": "Ёмкость ядра %.0f μm", "structure_segment_fmt": "Предел сегмента %.0f μm", "structure_feeders_fmt": "Питающих гиф: %d", "structure_growth_fmt": "Время роста %.1f с", "structure_footer": "Структурные улучшения действуют на все ядра и могут расти в этой стадии.",
		"toast_node_max": "Радиус гиф достиг текущего предела", "toast_node_need_fmt": "Мало органики: для усиления нужно %.3f", "toast_node_done_fmt": "Узел ур.%d · радиус %.0f μm · скорость ДНК +%d%%", "toast_diet_need_fmt": "Мало ДНК: новое питание требует %d", "toast_diet_established_fmt": "%s принято · начальное поглощение 20%%", "toast_diet_max_fmt": "Поглощение %s достигло 100%%", "toast_diet_level_need_fmt": "Мало ДНК: эффективность требует %d", "toast_diet_done_fmt": "Эффективность %s повышена до %d%%", "toast_unlock_need_fmt": "Мало ДНК: для %s нужно %d", "toast_barracks_unlocked_fmt": "%s открыто; доступно в казармах", "toast_upgrade_max_fmt": "%s на максимальном уровне", "toast_upgrade_need_fmt": "Мало ДНК: улучшение %s требует %d", "toast_upgrade_done_fmt": "%s повышено до ур.%d", "toast_diet_required_fmt": "Сначала примите %s", "toast_unit_unlocked_fmt": "%s открыто; список казарм обновлён", "toast_component_need_fmt": "Мало ДНК: эта эволюция требует %d", "toast_structure_need_fmt": "Мало ДНК: структурная эволюция требует %d", "toast_survival_need_fmt": "Мало ДНК: эволюция выживания требует %d", "toast_current_max_fmt": "%s достигло текущего предела", "toast_level3_fmt": "%s · ур.%d / 3", "toast_level4_fmt": "%s · ур.%d / 4"
	}
}


static func normalize_locale(locale_id: String) -> String:
	var value := locale_id.strip_edges().replace("-", "_").to_lower()
	if value.begins_with("zh_hant") or value.begins_with("zh_tw") or value.begins_with("zh_hk") or value.begins_with("zh_mo"):
		return "zh_TW"
	if value.begins_with("zh"):
		return "zh_CN"
	for locale_id_value in ["en", "ja", "es", "de", "ru"]:
		if value == locale_id_value or value.begins_with(locale_id_value + "_"):
			return locale_id_value
	return "en"


static func text(key: String, locale_id: String) -> String:
	var locale := normalize_locale(locale_id)
	var table: Dictionary = TEXTS.get(locale, TEXTS["en"])
	if table.has(key):
		return String(table[key])
	return String((TEXTS["en"] as Dictionary).get(key, key))
